### ISSUE TITLE
Why does google insistently alerts that someone else's trying to access my account?

### ISSUE THREAD

**Issue by luisfsr** [deltachat/deltachat-android#231] opened 2017-12-27 23:47 UTC
When me and my fiancée use DC we both receive messages from google that someone else may have our passwords. We are users of K9-mail and never had that issue (so it's not just because it's not a google program). We're not 100% sure, but we believe that this is something related to DC because those warnings started when we started using DC. I'm not worried about that, but that would be worrisome to other people... But I'm curious why that happens and if that happens to others, as well as if there's someone working in a fix. Thanks!

**Comment by csb0730** [comment] 2017-12-28 23:16
I got a similar message by GMX into web interface: "Failed access by external mail program".
But this was caused by a not activated external access of the account (IMAP/SMTP).
I think this is not the same root cause than your's because You are using the working account?

**Comment by luisfsr** [comment] 2017-12-29 09:53
Yes. I'm using my Google account. Everything is set up. Pop/SMTP/IMAP and "less secure apps" are activated.

**Comment by nutpantz** [comment] 2018-01-04 04:47
I get that message every time my phone connects to a new Wi-Fi spot
And 99/100 times I can't get my mail them until I'm back on mobile or my usual network.
It's Google "we don't trust you to have a secure password / different device/new location "protection.

**Comment by r10s** [comment] 2018-03-11 17:48
i think this is more a Google than a Delta Chat issue.

closing now, if there are any concrete things we can do about this, we should reopen the issue.

**Closed by r10s** 2018-03-11 17:48 UTC
