### ISSUE TITLE
Portrait to landscape photography

### ISSUE THREAD

**Issue by AndreasLattmann** [deltachat/deltachat-android#1234] opened 2020-02-01 22:14 UTC
- Android: 9
- Device: Huawei HMA-L29
- Delta Chat version: 1.1.2 - 1.2.0
- Expected behavior: When I click on the camera icon and take a photograph with the phone rotated in landscape orientation, I expect that when the image is sent it will be rotated from landascape to portrait orientation.
- Actual behavior: When I click on the icon and take a photograph in landscape orientation, the photograph is sent without first rotating it.  The contact who will receive the sent photo will see it rotated 90 ° forcing him to "bend his head" to see the photograph.
- Steps to reproduce the problem: Click on the camera icon, rotate the phone 90 °, take the photograph.
- Screenshots: 

![portrait](https://user-images.githubusercontent.com/58994349/73599822-5b4dab00-4548-11ea-9d1f-c4a0e8f59690.jpg)

![landscape](https://user-images.githubusercontent.com/58994349/73599823-630d4f80-4548-11ea-87e6-6615dd2495ad.jpg)

**Comment by angelo-fuchs** [comment] 2020-02-06 21:38
I could not reproduce this. After about 3 seconds the orientation always switches (except it is set to not switch in the android system, of course).

Do you have custom settings on your phone (Camera App, Orientation Lock, ...?)

**Comment by AndreasLattmann** [comment] 2020-02-07 11:32
I have to investigate why the image doesn't rotate. I check if there is any setting on Android.

**Comment by AndreasLattmann** [comment] 2020-02-07 11:37
Found, automatic rotation is disabled.  Even if I get another mistake.

If I click on the camera icon and rotate the phone, the screen remains black (see screenshot).
![Screenshot_20200207_123523_com b44t messenger beta](https://user-images.githubusercontent.com/58994349/74026500-9f0c3e80-49a6-11ea-9982-f141ba61540d.jpg)

**Comment by angelo-fuchs** [comment] 2020-02-08 18:42
Could you try to change to front / back camera and back again?

I remember that I once had that same issue (long ago) and it turned out to be an issue with my camera app. (Couldn't figure out what exactly it was)

Could you try to restart your phone and open DC first and see if it works then?

**Comment by AndreasLattmann** [comment] 2020-02-08 19:30
I tried, but it doesn't solve the problem permanently.  I also tried to restart, but the situation does not change.  I use the trick of changing with the front / back camera to temporarily solve the problem, but I think an end user is not happy with using tricks to make the app work.  🤔

**Comment by angelo-fuchs** [comment] 2020-02-08 21:50
@AndreasLattmann I agree, but it is possible that we can't fix it (because its an issue with the phone/droid version combination) and then having a workaround available (and ideally know the combination that causes the problem) is better then nothing :)

Nonetheless this is a different issue. I will close this one.

**Comment by angelo-fuchs** [comment] 2020-02-08 21:54
New issue for new problem, old issue solved.

**Closed by angelo-fuchs** 2020-02-08 21:54 UTC
Labels: bug, needs-retry

**Comment by AndreasLattmann** [comment] 2020-02-09 19:09
Ok! 😁
