### ISSUE TITLE
Notifications are too much intrusive

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#451] opened 2018-12-20 22:17 UTC
Notification messages are too much intrusive/annoying. They are showing up while the user is writing in a chat or while seeing the chat list. In v0.20 the notification icon is shown in the "status bar" and sound is played but users aren't disturbed with a notification dialog showing up on the screen while they are chatting, this can be really annoying if the user start to receive several messages from other chats while in a conversation.
 
- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.92

**Comment by angelo-fuchs** [comment] 2019-01-22 14:08
@adbenitez Could you post a screenshot of such a notification "showing up"? When I just tested it, the vibration went off, the sound was heard and the message scrolled through the status window, but nothing that would stop me from continuing writing. (Maybe my phone can't display that kind of notification which would explain why I didn't notice it earlier)

I will work on the frequency of the vibration / sound thing

**Comment by adbenitez** [comment] 2019-01-22 16:59
will start testing this, screenshots coming soon...

**Comment by adbenitez** [comment] 2019-01-22 17:07
At the chats list:
if user is at the chat list, and receives a message, do he really needs the notification??
As an user my UX with this is a total disaster I feel really bad with this since I just want to tap in the chat in the list, but the notification feels intrusive, when a chat have a message it is shown at the top of the list and the notification is blocking the view, all the info I need is already in the chat list, I think there are no need for a notification here...
Screenshot:
![screenshot_20190122-114145](https://user-images.githubusercontent.com/24558636/51552258-335c3f80-1e3e-11e9-9796-ced1e710ab9c.png)

**Comment by r10s** [comment] 2019-01-22 17:21
> if user is at the chat list, and receives a message, do he really needs the notification??

i think, if the user is in a chat or in a chatlist, notifications should be shown by an icon in the statusbar only.
and notifications for an opened chat can be skipped at all.

**Comment by adbenitez** [comment] 2019-01-22 17:32
(note: all this tests are in 0.98.2)
In-chat notifications (part 1):
When I am in a private (1x1) chat and the other user sends me a message, the app now works fine, no notification is created at all, since I am in the chat and can see the message, if the cell is in vibrate-mode it works fine and do not vibrate, but otherwise still the notification sound is played, mine is soft one, but a friend have set a notification sound that is quite noisy (rock music) and I can imagine other people with loud notifications also, all them will hate that the notification sound is played for messages from the current chat, 0.20 used a soft "bubble pop", we don't have to use the same, but at least something that is audible but not annoying like the old one.

**Comment by adbenitez** [comment] 2019-01-22 18:12
In-chat notifications (part 2):
If I am typing in a chat and other people start sending messages, (as example, imagine you are chatting with someone and 5 friends and some groups start sending messages at the same time) it is annoying to have the notifications constantly showing up, playing the notification sound and the phone buzzing like a bumblebee, while you try to focus and reply faster, it feels a bit stressing...
Notifying is fine in this situation but in a more discrete way(ex. just showing the notification icon and maybe a soft sound), since user isn't a mile away from the phone ;) 
I understand that in some cases the current behaviour may be useful (ex. to quickly reply to a friend right from the other chat) so no hard feelings if you just ignore this comment...

Screenshot:
![screenshot_20190122-121412](https://user-images.githubusercontent.com/24558636/51556048-11b38600-1e47-11e9-9ac0-80ad6c57b787.png)

**Comment by angelo-fuchs** [comment] 2019-01-22 19:05
@adbenitez Ok, as I thought its something that is not shown on my phone :( I will need a different device to test (and then remove) it. Looks terrible.

**Comment by angelo-fuchs** [comment] 2019-01-25 14:43
@r10s Maybe I'm getting a newer phone just to test this issue :) (wrt Min SDK Version)

**Comment by angelo-fuchs** [comment] 2019-01-29 12:59
Just tested together with @Simon-Laux and have seen whats going on. I'll have a look at the code.

**Comment by r10s** [comment] 2019-01-29 13:04
btw, i also realized that the order of the notified messages may be wrong. i the phones notifies "MessageA" and then after a minute "MessageB", both are shown when enlarging the notifications, however, the short popup that is displayed during the sound always shows "MessageA".

**Comment by angelo-fuchs** [comment] 2019-01-29 13:09
@r10s Is that true regardless of quite time (20 seconds) between messages?

**Comment by adbenitez** [comment] 2019-01-29 16:15
yeah, I am annoyed by this but I was thinking it was the intended behavior  of the devs...

**Comment by r10s** [comment] 2019-01-29 19:48
@angelo-fuchs yip, it's still true. it's only the order. happens wenn the app was not used between MessageA and MessageB.

**Comment by angelo-fuchs** [comment] 2019-01-31 13:49
@r10s Can't reproduce. Need to see it on your phone.

**Comment by angelo-fuchs** [comment] 2019-02-14 17:02
As I can't reproduce this on my phone I also can't fix it.

**Comment by cyBerta** [comment] 2019-05-15 16:09
> btw, i also realized that the order of the notified messages may be wrong. i the phones notifies "MessageA" and then after a minute "MessageB", both are shown when enlarging the notifications, however, the short popup that is displayed during the sound always shows "MessageA".

I've addressed that issue with commit 47cba2dc51da4d3effd838bc2b54a68b7354e92a

**Comment by cyBerta** [comment] 2019-05-15 16:18
https://github.com/deltachat/deltachat-android/issues/432
<-- This behavior is still the same, though I think it's fine actually. If you mute the conversation, there is no in-chat notification sound otherwise there is a sound (but no further distraction like a notification view)

**Comment by r10s** [comment] 2019-05-15 18:28
in general, i think messages coming in the active chat should not be notified at all via the system, not sure if this is the current state of the pr, however, this is the desired behavior.

wrt sound: we have the option "In-Chat sounds" - i think this should be regarded exactly for that purpose.

however, i'd suggest to never play the "notification" sound but a short and decent "plopp", this one: https://github.com/deltachat/deltachat-android-old/blob/master/MessengerProj/src/main/res/raw/sound_in.wav

**Comment by r10s** [comment] 2019-05-15 18:33
@cyBerta the sound_in should not be played via the notification-channel or so, but using a SoundPool:

we did this on the telegram-version as follows:

https://github.com/deltachat/deltachat-android-old/blob/master/MessengerProj/src/main/java/com/b44t/messenger/NotificationsController.java#L913

and if you're on this, i'd also add the corresponding "plipp" for outgoing messages: https://github.com/deltachat/deltachat-android-old/blob/master/MessengerProj/src/main/res/raw/sound_out.wav

**Comment by cyBerta** [comment] 2019-05-16 09:37
> also, system-info-messages as "group member added" should not be notified.
fixed with https://github.com/deltachat/deltachat-android/pull/915/commits/28fbb354b3a992929758f90abbb05be1f6cb1848

**Comment by r10s** [comment] 2019-06-04 21:09
targeted by #915 and related commits

**Closed by r10s** 2019-06-04 21:09 UTC
Labels: notifications
