### ISSUE TITLE
markseen is sent when a chat is open but the display is off

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1850] opened 2021-03-28 10:08 UTC
a read-receipt is sent immediately when Alice sends a message to Bob and Bob has the chat open and Delta Chat was the last active app and the display is off.

the read-receipt should be sent only, if the message is really displayed to the user.

the issue is on current master, not tested, however, i think, this was correct at some point (in this case, this issue should be regarded even as a blocker).

**Comment by gerryfrancis** [comment] 2021-04-11 17:44
Confirmed. Side effect on Delta Chat for Android: No notification received either when device is on standby...

**Comment by Hocuri** [comment] 2021-04-18 11:03
Strange, I can't reproduce this, neither on Android 10 nor on Android 7

**Comment by gerryfrancis** [comment] 2021-04-18 16:15
Hm, I cannot reproduce it (anymore) either with the latest nightly build...

**Comment by r10s** [comment] 2021-04-28 20:46
the issue is still there for me, i just retested that on master (and filed a duplicate issue #1900 accidentally :)

**Comment by adbenitez** [comment] 2021-05-13 17:29
I can't reproduce this in my phone (android 10), what I tried:
1. chat with user X open, press power button to turn off screen, send message from other device with X's account, the notification sound plays, after some minutes still no read receipts arrive, turning on screen and unlocking then when the chat is shown the read receipts are sent.
2. the same as above but instead of manually pressing power button I waited for the screen to turn off, in both cases everything was fine.

**Comment by adbenitez** [comment] 2021-05-13 17:34
maybe it is some old android version that is not calling `onPause()` properly if screen times out?

**Comment by r10s** [comment] 2021-05-13 18:39
might be related android version, indeed. i encountered the issue on android7.

**Comment by gerryfrancis** [comment] 2021-05-13 19:10
Never had an older Android version than 10, and I encountered the issue as well, but not anymore... :/

**Comment by AndreaLattmann** [comment] 2023-04-06 16:35
I've tried with two smartphones and I can't reproduce this bug. DC 1.36.2

**Comment by adbenitez** [comment] 2023-09-25 23:50
just tried in android 13, could not reproduce, closing this issue until someone reports they can reproduce and help testing patches for the issue

**Closed by adbenitez** 2023-09-25 23:50 UTC
Labels: bug, needs-retry
