### ISSUE TITLE
Error accepting new chat

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#419] opened 2019-01-03 17:22 UTC
When I accept a chat something weird is happening with the date label, also the bottom bar, with the textview for typing a message and buttons for sending attachments are not shown at all, I have to go back and open the chat again.

- Platform (android/blackberry/anbox): Android
- Device: BLU
- Delta Chat Version: 0.79.1
- Steps to reproduce the problem: go to the contact requests view, and tap on a message and accept to chat.
- Screenshots:
![screenshot_20190102-124712](https://user-images.githubusercontent.com/24558636/50651689-1e347500-0f52-11e9-8a2d-c4f9a4e5618e.png)

**Comment by angelo-fuchs** [comment] 2019-01-25 18:56
I think here are two separate problems:
1. The Date
I could reproduce this: Having more then one message appear after accepting a contact request (and before returning to contact list) causes this problem. It does not happen with just one message. It is not relevant if the second message was already in the contact requests or came afterwards.

2. The Input bar
This seems to be connected with the contact request "ConversationActivity" as we hide the input there and then don't redraw the activity.

Maybe both can be solved by forcing a new activity to be created with the Intent (as the problem disappears if we go back to the contact list and then into the chat)

**Comment by r10s** [comment] 2019-02-14 00:17
yip, also have the feeling this is releated to always reusing the same activity and onNewIntent() which makes things a bit harder and unpredictable. cmp #420

**Comment by r10s** [comment] 2019-05-06 10:04
not really "forward and share" but might be related very closely to issues we have there.

**Comment by r10s** [comment] 2019-05-10 11:54
i assume this is fixed by #895, feel free to re-open if this is not the case :)

**Closed by r10s** 2019-05-10 11:54 UTC
Labels: bug, fwdAndShare
