### ISSUE TITLE
Update creates new instance

### ISSUE THREAD

**Issue by thomas374b** [deltachat/deltachat-android#2072] opened 2021-10-06 11:24 UTC
- Android version: 4.3
- Device: GalaxyS gti9003

- Delta Chat version:  1.20.5 installed,  updating to 1.22.1 

- Expected behavior: 
     On installation of the new APK file the existing installation gets overwritten/is updated and the actual settings are taken over.

- Actual behavior: 
    A secondary instance of the program gets installed side by side. In the menu there is two times the same DC-icon visible which makes it hard to distinguish between the two versions. The newly installed version remains unconfigured.   One must backup ("export chats to external server") and uninstall the old version first, install the new version and import the backup.

- Steps to reproduce the problem:
    -  Install version 1.20.5 and configure a user account, start chatting with someone
    -  download APK file for version 1.22.1
    - enable installation of "foreign packages"
    - double tap on new APK-file in file manager to start the new installation

**Comment by Hocuri** [comment] 2021-10-06 12:21
This is expected, so you can use both the development version and the Play Store version. But how did you install 1.20.5? It should be possible to upgrade by using the same installation method.

**Comment by Hocuri** [comment] 2021-10-06 12:23
Also, what's in the log of 1.20.5? (Settings -> Advanced -> View Log). I'm interested in the lines starting with "app" and "installer"

**Comment by adbenitez** [comment] 2021-10-29 21:56
that you can install f-droid and gplay versions side by side is expected, so can this issue be closed then?

**Comment by thomas374b** [comment] 2021-10-30 00:14
If there are two different versions, they should be distinguishable.  I suggest to give one version a slightly different coloring (brighter, darker)

As for now they appear exactly with the same icon.

**Comment by adbenitez** [comment] 2021-10-30 00:23
Hi @thomas374b, I understand you would like that, but that is a feature request, not a bug, you could create a discussion about it at https://support.delta.chat/ so other Delta Chat users could comment,

in my opinion it is not needed that F-Droid and Google Play versions have different icons, usually apps have the same icons in all stores, you probably should use a launcher that allows editing app icons or adding tags to apps like the KISS launcher so you could tag one app as "fdroid" and the other as "gplay" and you could differentiate the apps that way.

Will close this issue if there is no bug to fix, and it is a rather controversial topic if we should use different icons or not so the forum is more appropriate for discussions, thanks a lot for taking care! see you in the forum, 

best regards,
adb

**Closed by adbenitez** 2021-10-30 00:23 UTC
