### ISSUE TITLE
Draft lost if app is swiped out from the recent list

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#743] opened 2019-02-25 19:11 UTC
If you are writing some message, then stop writing and minimize Delta Chat, then go to the recent list and swipe/close the app from there, the draft is lost!! this may be the cause of https://github.com/deltachat/deltachat-android/issues/420, seems like the draft is not saved in `onPause()`????

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU (RAM<500MB, low mem device)
- Delta Chat Version: 0.101.1

**Comment by adbenitez** [comment] 2019-03-04 15:57
in this situation, k9 do save the draft.

**Comment by r10s** [comment] 2019-03-05 23:12
for me, the draft is saved.
again, it seems that onDestroy() is not called because of low memory.

**Comment by r10s** [comment] 2019-03-05 23:13
wrt k9, well might be that the draft is saved under different circumstances or that the app was just not killed, maybe it consumes less memory in total or so.

**Comment by adbenitez** [comment] 2019-03-06 01:08
DeltaChat isn't killed! if I minimize DeltaChat and go back to it the app is resumed from where it was in the chat with the draft still there, for some reason dc isn't saving the draft when I minimize it, the app isn't destroyed until I do it manually swiping out the app from the recent list, k9 save the draft as soon as I minimize the app (a toast is shown saying that the draft was saved)
(my system kill the minimized app if I open another memory consuming app, but I am not doing it)

**Comment by adbenitez** [comment] 2019-03-06 01:21
if it is easy to do, I can test a debug apk which print a toast on screen when the draft is saved to test this on my device, if you think this isn't worthy I am ok if you close this issue :)

**Comment by adbenitez** [comment] 2019-03-06 01:22
I mean, if it easy to you to provide such apk to me, I can't compile it by myself atm :(

**Comment by r10s** [comment] 2019-03-06 09:21
i think it's worth some tries, however, just now, me personally is not up for that :)

**Comment by adbenitez** [comment] 2019-04-30 14:08
ok, tested this on a tablet from my work with GBs of RAM, and it also happens, the tablet has Android 6.0.1 so this is not a low RAM problem, seems like it is something realated to Android versions (Android 6 in this case)
can someone else with Android 6 confirm this??
Steps to reproduce:
1. Open Delta Chat and open a Chat
2. Write something, but don't send it.
3. Minimize Delta Chat and go to your recent apps list (at this point the message you typed should be saved as a draft)
4. Swipe out Delta Chat from the recent apps list
5. Open Delta Chat again
6. The draft is lost, it wasn't saved

**Comment by r10s** [comment] 2019-04-30 21:02
@adbenitez thanks for the details explanations. great report, as always :) this will probably help a lot on investigate on this issue.

**Comment by angelo-fuchs** [comment] 2019-12-27 23:42
I can reproduce this, will see if I can fix it.

**Comment by r10s** [comment] 2019-12-29 11:26
> I can reproduce this, will see if I can fix it.

great!

**Comment by r10s** [comment] 2019-12-29 18:50
fixed in https://github.com/deltachat/deltachat-android/pull/1192

**Closed** 2019-12-29 18:49 UTC
