### ISSUE TITLE
Mail personal signature

### ISSUE THREAD

**Issue by MauritsCornelis** [deltachat/deltachat-android#265] opened 2018-03-06 21:56 UTC
Some mails accounts (specially non personals accounts) send (often automatically) an embedded signature with personal information and some legal issues. This is annoying, making it dificult to read the chat.

Would it be possible to automatically delete this signature?

**Comment by r10s** [comment] 2018-03-06 22:06
typical footnotes starting with `-- ` are already truncated, maybe this can be optimized, but in general, it works, see https://github.com/deltachat/deltachat-core/blob/master/src/mrsimplify.c#L114

can you please give more information about how the signature look like? or a PR is also always welcome :)

**Comment by MauritsCornelis** [comment] 2018-03-07 17:04
Ok. Thanks for your answer. I think it is not possible to solve if there is
not special character at the start of the signatura/foodprint ¯\_(ツ)_/¯.

El 6 mar. 2018 11:06 p. m., "Björn Petersen" <notifications@github.com>
escribió:

typical footnotes starting with -- are already truncated, maybe this can be
optimized, but in general, it works, see https://github.com/deltachat/
deltachat-core/blob/master/src/mrsimplify.c#L114

can you please give more information about how the signature look like? or
a PR is also always welcome :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/deltachat/deltachat-android/issues/265#issuecomment-370946007>,
or mute the thread

**Comment by testbird** [comment] 2018-03-07 20:32
It might be possible to collapse all lines at the end of a message that are identical to the last received message.

**Comment by MauritsCornelis** [comment] 2018-03-07 20:33
I think that's a great idea!

**Comment by r10s** [comment] 2018-03-09 17:29
> It might be possible to collapse all lines at the end of a message that are identical to the last received message.

Yes I also like the idea. However, it will tend to cut things that are no footnote, eg. "Best regards - Björn" may be also printed below each message as "Sent with my iPhone" - both without any special separator ("thanks" to Apple-Samsung-Google-... )

**Comment by testbird** [comment] 2018-03-10 08:46
The #118 fix seem to compare the received message to the last message sent. Here the received message would need to be compared to the last received message, right?

A possiblity to avoid cutting of real greetings could be to let deltachat insert something similar to the dashes
 before the redundant part starts.
[---]
Kind regards,
testbird

---
 And clicking on the insertion could allow to allway hide following string behind some dots `...` in this message and in following messages.

**Comment by MauritsCornelis** [comment] 2018-03-10 08:57
Well, I think a 'best regards' could make sense after every email, but is a
nonsense in a messaging app.

**Comment by testbird** [comment] 2018-03-10 09:36
Yes, you are probably right. Messenges seem to follow and foster some (un)kind [shaving](https://en.wikipedia.org/wiki/Razor_(philosophy)) down of communication anyway, may even confirm what some opponents may have said hundred of years ago ;-)

So cutting repetitions by default may be ok here, because in mobile messengers they are most probably only advertisements anyway.

**Comment by r10s** [comment] 2018-03-10 14:25
> The #118 fix seem to compare the received message to the last message sent. Here the received message would need to be compared to the last received message, right?

IIUC, both approaches would compare against the last received message.

> A possiblity to avoid cutting of real greetings could be to let deltachat insert something similar to the dashes before the redundant part starts.
> [---]
> Kind regards,
> testbird

There is already a standard marker before real footers, a line with exactly the following three characters: `-- ` (minus, minus, space)
The problem is that there are MUAs out there, that do not follow this convention. Probavly some commercial MUA creators do not want their Ads to be cutted out or drawn in another color.

**Comment by testbird** [comment] 2018-03-10 16:35
I also see regular MUAs adding lines before the signature by repeating
`=5F=5F=5F` (CAS netWorks) and other email with a signature without any separator (no X-Mailer or other header). So these kind of repetitive things (and greetings) might only be removed by diffing.

> IIUC, both approaches would compare against the last received message.

Not sure if we think of the same. 

 1) A sends a message a1 to B that was littered with a not properly separated advertisement footer.
 2) B answers with a message b1. Here, A may see his own message a1 quoted, and detect it by comparing a1 with b1 (compare new message with last message sent).
 But maybe detecting quotes should better be done by filtering lines that start with `> `, to avoid filtering deliberate repetitions with diff. Maybe that's already what you're doing.)
3) A replies again with a2. Now, B can detect the repeated advertisement through ad diff that identifies the identical endings of a1 and a2 (compare new message with last message received).



> There is already a standard marker before real footers, a line with exactly the following three characters: -- (minus, minus, space)

OK, then it could make sense to use the standard signature separator in a square bracket insertion like `[-- ]`, to indicate that the following repetitive text may be collapsed from messages by clicking on the `[-- ]` insertion. (If it is desired to make the collapsing optional, instead of automatic.)

**Comment by testbird** [comment] 2018-04-07 17:40
Isn't this solved by https://github.com/deltachat/deltachat-android/issues/112 ?

**Comment by r10s** [comment] 2018-10-13 23:19
i think this is strongly related to #118 

closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat

**Closed by r10s** 2018-10-13 23:19 UTC
Labels: duplicate, feature proposal
