### ISSUE TITLE
Attachments do not open

### ISSUE THREAD

**Issue by agutierrez25249** [deltachat/deltachat-android#1119] opened 2019-11-17 17:52 UTC
- Android version: 9
- Device: xiaomi mi A1 
- Delta Chat version: 0.950
- Expected behavior: Open attachments directly in Delta
- Actual behavior: 
When you click on an attachment, a sign appears. 

Media-type: text / html 
Media-type: application / zip 

Depending on the attachment that opens
- Steps to reproduce the problem:
- Screenshots:
![deltachat-2019-11-17-124903](https://user-images.githubusercontent.com/52469394/69011482-b18f5280-0938-11ea-8d36-4c78ae098965.jpg)

- Logs:

Saying that version 0.510 doesn't give me this problem ..

**Comment by agutierrez25249** [comment] 2019-11-24 23:08
The problem continues in this new version v0. 960 I can't open the documents directly from delta.chat

**Comment by hpk42** [comment] 2019-11-25 09:54
thanks for reporting again -- i guess @cyberta or @r10s can look into this
maybe this week.

**Comment by agutierrez25249** [comment] 2019-11-25 18:04
Same problem in a
Huawei Y9 2019,
Emui 9.1.0
Android 9
DeltaChat v0.9.50

I have tried several mobiles, and I have not seen this problem in any.

**Comment by agutierrez25249** [comment] 2019-12-05 17:03
The problem continues in this version. v0.970.0

**Comment by agutierrez25249** [comment] 2019-12-08 02:36
The problem continues in this version. v0.971.0

device=Xiaomi Redmi 8 (olive)
android=9 (V11.0.1.0.PCNMIXM, ZQL2115-olive-build-20191127144358)
sdk=28
memory=10M (30.25% free, 256M max)
memoryClass=192
host=c4-miui-ota-bd103.bj
applicationId=chat.delta
app=Delta Chat 0.971.0-gplay
installer=com.google.android.packageinstaller
ignoreBatteryOptimizations=true

**Comment by r10s** [comment] 2019-12-08 11:28
the issue is targeted in the recent master, see https://github.com/deltachat/deltachat-core-rust/pull/978. it happend only for html-attachments that were treated as an alternative text format.

so, the issue should be fixed in android with the next update :)

**Closed by r10s** 2019-12-08 11:28 UTC
