### ISSUE TITLE
Notification seems to pop up twice when a message is received

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-android#3168] opened 2024-07-13 17:25 UTC
- Android version: 14
- Device:
- Delta Chat version: 1.46.5, and other versions from at least one year ago
- Expected behavior: Only one notification is received per message
- Actual behavior: Two notifications seem to be popping up
- Steps to reproduce the problem:
  1. Install Delta Chat
  2. [Create a new Android profile](https://www.howtogeek.com/333484/how-to-set-up-multiple-user-profiles-on-android/)
  3. Enable that profile to receive notifications from the original profile
  4. Switch to that new profile
  5. Get a message on Delta Chat
  6. When you pull down the shade, you'll see that there are two notifications from Delta Chat
- Screenshots:
- Logs:

On some phones you don't have make new profiles, there the phone would just ~~vibrate~~ make a sound two times in a row.

**Comment by adbenitez** [comment] 2024-07-30 13:27
> 2\. Create a new Android profile

I don't understand the context so you are using some kind of "dual"/"parallel"/"clone"/"duplicate" spaces? to duplicate an app, feature that is often used to create a new account in apps that don't support multi-account?

**Comment by adbenitez** [comment] 2024-07-30 13:28
this looks more like a misconfiguration of the "android profiles" usage than something that can be fixed in the delta chat app

**Comment by WofWca** [comment] 2024-07-30 13:36
This is what I'm referring to:
https://www.howtogeek.com/333484/how-to-set-up-multiple-user-profiles-on-android/

No, there is just one instance of Delta Chat on just one profile. The two notifications are received from just one profile profile.

**Comment by adbenitez** [comment] 2024-07-30 13:38
thanks, but Delta Chat is not even aware of these profiles so whatever happens should be a system configuration problem nor an app problem, if I got it correctly

**Comment by adbenitez** [comment] 2024-07-30 13:40
did you test that notifications are not double with apps like Element, Conversations, Jami etc?

also could you share a picture of such double notifications? you mean that the notification for the same message is duplicated or that there are two notifications bubbles but for different messages instead of being collapsed into 1 bubble?

**Comment by WofWca** [comment] 2024-07-30 13:50
I use many different applications, including messengers such as WhatsApp, Telegram, but I don't remember seeing this happen to any other app than Delta Chat.

I mean that if I receive just one message, this shows up as two notifications on another profile.
It looks like just one notification on the original profile though, where Delta Chat is installed.

![image](https://github.com/user-attachments/assets/2c5eafdd-146c-4ac4-a768-61be5a986ef0)

**Comment by WofWca** [comment] 2024-07-30 14:55
Also I confirmed the notification sound being played twice on another phone of mine.

**Comment by adbenitez** [comment] 2024-07-31 10:18
in the screenshot it says "notification from delta chat" that is not how a real delta chat notification is supposed to look like so it seems to be from the push notifications from google?

**Comment by WofWca** [comment] 2024-07-31 10:21
When using a different profile, it shows only the name for notifications that are for a different profile. Also I do not have Google Play Services installed on the profile that I use Delta Chat on.

**Comment by WofWca** [comment] 2024-07-31 10:24
> Also I confirmed the notification sound being played twice on another phone of mine.

That is on the same profile, no other profiles involved at all.

**Comment by adbenitez** [comment] 2024-07-31 10:25
what version of android does that other phone has?

**Comment by WofWca** [comment] 2024-07-31 10:26
> what version of android does that other phone has?

Pretty old, 8.1.0

**Comment by adbenitez** [comment] 2024-07-31 10:29
that doesn't happen to me in the devices I have tested

try this:

1. go to your delta chat (the old one with android 8 and without user profiles)
2. create a new nine account using the instant onboarding screen
3. from another account scan QR/invite link of the just-created account
4. send a message from your older account to your new created testing account
5. does it receive double notification in the newly created nine account?

**Comment by WofWca** [comment] 2024-07-31 10:34
Just did that. Yes, the notification sound is still played twice.

**Comment by adbenitez** [comment] 2024-07-31 10:43
sound but not double notification then?

**Comment by WofWca** [comment] 2024-07-31 10:46
Perhaps I haven't made this clear. On the original profile the notifications always look fine, i.e. only a single one is displayed.

**Comment by adbenitez** [comment] 2024-07-31 10:48
ok so the double notification seems to be related to the Android profile feature in particular

**Comment by WofWca** [comment] 2024-07-31 10:49
IDK, given that the sound is played twice on the old phone, I suspect this is the same issue and is not just about profiles.

**Comment by adbenitez** [comment] 2024-07-31 10:50
well you just said there is no double notifications without profiles, so it is a fact this is only happening for android profiles

**Comment by WofWca** [comment] 2024-07-31 10:51
I said that visually there is just one notification, but the notification sound is still played twice.

**Comment by r10s** [comment] 2024-07-31 12:20
so, to get it right, it is about _two_ android-profiles, where _only one_ has Delta Chat with just a single delta-profile.

i just tried and android14 in the emulator, installing Delta Chat on the "Owner" android-account, create another android-profiles, things and notification works as expected (the other account does not see Delta nor gets notifications)

you then wrote:

> iii. Enable that profile to receive notifications from the original profile

how did you do that? i did not find an option in the stock android for that, there is (a bit outdated) https://support.google.com/work/android/answer/7029165?sjid=13897655756563575851-EU , but i could not find that option for that.

if you elaborate on that and send a screenshot, we can try again to reproduce.

in general, however, it may be on purpose somehow to have two notifications (one for the original profile, one where you request a copy) - it does not sound too strange to me.

finally, we'll change the [target sdk to andoid14 (api34) soon](https://github.com/deltachat/deltachat-android/issues/3151), maybe this will also change things

**Comment by WofWca** [comment] 2024-07-31 12:36
> how did you do that?

1. Pull down the shade
2. Tap on user icon (besides "settings")
3. Tap " manage users"
4. Enable "Send notifications to current user"

![IMG_20240731_163012.jpg](https://github.com/user-attachments/assets/e1f5671a-9d47-4641-8cd9-adfc36e4f4aa)

The duplicated notification is then visible on the other profile, the one that doesn't have Delta Chat installed.
On the original profile everything looks fine.

**Comment by r10s** [comment] 2024-07-31 12:45
hm, i do not see that option in stock android14, this is how it looks to me:

<img width="371" alt="Screenshot 2024-07-31 at 14 42 56" src="https://github.com/user-attachments/assets/4a013e92-5638-45d5-b4a9-9a51e62b633d">

maybe this is sth. that is added by some android flavour, maybe in a suboptimal way :)

however, tbh, as the notification may be modified ("Only the user's name, the app's name, and the time received will be shown.") i am not surprise this ends up in a second notification.

**Comment by r10s** [comment] 2024-07-31 13:20
wondering where `SEND_CENSORED_NOTIFICATIONS_TO_CURRENT_USER` is actually read, that could make things clearer.

 but again, the variable name again looks to me as if it is natural that the notification will be doubled. i mean the option will send a _censored_ copy that you can see when you're not in the correct android-profile - but if you switch to the correct android-profile one probably expect the correct notification to be present.

**Comment by WofWca** [comment] 2024-07-31 13:24
I don't think that's how it works. If this setting is toggled off, you receive no notifications from other profiles at all, plus it's only the case for Delta Chat that there are two notifications. Other apps show only one notification.

**Comment by r10s** [comment] 2024-07-31 13:41
> Other apps show only one notification.

well, there are a lot of methods how notifications can be fired, grouping and whatnot. this can make a difference, without the one being more correct than the other in case of issues like that one.

Delta Chat relies very much on the system, for grouping, sounds and whatnot.

**Comment by adbenitez** [comment] 2024-08-05 15:04
> Looks like you're right.
> 
> [GrapheneOS/platform_packages_apps_Settings@1195220](https://github.com/GrapheneOS/platform_packages_apps_Settings/commit/11952204569e3d1d1386fb3b5675d6d2553f4667)
> 
> Original Android doesn't have this https://cs.android.com/android/platform/superproject/main/+/main:packages/apps/Settings/res/xml/user_settings.xml

so this is a GrapheneOS specific non-standard feature and it seems somewhat new, probably it has issues with notification grouping feature that is used by DC, there is nothing to fix on our side,

 closing this issue as this is out of scope of what we can care for

**Closed by adbenitez** 2024-08-05 15:04 UTC
Labels: bug, needs-feedback
