### ISSUE TITLE
Show old emails on first run (feature request?)

### ISSUE THREAD

**Issue by vit1-irk** [deltachat/deltachat-android#338] opened 2018-06-23 02:54 UTC
The whole idea of Delta Chat is just awesome, but it seems unusable until it shows already existing correspondence inside your mailbox.

For example, I have about 500 letters (maybe more) from different people in mailbox already. When first opening Delta Chat (after account setup) I see **an empty window** and few contacts to start new conversation.

If it could display old emails to read them, it would be easier for beginners to start using the app immediately after installing.

**Comment by testbird** [comment] 2018-06-23 07:40
Well put. Didn't think of it that way. 

The "contact requests" https://github.com/deltachat/deltachat-core/issues/48 i.e. unapproved emails (ignored for chat) show further arriving emails, anyway. Not showing the existing ones hides the function that it is good for from new users. (So, it is not only the name that creates the confusion for new users.)

Seems that the downloading of message history behavior has been changed to only show newly received messages https://github.com/deltachat/deltachat-android/issues/21. It got reported before https://github.com/deltachat/deltachat-android/issues/123, https://github.com/deltachat/deltachat-android/issues/210, the last time the devs even had a hack for older versions of deltachat, but was deferred.

Cant't deltachat start with "last seen uid == 0" and at least download the INBOX  anymore, for now, if an account gets newly configured (is not imported)?
Same with the correspondingly required "downloading of deletes https://github.com/deltachat/deltachat-core/issues/195

(It might not be very realistic to assume deltachat is used with empty newly created accounts, without any preexisting email client in use.)

**Comment by vit1-irk** [comment] 2018-06-23 07:57
I think the chat should ask whether import INBOX or not as suggested here: https://github.com/deltachat/deltachat-android/issues/21#issue-205292094

Past year/month/1 week/ALL

And there should be an option to import Sent as well, to remember the previous conversations.

**Comment by testbird** [comment] 2018-06-23 08:03
Ideally, in the long run yes. 
My limitation to INBOX state is due to thee current scope of getting the app into a basic generally working state.

**Comment by testbird** [comment] 2018-06-23 08:05
May something like this work to ensure it stays manageble for now: "last seen uid == current uid - 20"

**Comment by sketet** [comment] 2018-06-23 18:34
Hello, I installed DC, then I removed and now I installed again.
In my first install I saw the old emails - that I moved in Chats folder - and I added some conversations using DC.
Now I've reinstalled DC but I can't see the old emails, old DC conversations... nothing. Why?
What should I do to show all the emails in the Chats folder?

**Comment by r10s** [comment] 2018-06-23 21:14
@sketet Delta Chat currently does not show old emails. Only new ones. This may change in the future, however, for now, this is not the main focus.

**Comment by sketet** [comment] 2018-06-24 07:32
@r10s like I said, when I installed DC for the first time (last october/november, I don't remember exactly), DC showed the old emails.
I moved the emails (that I considered as chat) into the Chats folder.

Now I reinstall DC but there are not the old emails and the conversations that I made with DC.

So, in past DC had this feature!

**Comment by testbird** [comment] 2018-06-24 10:22
Unfortunately it only works sometimes: https://github.com/deltachat/deltachat-core/issues/156

**Comment by kollokollo** [comment] 2018-07-22 08:15
Apparently the import of oldmessages works, if the messages are in the inbox folder. So I moved all messages from chats folder to inbox (using a thunderbird client on the same account). Then delta chat imported all old messages but left them in inbox. So I moved the messages back to chat folder with thunderbird. Done.

**Comment by r10s** [comment] 2018-07-24 14:17
i think this is an duplicate of #123

**Closed by r10s** 2018-07-24 14:17 UTC
Labels: duplicate
