### ISSUE TITLE
No more emoji's on Android 4.1.2

### ISSUE THREAD

**Issue by icke68746** [deltachat/deltachat-android#1493] opened 2020-07-21 16:21 UTC
- Operating System (Linux/Mac/Windows/iOS/Android):Android 4.1.2
- Delta Chat Version:1.10.4; 1.10.5 (nightly 2020-07-21)
- Expected behavior:Emojis are displayed
- Actual behavior:Emojis are not displayed
- Steps to reproduce the problem:Enter a chat and click the emoji  #icon.
![Screenshot_2020-07-21-18-12-54](https://user-images.githubusercontent.com/36864290/88080056-d51d3380-cb7e-11ea-9205-0deb1ec726eb.png)

- Screenshots:

Regards Mike

**Comment by gerryfrancis** [comment] 2020-07-21 17:38
@icke68746 Thank you for your report. I have deleted the German part from the issue name, because our Github repositories are moderated in English only.

**Comment by gerryfrancis** [comment] 2020-07-21 18:00
Maybe caused by the switch to the new MediaKeyboard. Do we know if it is supported in Android 4.1.2?

**Comment by r10s** [comment] 2020-07-21 18:23
> Do we know if it is supported in Android 4.1.2?

not sure, iirc @cyBerta tried it out, however, not sure on which android 4 version.

**Comment by RubenDavidPerezJimenez** [comment] 2020-07-21 23:21
I have a contact that have see that issue in Android 4.4.2 in a Huawei Y360


En 21 de julio de 2020 2:24:09 p. m. bjoern <notifications@github.com> 
escribió:

**Comment by cyBerta** [comment] 2020-07-22 10:05
@icke68746 are you able to see icons if you receive them as messages? My guess is that .webp format is not supported on some Android 4.X devices. With the MediaKeyboard we switched from png to webp (Signal's codebase).

**Comment by gerryfrancis** [comment] 2020-07-22 10:41
From https://developer.android.com/studio/write/convert-webp :

> Lossy WebP images are supported in Android 4.0 (API level 14) and higher, and lossless and transparent WebP images are supported in Android 4.3 (API level 18) and higher.

**Comment by RubenDavidPerezJimenez** [comment] 2020-07-22 11:22
But I have see in Android 4.4.2 in my contact's phone



En 22 de julio de 2020 6:42:18 a. m. gerryfrancis

**Comment by gerryfrancis** [comment] 2020-07-22 11:37
@RubenDavidPerezJimenez Which version of Delta Chat do you use?

**Comment by RubenDavidPerezJimenez** [comment] 2020-07-22 16:32
1.10.5


En 22 de julio de 2020 7:37:49 a. m. gerryfrancis

**Comment by icke68746** [comment] 2020-07-23 08:28
@cyBerta Hi, no I there are also no receiving emojis displayed. Just a blank message, or just the text.

Original: Hi, nein ich es werden auch keine empfangenen Emojis angezeigt. Nur eine leere Nachricht, oder nur der Text.

**Comment by gerryfrancis** [comment] 2020-07-23 09:00
@icke68746 The problem has been identified and will be fixed in a future version.

**Comment by icke68746** [comment] 2020-07-23 09:31
Great, thanks!

**Closed** 2020-07-23 22:14 UTC
Labels: android4, bug
