### ISSUE TITLE
Feature request: automatically delete delivered messages from the mail server

### ISSUE THREAD

**Issue by Px3XjG6P** [deltachat/deltachat-android#889] opened 2019-05-05 09:33 UTC
When I receive a message in the app, the message is needlessly kept on the mail server occupying space. It would be nice if these messages are deleted from the mail server immediately after succesful arrival in the app.

- Platform (android/blackberry/anbox): android
- Device: sm-j730f
- Delta Chat Version: 0.301.1
- Expected behavior: messages not kept on the mail server
- Actual behavior: messages kept on the mail server
- Steps to reproduce the problem: current normal behaviour
- Screenshots: /
- Logs: /

**Comment by webratte** [comment] 2019-05-05 09:42
There is currently work in progress.
I also think it's a very important feature.

https://github.com/deltachat/deltachat-core/pull/595

**Comment by r10s** [comment] 2019-05-05 10:08
@Px3XjG6P well, how "needlessly" this is  depends on the concrete setup, eg. for multi-client, webclients etc. this makes some sense :)

however, as @webratte mentioned, this seems to be a duplicate of eg. https://github.com/deltachat/deltachat-core/issues/164

**Closed by r10s** 2019-05-05 10:08 UTC

**Comment by Px3XjG6P** [comment] 2019-05-05 10:30
Thank you! Indeed, the existing tickets overlap with what I suggested. Great!

**Comment by webratte** [comment] 2019-05-05 11:28
@r10s I absolutely agree.

It's not useless, but also absolutely important to keep the mailbox clean by deleting older messeges ;-)
