### ISSUE TITLE
Login screen endless loop with free GMX account due to folder limitation / Loginscreen Endlosschleife bei kostenlosem GMX-Konto wegen Ordnerbegrenzung

### ISSUE THREAD

**Issue by icke68746** [deltachat/deltachat-android#879] opened 2019-04-30 16:51 UTC
- Platform (Android 4.1.2):
- Device:Neptune Pine
- Delta Chat Version: 0.200 (probably all)
- Expected behavior: Login successfully completed
- Actual behavior: Returns to the login screen
- Steps to reproduce the problem: Create 20 folders with a free GMX account and try  to log in with DeltaChat
- Screenshots: not necessary because no error message appears
- Logs: 2019.04.26-DeltaChat-NeptunePine.log

Hello,
DeltaChat had a login loop after installation (v0.200). After entering the email address and password, I came back to the login screen. This happened over and over again. After evaluating the log files together with Der Mor, we found that my free GMX account had reached the maximum number of folders. Delta Chat could not create a new folder. After deleting some folders the login with DeltaChat worked without any problems. An error message is missing.
Great program, keep it up!

Greetings Mike

Translated with www.DeepL.com/Translator
--Original--
- Gerät: Neptune Pine (Android 4.1.2)
[2019.04.26-DeltaChat-NeptunePine.log](https://github.com/deltachat/deltachat-android/files/3132239/2019.04.26-DeltaChat-NeptunePine.log)

- Delta Chat Version: 0.200 (wahrscheinlich alle)
- Erwartetes Verhalten: Anmeldung erfolgreich durchgeführt
- Tatsächliches Verhalten: kehrt zurück zum Anmeldebildschirm
- Schritte, um das Problem zu reproduzieren: Mit einem freien GMX-Konto 20 Ordner anlegen und versuchen sich mit DeltaChat einzuloggen
- Screenshots: nicht nötig weil keine Fehlermeldung kommt
- Protokolle: 2019.04.26-DeltaChat-NeptunePine.log

Hallo,
DeltaChat hatte nach der Installation (v0.200) eine Anmeldeschleife. Nach der Eingabe der E-Mail-Adresse und des Passwortes, kam ich wieder zum Anmeldebildschirm zurück. Dies passierte immer wieder. Nach dem Auswerten der Logdateien zusammen mit Der Mor, haben wir festgestellt, dass bei meinem kostenlosen GMX-Konto die max. Anzahl der Ordner erreicht war. Delta Chat konnte keinen neuen Ordner anlegen. Nach dem löschen einiger Ordner klappte die Anmeldung mit DeltaChat problemlos. Es fehlt eine Fehlermeldung.
Tolles Programm, weiter so!

Gruß Mike

**Comment by r10s** [comment] 2019-10-28 14:28
should be re-checked with version 0.930.2 or newer

**Comment by r10s** [comment] 2019-10-28 14:36
the issue is confirmed by #1089

**Comment by webratte** [comment] 2019-10-28 15:06
Now as I know what's the reason I could test it on my test phone.

I have created 20 folders in my gmx account.
With V.0.930.2 now it works. 
But of course all messages stay in the inbox.

It's not really nice and more a workaround.
A user who create 20 folders like it to keep the inbox clean and tidy I believe.

**Comment by r10s** [comment] 2019-10-28 15:23
@webratte thanks for testing. so, i think we can close this issue, at least the loop/crash is gone.

i think if the user wants to use gmx, he has to sacrifice one of his 20 folders and rename it to DeltaChat - then things should work, i've added a hint on that to the new provider-db at https://github.com/deltachat/provider-db/pull/35

**Closed by r10s** 2019-10-28 15:23 UTC
Labels: bug, needs-retry

**Comment by webratte** [comment] 2019-10-28 15:26
OK, great.
I have contacted my friend. And yes, it seems also the problem there.

**Comment by r10s** [comment] 2019-10-28 18:37
@webratte thanks for verification!
