### ISSUE TITLE
no notificacion if DC is closed, only notificacion if DC is opened 

### ISSUE THREAD

**Issue by gitgerardo** [deltachat/deltachat-android#1173] opened 2019-12-18 09:20 UTC
- Android version:9 (Lineage16)
- Device:Oneplus 6
- Delta Chat version:1.0.0
- Expected behavior:notificacion
- Actual behavior:no notificacion if DC isn't opened

Just installed version 1.0.0 on my oneplus 6 , OS is Lineage 16 .
I don't get a notificacion  if DC isn't opened .
This worked up to version 0.501.1 on my device.

logfile:

device=OnePlus ONEPLUS A6003 (OnePlus6)
android=9 (eng.root.20191210.053715, lineage_enchilada-userdebug 9 PQ3A.190801.002 eng.root.20191210.053715 dev-keys)
sdk=28
memory=8M (22.81% free, 512M max)
memoryClass=256
host=21f98c88112d
applicationId=chat.delta
app=Delta Chat 1.0.0-gplay
installer=com.aurora.store
ignoreBatteryOptimizations=true

sentbox_watch=1
mvbox_watch=1
is_configured=1
public_key_count=14
mvbox_move=0
private_key_count=3
bcc_self=1
blobdir=/data/user/0/chat.delta/files/messenger.db-blobs
deltachat_core_version=v1.0.0-beta.19
inbox_watch=1
number_of_chats=256
number_of_contacts=2060
sqlite_version=3.29.0
configured_sentbox_folder=Gesendet
fingerprint=***
selfavatar=<unset>
folders_configured=3
entered_account_settings=*** imap:unset:***:unset:0:cert_automatic smtp:unset:0:unset:0:cert_automatic 0
configured_mvbox_folder=DeltaChat
display_name= ***

cert_automatic AUTH_NORMAL 0x4IMAP_SSL 0x200SMTP_SSL 0x20000
messages_in_contact_requests=35
mdns_enabled=1
sqlite_thread_safe=1
database_dir=/data/user/0/chat.delta/files/messenger.db
level=awesome
arch=64
e2ee_enabled=1
database_version=61
number_of_chat_messages=11516

--------- beginning of system
12-18 09:44:21.855 12199 12199 D TextClassifierService: No configured system TextClassifierService
12-18 09:44:21.856 12199 12199 D TextClassifierService: No configured system TextClassifierService
12-18 09:44:21.858 12199 20297 D TextClassifierService: No configured system TextClassifierService
12-18 09:44:21.883 12199 20297 D androidtc: Loading ModelFile { path=/etc/textclassifier/textclassifier.en.model name=textclassifier.en.model version=6 locales=en }
12-18 09:44:21.961 12199 20297 D TextClassifierService: No configured system TextClassifierService
--------- beginning of main
12-18 10:23:36.197 24237 24237 I DeltaChat: -------------------- Screen on --------------------
12-18 10:23:59.663 24237 24262 I DeltaChat: ThreadId(8) src/job.rs:571: SMTP-idle ended.
12-18 10:23:59.668 24237 24262 I DeltaChat: ThreadId(8) src/job.rs:529: SMTP-jobs started...
12-18 10:23:59.671 24237 24262 I DeltaChat: ThreadId(8) src/job.rs:531: SMTP-jobs ended.
12-18 10:23:59.672 24237 24262 I DeltaChat: ThreadId(8) src/job.rs:542: SMTP-idle started...
12-18 10:24:56.398 24237 24237 W PassphraseRequiredActionBarActivity: onDestroy()
12-18 10:24:56.417 24237 24237 W PassphraseRequiredActionBarActivity: onResume()
12-18 10:24:56.438 24237 24237 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-18 10:24:56.455 24237 24237 I chatty  : uid=10188(chat.delta) identical 6 lines
12-18 10:24:56.458 24237 24237 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-18 10:24:59.785 24237 24237 W PassphraseRequiredActionBarActivity: onPause()
12-18 10:24:59.789 24237 24237 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f9b690b
12-18 10:24:59.790 24237 24237 W PassphraseRequiredActionBarActivity: onCreate(null)
12-18 10:24:59.799 24237 24237 W PassphraseRequiredActionBarActivity: onResume()
12-18 10:25:00.084 24237 25073 D OpenGLRenderer: endAllActiveAnimators on 0x6f46af6500 (MenuPopupWindow$MenuDropDownListView) with handle 0x6f5b736380
12-18 10:25:12.506 24237 24237 W PassphraseRequiredActionBarActivity: onPause()
12-18 10:25:12.522 24237 24237 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b87a101

**Comment by r10s** [comment] 2019-12-18 09:59
@gitgerardo thanks for filing the issue. from the symptoms, this seems to be a duplicate of #1168, are you receiving messages at least every 15 minutes or so?

please also note that oneplus is known to produce issues, https://dontkillmyapp.com/oneplus

**Comment by gitgerardo** [comment] 2019-12-18 10:08
Lineage isn't the same as oxygen , the  pre-installed firmware on Oneplus devices.
Interesting is that the same problem 
(no notificacion, also with DC 0.501.1) happened also on my older oneplus one  after updating lineage.   Something changed there in September or October. So maybe it's an OS - Problem.

 Also maybe  that updating Firmware could help ...?

**Comment by cytrinox** [comment] 2019-12-18 21:35
+1 from me, having the same issue (since beta from summer '19 on google playstore).
Just updated to 1.0 from playstore and issue still exists.
Just wonder: I've two "New messages" options under notification settings and one "Receive messages in background". All three are activated but why is there a duplicated entry?

**Comment by r10s** [comment] 2019-12-18 23:35
> Just wonder: I've two "New messages" options under notification settings and one "Receive messages in background". All three are activated but why is there a duplicated entry?

@cytrinox i am confused. afaik, there is no "Receive messages in background" option at all. can you add a screenshot?

**Comment by cytrinox** [comment] 2019-12-19 08:05
Android 8.1.0
BQ Aquaris X Pro

![grafik](https://user-images.githubusercontent.com/509535/71155663-84d3a100-223e-11ea-844e-274180f2f9dc.png)

**Comment by gitgerardo** [comment] 2019-12-19 11:23
A question :
if I have have three email clients installed on my device,  using the same mail account. Isn't an incoming Mail fetch up by only one of them? And could that be the explanation to the problem that I don't get notifications in the other ones?
Is this handled differently by different Android devices?

**Comment by r10s** [comment] 2019-12-22 15:03
> if I have have three email clients installed on my device, using the same mail account. Isn't an incoming Mail fetched up by only one of them? And could that be the explanation to the problem that I don't get notifications in the other ones?

if another email client gets the message before Delta Chat and this other client marks the message as being "seen" (may happen without direct user interaction), this message won't be notified by Delta Chat (but it will be added if it is a "Chat" message)

anyway, i close this issue as the gist is already handled by https://github.com/deltachat/deltachat-android/issues/1168

**Closed by r10s** 2019-12-22 15:03 UTC

**Comment by cytrinox** [comment] 2019-12-22 18:01
After 1.0.3 update, still the same issue here.

**Comment by r10s** [comment] 2019-12-22 22:29
there was no change in this area, so this is not unexpected. however, we track these background-notification-issues now bundled in in #1168

**Comment by EchedeyLR** [comment] 2020-04-21 07:34
> this message won't be notified by Delta Chat (but it will be added if it is a "Chat" message)
No XD. It is notified when the app is opened with sound and all.
