### ISSUE TITLE
Missing push notifications for Android 4.2

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#770] opened 2019-03-17 11:12 UTC
- Platform (android/blackberry/anbox): Android 4.2
- Device: Samsung Mini S3
- Delta Chat Version: 0.200.0 (Gplay version)
- Expected behavior: Push notifications are shown on incoming messages
- Actual behavior: No Push notifications
- Steps to reproduce the problem: Receive a message and see there is no push notification

**Comment by webratte** [comment] 2019-03-17 11:45
I also register long delays (up to 10 min.) on my phone 
(Huawei nova- Android 7.0
Delta Chat Version: 0.200.0 (Gplay version)

This behavior (IIRC) was not on the previous version

**Comment by adbenitez** [comment] 2019-03-17 15:03
Also I have detected some issues with notification, ex. some times when I am in a chat, there are no notifications until I go back to the chat list and it comes out I have lots of new messages in several chats.
I will report other buggy behaviors when I get Internet access

**Comment by testbird** [comment] 2019-03-20 17:42
Confirming, not sure if the v0.200 update was already there.

**Comment by cyBerta** [comment] 2019-03-25 00:26
> Also I have detected some issues with notification, ex. some times when I am in a chat, there are no notifications until I go back to the chat list and it comes out I have lots of new messages in several chats. I will report other buggy behaviors when I get Internet access

@adbenitez This is a feature, not a bug. Remember https://github.com/deltachat/deltachat-android/issues/451?

**Comment by adbenitez** [comment] 2019-03-25 01:14
Hi @cyBerta, I think this behavior solves the problem of annoying notifications while in a chat, but the real bug is: I don't get the silent dc icon on the top bar so I know I have a new message, and also when I go back to the chats list, a annoying notification is still shown, blocking the view of the first chat which is one with new messages.

**Comment by webratte** [comment] 2019-03-25 05:14
But absolutely no notification is a bug, not a feature.
This was my initial report 😉

**Comment by Hiboycubano** [comment] 2019-04-04 18:08
Also related with issue #782 the crashing behavior on android 4.2.2 was reproduced on delta chat 0.200 (f-droid) :
-just receive a message

And the app will continuously crash until the green number of unread messages are over in every chat... off course without notification

**Comment by r10s** [comment] 2019-05-06 19:16
i think the initial issue is about notifications missing at all, not about how they're shown or so.
is this still an issue? i cannot complain about messages not reaching me on my test devices.

**Comment by r10s** [comment] 2019-06-20 22:04
closing this for now. there is no actionable item and the reports are a bit outdated.

**Closed by r10s** 2019-06-20 22:04 UTC
Labels: android4
