### ISSUE TITLE
private keys can't read 

### ISSUE THREAD

**Issue by antant999** [deltachat/deltachat-android#2484] opened 2023-03-02 01:43 UTC
- Android version: 13
- Device:vivo x90 pro +
- Delta Chat version:1.34.13
- Expected behavior: import the private keys in download success 
- Actual behavior:imex failed
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by gerryfrancis** [comment] 2023-03-08 10:47
@antant999 Thank you for your report. Without the mentioning of a specific error message, I am afraid that we can just speculate what might be the cause of your issue. Maybe you will find support to your issue by following this section of the Delta Chat FAQ's: https://delta.chat/en/help#i-cant-import-my-existing-pgp-key-into-delta-chat (Spoiler: Some keys might not work with Delta Chat, and private keys must not contain a passphrase to be imported successfully.)

I am closing here now. Should you still experience an issue which you consider to be a bug in Delta Chat, please come back here and add detailed information about it. You may also upload an anonymized(!) log file to accelerate the troubleshooting process. Thank you.

**Closed by gerryfrancis** 2023-03-08 10:47 UTC
