### ISSUE TITLE
No message when Delta.Chat is in background

### ISSUE THREAD

**Issue by paulschieres** [deltachat/deltachat-android#2888] opened 2023-11-27 21:05 UTC
- Android version: 14
- Device: Galaxy S22
- Delta Chat version: 1.40.0
- Expected behavior: Message received
- Actual behavior: Message is received only when Delta.Chat is opened
- Steps to reproduce the problem: Send a message from other user
- Screenshots:
- Logs:

**Comment by adbenitez** [comment] 2023-12-09 20:04
there is a "reliable background connection" option in the settings that enables a permanent notification to avoid the app being killed, you can enable that as well

since this is not a bug but a matter of phone configuration I am closing this bug report, thanks a lot for taking care!

**Closed by adbenitez** 2023-12-09 20:04 UTC
Labels: bug
