### ISSUE TITLE
Accessibility issues for visually impaired users

### ISSUE THREAD

**Issue by bmivzkrp** [deltachat/deltachat-android#2344] opened 2022-07-14 15:23 UTC
Android version: 6.0
Device: Impression ImSmart C551
Delta Chat version: 1.30.3 (F-Droid)
- Steps to reproduce the problem:
- 1. Install a screen reader such as TalkBack (Android Accessibility Suite) or Jieshuo on your device;
- 2. When you find a voice message, double-tap the Play button;
- 3. Double-tap anywhere on the screen.
Expected behavior: The voice message should stop playing because the focus should be on the Pause button.
Actual behavior: I assume the focus is shifting so when I double tap the screen nothing happens. That is, the focus is not on the Pause button. It is rather difficult to search for the Pause button, given that the speech synthesizer is also speaking during the playback of the voice message.

Many thanks for fixing this bug.

**Comment by gerryfrancis** [comment] 2022-07-20 23:25
@bmivzkrp Thank you for your report.

> When you find a voice message, double-tap the Play button;
> Double-tap anywhere on the screen.

It is not clear to me what you try to achieve with a double tap anywhere on the screen. Does it control the e-reader app (start/stop reading)? Do you know a good app available on F-Droid to test with? The ones you recommended cannot be downloaded from there, it seems.

And what is your definition of a voice message? In Delta Chat, voice messages are instant voice recordings done by tapping and holding the microphone icon on the right bottom. Voice messages are not read by an e-reader app, but played in Delta Chat. What you have meant probably is a common text message read by an e-reader app. If this is the case, it is difficult to predict how the controls of a third party app play together with other Android (IM) apps.

Please go into detail, thank you in advance.

**Comment by bmivzkrp** [comment] 2022-07-21 10:39
@gerryfrancis wrote:

> It is not clear to me what you try to achieve with a double tap anywhere on the screen.

OK. In order for you to better understand the situation, I will briefly 
describe exactly how blind users find and activate elements on the screen:
1. We find the element we need on the screen in one of two ways:
1.1. Just slide your finger on the screen, listening to the prompts of 
the speech synthesizer;
1.2. Some blind users, especially those new to using a touchscreen 
device, may find this method difficult at first. Therefore, another 
method is provided: swipes to the right and left imitate cursor arrows. 
That is, a swipe to the left is the previous element, and a swipe to the 
right is the next one;
2. Once the user has focused on an item, they can activate it by double 
tapping anywhere on the screen with one finger. This can be changed in 
the TalkBack or Jieshuo settings, but this is usually the default 
behavior of screen readers.
You can learn more about how blind users use a touch device in the help 
for TalkBack provided by Google:

https://support.google.com/accessibility/android/topic/3529932?hl=uk&ref_topic=9078845

So - an example of a situation:
1. I receive a voice message from someone, let it be the Element 
application (for Matrix);
2. I find this voice message in the corresponding chat and press the 
Play button;
3. Playback of the voice message begins, and at the same time, the Play 
button changes its name to Pause. Focus remains on this button as well. 
Now I can double tap anywhere on the screen to pause the voice message.

I expect to see something similar in Delta Chat as well, as this is the 
correct behavior in many applications, not just messengers.

> Do you know a good app available on F-Droid to test with? The ones you recommended cannot be downloaded from there, it seems.

https://f-droid.org/packages/com.android.talkback/

I m not sure, but it looks like these are builds from the TalkBack FOSS 
project. They stop supporting older devices very quickly, so there is 
nothing for Android 6.0.
So, it probably remains only to install TalkBack from Google Play, or to 
build TalkBack from the source code. It is better to use TalkBack for 
testing.
Jieshuo is a proprietary screen reader. I don t like it, but I have no 
choice because Jieshuo provides so many useful features related to 
accessibility:

https://github.com/nirenr/jieshuo/releases

> And what is your definition of a voice message? In Delta Chat, voice messages are instant voice recordings done by tapping and holding the microphone icon on the right bottom.

These are the records I had in mind.

	P.S.:
Sorry for my bad English. Ukrainian is my native language.

**Comment by bmivzkrp** [comment] 2022-07-22 05:31
@gerryfrancis
One of my friends confirmed the existence of this problem (OUKITEL WP9 
Pro, Android 10).

**Comment by gerryfrancis** [comment] 2022-07-30 15:46
@bmivzkrp I have installed TalkBack on my phone and followed your steps to reproduce the issue successfully. While it might not be possible to pause/stop playback by doubletapping anywhere else on the screen, you could configure a TalkBack setting named "Audio ducking", it decreases the media (playback) volume while speaking. This would help to focus and use the pause button, too, e.g. by wiping and doubletapping it after being focused. The percentage of the medis volume can be reduced to 75, 50, and 25 percent to improve hearing TalkBack hints.

I have tried to research information in regard to accessibility features of other messaging apps, but it seems they rely on tools like TalkBack (for Android) and VoiceOver (for iOS), so I am not sure what we could do on our site to provide "doubletap ooutside the blob to stop audio playback", as our chat view allows to focus other elements during playback.

**Comment by bmivzkrp** [comment] 2022-07-30 16:54
@gerryfrancis
No, this is not an acceptable solution to the problem. That is, the 
meaning is as follows: a completely blind person should be on the same 
level as a person who can see. A sighted person can see the Pause button 
and activate it. That is, it can pause playback of a voice message very 
quickly. While searching for the Pause button, a blind person may miss 
part of the voice message, even if the speech synthesizer volume is 
lower. That is, I want to say that the sighted user and the blind should 
be on equal terms as much as possible.

30.07.22 18:46, gerryfrancis пише:
> @bmivzkrp I have installed TalkBack on my phone and followed your steps to reproduce the issue successfully. While it might not be possible to pause/stop playback by doubletapping anywhere else on the screen, you could configure a TalkBack setting named "Audio ducking", it decreases the media (playback) volume while speaking. This would help to focus and use the pause button, too, e.g. by wiping and doubletapping it after being focused. The percentage of the medis volume can be reduced to 75, 50, and 25 percent to improve hearing TalkBack hints.
> 
> I have tried to research information in regard to accessibility features of other messaging apps, but it seems they rely on tools like TalkBack (for Android) and VoiceOver (for iOS), so I am not sure what we could do on our site to provide "doubletap ooutside the blob to stop audio playback", as our chat view allows to focus other elements during playback.
>

**Comment by gerryfrancis** [comment] 2022-07-30 17:32
@bmivzkrp I see your point. I had a chat with one of the developers recently, he suggested to give that button its focus back after it turned from play to pause, but I do not know if this can be achieved soon. Maybe he and some other developers will chime in here and contribute to the discussion to find a good solution. (I am no developer.)

**Comment by bmivzkrp** [comment] 2022-07-30 21:33
@gerryfrancis
I am also not a developer. I m just a regular blind user pushing 
accessibility into Linux and Android apps that I ve enjoyed. I have 
familiar developers, I will try to involve them in the discussion.

30.07.22 20:33, gerryfrancis пише:
> @bmivzkrp I see your point. I had a chat with one of the developers recently, he suggested to give that button its focus back after it turned from play to pause, but I do not know if this can be achieved soon. Maybe he and some other developers will chime in here and contribute to the discussion to find a good solution. (I am no developer.)
>

**Comment by adbenitez** [comment] 2022-07-30 21:42
hi @bmivzkrp, thanks a lot for using Delta Chat and taking care to provide feedback, it is really appreciated!
I have done quite some improvements to the app in the past so the experience for TalkBack users is better, at a first glance from what you describe I think this should be possible to fix in Delta Chat, right now I don't have the time to dive into this issue and I am not a super skillful Android dev, but will try to fix it when I get the time, but could you please answer why this is a regression??? 
does it used to work fine in the past and now in a recent version it is not working as expected? this could be useful to find out what caused the regression,

best regards,
adb

**Comment by bmivzkrp** [comment] 2022-07-30 21:53
@adbenitez No, it s not actually a regression. I don t know English well, so I formulated the title of the issue in this way. )

**Comment by bmivzkrp** [comment] 2022-07-31 04:04
Hi All.

Below I provide a comment from the developer.

This situation occurs when a chat voice message of interest to the user 
is overlaid with a simultaneous speech of a screen reader (such as 
TalkBack). To avoid overlapping the playback of this voice message and 
the speech output, the user tries to pause the voice message, then turn 
off TalkBack, and then listen to the voice message without problems.
In other words, there are two tasks: to listen to the voice message 
without the interference that the screen reader produces, and to force 
the focus back on the Play / Pause button during the playback of the 
voice message so that the accessibility user (not only the blind, but 
also those with other handicapped, such as those with a motor 
disability) could pause a voice message with a single touch or movement.
Unfortunately, audio focus control does not solve the first of these 
problems, since TalkBack does not reduce its volume, but the volume of 
the chat voice message being played.
Please consider the following possible solutions:
1. Use the AccessibilityManager.isEnabled() method to ensure that any 
accessibility service is enabled (see 
https://developer.android.com/reference/android/view/accessibility/AccessibilityManager).
2. If a voice message is playing and the accessibility service is 
active, then...
2.1. Any touch on the screen (double tap if using a screen reader) or 
pressing a hardware button should pause the playback. Playback should 
continue if the user has explicitly activated the Play button again.
2.2. You can interrupt the TalkBack speech using the 
AccessibilityManager.interrupt() method so that the user can easily 
listen to the voice message without problems. However, the screen reader 
may resume the speech if an accessibility event is raised (meaning that 
this solution does not completely fix the problem).
2.3. Move the focus to the Play/Pause button using the 
Button.requestFocus() method. You will most likely have to interrupt 
TalkBack because the screen reader is trying to indicate the focus move. 
I'm not sure, but maybe the Window.setLocalFocus() method will also 
allow you to move the focus to the desired view.
Please note that changing the state of the foreground activity elements, 
as well as the appearance of new activities, toasts, dialogs or 
notifications on the screen, will provoke a screen reader speech, which 
will interfere with listening to the voice message. If something like 
this happens in your app, for accessibility reasons, it's a good idea to 
slow down such changes until the chat voice message has finished playing.

**Comment by bmivzkrp** [comment] 2023-01-08 14:06
Hi All.
I sincerely apologize. Investigation has shown that this problem does not affect Delta Chat after all. I have already asked the developer of Jieshuo Screen Reader to fix it.

**Comment by r10s** [comment] 2023-01-08 22:33
@bmivzkrp thanks a lot for taking care and coming back to this issue!

so, i close this for now - if it turns out, there is sth. we should do, please reopen with additional information or create a new issue.

**Closed by r10s** 2023-01-08 22:33 UTC
