### ISSUE TITLE
Display "time sent" of message, instead of "time received on device"

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#211] opened 2017-12-01 18:50 UTC
As email is a store and forward system the arrival times differ between receivers and devices.
When the related parties are all online the arrival times may not differ much, and refering to messages by the arrival time may work, but if some where offline it is not possible to say something referring to the answer from say 9:15h, because everybody sees different "arrival times" instead of the "time sent".

**Comment by r10s** [comment] 2017-12-02 11:56
Also to me, the sending time seems to be much more useful; eg for messages as "I'll be there in two minutes" ...

However, AFAIK, Delta Chat already displays the sending time. Only if the sending time is "broken" (eg. is in the future or sth. like that), the arrival time is taken.

It's all a little bit complicated, and I do not remember the details, however, this is how it _should_ work.

**Comment by testbird** [comment] 2017-12-04 12:34
Hm, strange, I've only seen arrival times on all installs (noticeable after a device was offline).

**Comment by r10s** [comment] 2017-12-05 10:05
Might be that one clock was going wrong?

**Comment by testbird** [comment] 2017-12-08 19:35
I don't think anybody adjusted the time manually, but could it be related to some device moving between timezones?

**Comment by testbird** [comment] 2017-12-08 19:36
Actually, the apps where installed in different timezones.

**Comment by ericzolf** [comment] 2018-01-01 16:39
Actually, I can confirm the issue between multiple devices all in the same time zone, and the mail server as well (we are both using a small common e-mail server). The time shown in the client is the time when the message was pulled from the server, and has nothing to do with the time the chat was sent, or even received on the server. There was never any issue with time stamps in any used e-mail client.

**Comment by r10s** [comment] 2018-03-11 01:01
the wrong time display happens when Alice's message to Bob is delayed and Bob sends a message to Alice in between. When Alice's message arrived lately, it will be sorted after Bob's (which is desired), however, the time was displayed wrong. This is fixed by https://github.com/deltachat/deltachat-core/commit/9f4ab2fd876b623a23666522d095cfa3da126664

In short, we can say that:
- the chat is sorted by receiving time
- the displayed times, however, are sending times

**Closed by r10s** 2018-03-11 01:01 UTC
Labels: affects users: in general, impairs: overall app usage, severity 2: expected function
