### ISSUE TITLE
voice messages can't be played (when sent from Android 4)

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#916] opened 2019-05-16 10:08 UTC
When recoding a voice message at v0.200.0 and send it to a dc v0.303.0 version it can't be played.
The opposite way is working!

Recorded voice message at v0.200.0 locally can be replayed clear and loud.

**Comment by webratte** [comment] 2019-05-16 10:12
If it's work with the current version but not with the outdated version it's not a bug anymore I think.

**Comment by csb0730** [comment] 2019-05-16 10:13
With v0.300.0 I mean the current Google Play version. We did the test at 15.05.19

**Comment by csb0730** [comment] 2019-05-16 10:17
Hi, in principle I agree, but there should be an explanation for it.
With older versions there wasn't an issue in that way.

The question is if there is an incompatible change between version 0.200.0 and 0.300.0 somewhere around?

**Comment by r10s** [comment] 2019-05-16 12:13
> The question is if there is an incompatible change between version 0.200.0 and 0.300.0 somewhere around?

no, there was no change at all in this area. at least not intentionally :)

but there voice-messages between 0.20.0 and 0.300.0 are incompatible - maybe you mean 0.20.0 and not 0.200.0?

**Comment by csb0730** [comment] 2019-05-16 14:05
no - v0.200.0 is correct.

Maybe it's my old device (Android 4.1.2) ?

I'm using the 0.200.0. My friends are using the newer 0.303.0.

I'm going to check the mail with Thunderbird ...

**Comment by csb0730** [comment] 2019-05-22 00:23
Found that message sent from v0.303.0 has an attachment like  `voice-message_date_xxxx.aac`
but message sent from v0.200.0 has an attachment like `voice-message_date_xxxx.null`
(file format itself is ok and can be played local or at PC)

![nok-voice-message](https://user-images.githubusercontent.com/30560716/58138670-99fc3900-7c37-11e9-8bba-c9c43b5b8965.png)

I think this wrong file extension of voice mail attachment ".null" is the reason for not playing the file at dc v0.303.0.

IMHO this issue should be solved because v0.303.0 sends the correct extension and I'm able to play it.

**Comment by csb0730** [comment] 2019-05-27 23:19
I think that's it.
If the issue occurs again in future with newer versions it can be re-opened.

**Comment by csb0730** [comment] 2019-06-14 22:38
Tested with version 0.304.0 now but same behaviour. voice file is created with extenstion ".null".
Maybe this issue is realted to Android 4 ?
Q: Where and how the filename is created?

**Comment by r10s** [comment] 2019-06-17 22:26
closed by https://github.com/deltachat/deltachat-android/pull/954

**Closed by r10s** 2019-06-17 22:26 UTC
Labels: android4
