### ISSUE TITLE
show a hint that qr-verification cannot be done without network

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#756] opened 2019-03-07 17:59 UTC
- Platform (android/blackberry/anbox): Android
- Device: Moto G3
- Delta Chat Version: 0.101.1
- Expected behavior: The verified key should be transferred on the next internet connection
- Actual behavior: DC tries to transfer the key instantly, which doesn't work. To continue using Delta Chat you need to press "Cancel".
- Steps to reproduce the problem: Scan a QR invite code without internet

**Comment by r10s** [comment] 2019-03-07 18:15
i'd say this is by design, at least for now.

the verification is not only about transferring a key but also about receiving the key of the other side and about knowing that the other side knows that you have the key. this requires a network connection.

even if we could delay this in a way, there would be no clear verification result after scanning and it would be confusing ux-wise when and if you can add the contact eg. to a verified group.

however, there are rough ideas to allow verifications also through other channels that do not required a in-person-meeting and can be used when both sides have actually network.

**Comment by Hocuri** [comment] 2019-03-07 18:37
Well a dialog "No Internet connection. The contact will be verified when you are connected again" could appear.

**Comment by r10s** [comment] 2019-03-08 13:38
might be that the qr code is not valid "forever", so this is not really an option.

so, at least for now, network is required during out-of-band-verification :)

**Comment by Hocuri** [comment] 2019-03-08 20:52
> might be that the qr code is not valid "forever", so this is not really an option.

Do you mean that the keys change, e.g. after reinstalling DC? Or that they dynamically change?

**Comment by r10s** [comment] 2019-03-08 21:04
currently, the qr codes are more or less static to make testing easier (it's still an experimental feature!), however, there are ideas that the qr-code shown is only valid for a short period of time, say one minute.

in this case the out-of-band-verification needs network anyway.

to keep us the option in the future and to make things easier, it's seems to be appropriate to keep the network requirement for now. 

also, as mentioned, imho an out-of-band-verification is a "thing" that is done by two people at a given time with an immediate outcome. ux-wise everything else would be more complicated.

**Comment by BachUhr** [comment] 2019-03-08 21:15
> even if we could delay this in a way, there > would be no clear verification result after > scanning and it would be confusing ux-    > wise when and if you can add the contact   > eg. to a verified group.

But at the moment there is no notification or sth. like this, so it is not obvious that the verification cannot be done.
This is confusing too, maybe there could be a notification so that the user knows that an internet connection is necessary.

**Comment by r10s** [comment] 2019-03-08 21:31
> But at the moment there is no notification or sth. like this, so it is not obvious that the verification cannot be done.

yip, this is something we should target.

**Comment by Hocuri** [comment] 2019-03-09 11:15
We can continue the discussion here: https://support.delta.chat/t/additionally-keep-static-qr-codes-for-offline-out-of-band-verification/301

**Comment by Boehrsi** [comment] 2019-05-10 06:32
I will add some kind of hint today, so the user is aware of the required internet connection.

**Comment by r10s** [comment] 2019-05-15 15:02
closed by #904

**Closed by r10s** 2019-05-15 15:02 UTC
Labels: good first issue
