### ISSUE TITLE
No new messages after upgrade from 0.510.1 to 1.1.2

### ISSUE THREAD

**Issue by rootuser1** [deltachat/deltachat-android#1244] opened 2020-02-07 16:53 UTC
I've recently upgraded two devices from Delta Chat F-Droid 0.510.1 to 1.1.2. Since then no messages are being received in Delta Chat anymore. Messages are being sent and I can see them being delivered to the mailbox / INBOX using an IMAP client, but they are not being moved to the DeltaChat folder.

This seems to be related to #1239 and https://support.delta.chat/t/delta-chat-is-no-longer-working-after-udpate/706 (same hosting provider).

- Android version: Both 8
- Device: Samsung & Motorola
- Delta Chat version: 1.1.2
- Expected behavior: Messages are moved / received
- Actual behavior: Messages are not moved / received
- Steps to reproduce the problem: Upgrade from Delta Chat F-Droid 0.510.1 to 1.1.2
- Screenshots: -
- Logs:

The only suspicious line(s) in the logs seem(s) to be:
> 02-07 17:30:00.000 15680 15707 W DeltaChat: ThreadId(7) src/job_thread.rs:93: connect+fetch failed: Watch folder not found "not-set"

**Comment by gerryfrancis** [comment] 2020-02-07 17:15
Probably a duplicate of https://github.com/deltachat/deltachat-android/issues/1239 .

**Closed** 2020-02-07 21:19 UTC
Labels: duplicate
