### ISSUE TITLE
Strange behavior when pasting text onto emoji

### ISSUE THREAD

**Issue by Gh0stz0x** [deltachat/deltachat-android#3099] opened 2024-05-25 17:20 UTC
- Android version: 10
- Device: Huawei Mate 20
- Delta Chat version: 1.46.0
- Expected behavior: When I paste text containing emoji onto an emoji, the characters should not disappear.
- Actual behavior: If you paste text with emoji onto an emoji the text disappears, if you leave the chat and re-enter the text it reappears.
- Steps to reproduce the problem: Copy some text with emojis inside, then insert an emoji into the chat without sending it, select the emoji and paste the previously copied text.
- Screenshots:

https://github.com/deltachat/deltachat-android/assets/168986411/9d2fcf0f-4331-4a42-b8af-de6953df95aa

- Logs:

**Comment by adbenitez** [comment] 2024-06-14 14:12
duplicate of #1993

**Closed by adbenitez** 2024-06-14 14:12 UTC
Labels: bug
