### ISSUE TITLE
Size limit ends in endless upload

### ISSUE THREAD

**Issue by JobbeDeluxe** [deltachat/deltachat-android#102] opened 2017-06-11 19:44 UTC
If the email size limit is aktiv and you try to send something (just a file) bigger than this limit, the send will fail and delta chat will try to resend it. This will be repeated  for a unlimited time. And every time will be send the max data limit. So it will consume the mobile data as well. 
After 3 or more tries, delta should say something or abort the sending?

**Comment by r10s** [comment] 2017-06-12 06:40
Thank you very much, for this, I will check this. Do you know anything about the typical size limits and/or error codes one gets?

**Comment by JobbeDeluxe** [comment] 2017-06-12 08:10
On my one, Linux with postfix and dovecot the default size limit is 10 MB. 
I now removed the limit. 
I will try to get an log file from the error today.

**Comment by JobbeDeluxe** [comment] 2017-06-12 18:36
I have test this some time.
It seams so be that the connection will be disconnected after size limit is reached. And DeltChat is try to resend ever minute or on every reconnect like mobile data changed.
I can force the re upload by switching Wlan off an on again.
The log ist just i try to upload and wait 5 minutes:
`Jun 12 20:12:32 TestServer dovecot: imap-login: Disconnected (no auth attempts in 17 secs): user=<>, rip=0my.0ip.add.000, lip=0my.local.addr.serv, TLS, session=<fCRFQ8dRWd1ZD+4i>
Jun 12 20:12:33 TestServer dovecot: imap-login: Login: user=<User>, method=PLAIN, rip=0my.0ip.add.000, lip=0my.local.addr.serv, mpid=16574, TLS, session=<uyY6Q8dR58JZD+4i>
Jun 12 20:12:33 TestServer dovecot: imap-login: Disconnected (no auth attempts in 18 secs): user=<>, rip=0my.0ip.add.000, lip=0my.local.addr.serv, TLS, session=<alZRQ8dRvoRZD+4i>
Jun 12 20:12:33 TestServer dovecot: imap-login: Login: user=<User>, method=PLAIN, rip=0my.0ip.add.000, lip=0my.local.addr.serv, mpid=16575, TLS, session=<0iRIQ8dRce9ZD+4i>
Jun 12 20:13:12 TestServer dovecot: imap(User): Connection closed (IDLE running for 0.001 + waiting input for 332.938 secs, 2 B in + 10+0 B out, state=wait-input) in=28 out=703
Jun 12 20:13:12 TestServer dovecot: imap(User): Connection closed (IDLE running for 0.001 + waiting input for 332.902 secs, 2 B in + 10+0 B out, state=wait-input) in=27 out=705
Jun 12 20:13:15 TestServer dovecot: imap(User): Connection closed (IDLE running for 0.001 + waiting input for 42.634 secs, 2 B in + 10+0 B out, state=wait-input) in=28 out=652
Jun 12 20:13:15 TestServer dovecot: imap(User): Connection closed (IDLE running for 0.001 + waiting input for 42.411 secs, 2 B in + 10+0 B out, state=wait-input) in=27 out=654
Jun 12 20:13:16 TestServer dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=0my.0ip.add.000, lip=0my.local.addr.serv, TLS, session=<HE7jRcdRpOJZ9XNf>
Jun 12 20:13:16 TestServer dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=0my.0ip.add.000, lip=0my.local.addr.serv, TLS, session=<lXTjRcdRpuJZ9XNf>
Jun 12 20:13:16 TestServer dovecot: imap-login: Login: user=<User>, method=PLAIN, rip=0my.0ip.add.000, lip=0my.local.addr.serv, mpid=16598, TLS, session=<bkzjRcdRo+JZ9XNf>
Jun 12 20:13:16 TestServer dovecot: imap-login: Login: user=<User>, method=PLAIN, rip=0my.0ip.add.000, lip=0my.local.addr.serv, mpid=16599, TLS, session=<+OrkRcdRpeJZ9XNf>
Jun 12 20:13:27 TestServer dovecot: imap(User): Disconnected for inactivity in=1018 out=35615
Jun 12 20:13:27 TestServer dovecot: imap(User): Disconnected for inactivity in=1210 out=6071
Jun 12 20:13:42 TestServer dovecot: imap-login: Login: user=<User>, method=PLAIN, rip=0my.0ip.add.000, lip=0my.local.addr.serv, mpid=16614, TLS, session=</klxR8dRq+JZ9XNf>
Jun 12 20:13:56 TestServer postfix/smtpd[16403]: timeout after AUTH from My.IPS.Provider[0my.0ip.add.000]
Jun 12 20:13:59 TestServer postfix/smtpd[16403]: disconnect from My.IPS.Provider[0my.0ip.add.000] ehlo=1 auth=1 commands=2
Jun 12 20:14:00 TestServer postfix/smtpd[16403]: connect from My.IPS.Provider[0my.0ip.add.000]
Jun 12 20:14:02 TestServer postfix/smtpd[16403]: 727C5C6080D: client=My.IPS.Provider[0my.0ip.add.000], sasl_method=PLAIN, sasl_username=User
Jun 12 20:14:02 TestServer postfix/cleanup[16617]: 727C5C6080D: message-id=<Mr.WT7ZwHAhsnr.User@my_mail_adress.org>
Jun 12 20:14:05 TestServer postfix/smtpd[16403]: warning: 727C5C6080D: queue file size limit exceeded
Jun 12 20:14:15 TestServer postfix/smtpd[16403]: disconnect from My.IPS.Provider[0my.0ip.add.000] ehlo=1 auth=1 mail=1 rcpt=1 data=0/1 quit=1 commands=5/6
Jun 12 20:15:25 TestServer dovecot: imap(User): Connection closed (IDLE running for 0.001 + waiting input for 128.689 secs, 2 B in + 10+0 B out, state=wait-input) in=28 out=669
Jun 12 20:15:25 TestServer dovecot: imap(User): Connection closed (IDLE running for 0.001 + waiting input for 128.843 secs, 2 B in + 10+0 B out, state=wait-input) in=27 out=671
Jun 12 20:15:41 TestServer dovecot: imap-login: Login: user=<User>, method=PLAIN, rip=0my.0ip.add.000, lip=0my.local.addr.serv, mpid=16656, TLS, session=<1u9xTsdRx+JZ9XNf>
Jun 12 20:15:41 TestServer dovecot: imap-login: Login: user=<User>, method=PLAIN, rip=0my.0ip.add.000, lip=0my.local.addr.serv, mpid=16657, TLS, session=<reWDTsdRxuJZ9XNf>
Jun 12 20:15:55 TestServer dovecot: imap-login: Login: user=<User>, method=PLAIN, rip=0my.0ip.add.000, lip=0my.local.addr.serv, mpid=16659, TLS, session=<+ptkT8dRyeJZ9XNf>
Jun 12 20:16:16 TestServer postfix/smtpd[16670]: connect from My.IPS.Provider[0my.0ip.add.000]
Jun 12 20:16:18 TestServer postfix/smtpd[16670]: D7157C6080D: client=My.IPS.Provider[0my.0ip.add.000], sasl_method=PLAIN, sasl_username=User
Jun 12 20:16:18 TestServer postfix/cleanup[16671]: D7157C6080D: message-id=<Mr.WT7ZwHAhsnr.User@my_mail_adress.org>
Jun 12 20:16:21 TestServer postfix/smtpd[16670]: warning: D7157C6080D: queue file size limit exceeded
Jun 12 20:16:26 TestServer postfix/smtpd[16670]: disconnect from My.IPS.Provider[0my.0ip.add.000] ehlo=1 auth=1 mail=1 rcpt=1 data=0/1 quit=1 commands=5/6
Jun 12 20:16:34 TestServer postfix/smtpd[16196]: disconnect from 0my.mobil.addr.000[0my.mobil.addr.000] ehlo=1 auth=1 mail=1 rcpt=1 data=0/1 commands=4/5
Jun 12 20:17:16 TestServer dovecot: imap(User): Connection closed (IDLE running for 0.001 + waiting input for 1457.214 secs, 2 B in + 10+0 B out, state=wait-input) in=1206 out=3348
Jun 12 20:17:26 TestServer postfix/smtpd[16670]: connect from My.IPS.Provider[0my.0ip.add.000]
Jun 12 20:17:41 TestServer postfix/smtpd[16670]: 2A478C6080A: client=My.IPS.Provider[0my.0ip.add.000], sasl_method=PLAIN, sasl_username=User
Jun 12 20:17:41 TestServer postfix/cleanup[16671]: 2A478C6080A: message-id=<Mr.WT7ZwHAhsnr.User@my_mail_adress.org>
Jun 12 20:17:51 TestServer postfix/smtpd[16670]: warning: 2A478C6080A: queue file size limit exceeded
Jun 12 20:18:01 TestServer postfix/smtpd[16670]: disconnect from My.IPS.Provider[0my.0ip.add.000] ehlo=1 auth=1 mail=1 rcpt=1 data=0/1 quit=1 commands=5/6
Jun 12 20:18:01 TestServer postfix/smtpd[16196]: connect from My.IPS.Provider[0my.0ip.add.000]
Jun 12 20:18:08 TestServer postfix/smtpd[16196]: 1F4A9C6080A: client=My.IPS.Provider[0my.0ip.add.000], sasl_method=PLAIN, sasl_username=User
Jun 12 20:18:08 TestServer postfix/cleanup[16203]: 1F4A9C6080A: message-id=<Mr.WT7ZwHAhsnr.User@my_mail_adress.org>
Jun 12 20:18:10 TestServer postfix/smtpd[16196]: warning: 1F4A9C6080A: queue file size limit exceeded
Jun 12 20:18:20 TestServer postfix/smtpd[16196]: disconnect from My.IPS.Provider[0my.0ip.add.000] ehlo=1 auth=1 mail=1 rcpt=1 data=0/1 quit=1 commands=5/6
Jun 12 20:20:12 TestServer postfix/anvil[16200]: statistics: max connection rate 2/60s for (smtps:0my.0ip.add.000) at Jun 12 20:18:02
Jun 12 20:20:12 TestServer postfix/anvil[16200]: statistics: max connection count 1 for (smtps:0my.0ip.add.000) at Jun 12 20:14:00
Jun 12 20:20:12 TestServer postfix/anvil[16200]: statistics: max cache size 1 at Jun 12 20:16:16
Jun 12 20:20:51 TestServer dovecot: imap(User): Connection closed (IDLE running for 0.001 + waiting input for 1029.489 secs, 2 B in + 10+0 B out, state=wait-input) in=24 out=831
`

**Comment by mukhametshin** [comment] 2017-09-16 10:59
I confirm the bug (however I currently have no screenshots or logs to prove it). DC has eaten all my cellular traffic for the month in couple of minutes as I was trying to send a large file to my friend over DC. The friend didn't receive the file and now I kill DC if I'm connected over cellular data, and start it if I'm online over wifi.

In disregard of this bug It would be nice to introduce the option "connect over wifi only" or "send attachments (files) over wifi only".

**Comment by r10s** [comment] 2017-09-16 14:56
+1

**Comment by r10s** [comment] 2017-09-16 14:59
I think, in general, Delta Chat should stop trying after a number of attemps (not counting the cases where there is no connection at the moment of failure)

**Comment by testbird** [comment] 2018-04-10 10:52
Is there something else then reinstalling to stop looping?
It's grave, possibly I also overlooked this reason when things got frozen in the past.

**Comment by JobbeDeluxe** [comment] 2018-04-10 11:12
I was able to remove the file that is too large. Than it was done.

**Comment by testbird** [comment] 2018-04-10 12:16
Ah, ok removing from storage, good idea, thanks!

**Comment by testbird** [comment] 2018-04-10 13:01
MUA log from sending a too large message:
```
ESMTP 235 Authentication succeeded
ESMTP MAIL FROM:<...>
SMTP 552-Requested mail action aborted: exceeded storage allocation 
SMTP 552 Mail size limit exceeded.
```

**Comment by r10s** [comment] 2018-05-24 22:46
in general, we should not try to send messages that are "too big"

**Comment by testbird** [comment] 2018-05-25 00:40
The problem is also prominent with accounts with rather low limits like 10MB.

**Comment by kecksk0enig** [comment] 2018-07-05 09:02
This one hit me too, tried to upload 50MB video...
![screenshot_20180705-105442](https://user-images.githubusercontent.com/4678750/42313354-d5b6c826-8042-11e8-938c-daa135bb4d5c.png)
![screenshot_20180705-105336](https://user-images.githubusercontent.com/4678750/42313355-d61883b8-8042-11e8-9a77-0be50300a859.png)

**Comment by r10s** [comment] 2018-07-10 16:53
@kecksk0enig thanks for the report, i think we will target this issue with the next release, >0.20.0 then

**Comment by r10s** [comment] 2018-07-11 22:05
should be fixed by https://github.com/deltachat/deltachat-core/pull/209:

- if a message cannot be sent for any reasons, _and_ there is network available after the failure, Delta tries over after 2 seconds and after 60 seconds (we do two tries to catch server-overloads and such things)
- if the message still cannot be sent, the job is removed and the message is marked as being failed to send.
- in the message info, the reason for failure is shown.

this approach should catch the issue above - as well as many other issues as bad recipients, quota and so on.

**Closed by r10s** 2018-07-11 22:05 UTC
Labels: bug

**Comment by r10s** [comment] 2018-07-12 11:43
i've refined the cases for low storate and too large mails in https://github.com/deltachat/deltachat-core/commit/c6b158a65cf5d262df06cec4f71c928600871201
