### ISSUE TITLE
crash in 'show all locations'

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1633] opened 2020-09-25 12:23 UTC
reported in testing group:

> did anyone noticed that when you open the menu from the chat list, select 
to show all locations, the app crashes

> after some seconds

![image-3494458663](https://user-images.githubusercontent.com/9800740/94266540-95861580-ff3a-11ea-990c-7f10775f43b0.jpg)

**Comment by adbenitez** [comment] 2021-06-25 21:41
I didn't realized that this issue exists and opened #1936 which is kind of a duplicate of this one, I think it was myself who shared that image in the testing group, I am able to reproduce the `java.lang.Exception: Last location unavailable` but I no longer get the fatal `NullPointerException`, the app doesn't crash and it is in a rather uncommon situation, so I will close this issue

**Closed by adbenitez** 2021-06-25 21:41 UTC
Labels: bug
