### ISSUE TITLE
Sharing from special app crashed

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#996] opened 2019-07-06 11:46 UTC
It crashed by sharing from this app: https://play.google.com/store/apps/details?id=de.badischezeitung.smart

There are also other News Apps who using (probably) the same software as Badische Zeitung.
So I think this issue also concerns also other Apps.

- Platform (android/blackberry/anbox): Android 7
- Device: Huawei nova
- Delta Chat Version: 0.500.0
- Expected behavior: Sharing links to DC
- Actual behavior: Chrash of DC

**Comment by Boehrsi** [comment] 2019-07-09 17:52
I would have a look on Friday, if the issue isn't fixed until then.

**Comment by Boehrsi** [comment] 2019-07-12 09:12
The PR should fix the problem. The actual problem was, that the mentioned app attached a SpannableString instead of a String. Kind of uncommon and "special", but the Delta shouldn't crash. Both cases are working now and I added a check to avoid further crashes, if no valid text is given.

**Comment by r10s** [comment] 2019-07-12 09:57
great that you figured that out!

**Comment by r10s** [comment] 2019-07-12 13:38
fixed by https://github.com/deltachat/deltachat-android/pull/1003

**Closed by r10s** 2019-07-12 13:38 UTC
Labels: bug
