### ISSUE TITLE
ANR in ConversationFragment.onResume()

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#3504] opened 2024-12-17 16:32 UTC
caused by `[libnative-utils.so] dc_marknoticed_chat`:
```
 #00  pc 0x000000000004b20c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
    
  
      #01  pc 0x0000000000cd0088  /data/app/~~KPtQ_9O6KqxixjvNdrlq5Q==/chat.delta-loT4g48vjTcQzJYPVnLLJg==/lib/arm64/libnative-utils.so
    
  
      #02  pc 0x0000000000ccfba8  /data/app/~~KPtQ_9O6KqxixjvNdrlq5Q==/chat.delta-loT4g48vjTcQzJYPVnLLJg==/lib/arm64/libnative-utils.so
    
  
      #03  pc 0x0000000000e1e8f0  /data/app/~~KPtQ_9O6KqxixjvNdrlq5Q==/chat.delta-loT4g48vjTcQzJYPVnLLJg==/lib/arm64/libnative-utils.so
    
  
      #04  pc 0x0000000000e1f1ec  /data/app/~~KPtQ_9O6KqxixjvNdrlq5Q==/chat.delta-loT4g48vjTcQzJYPVnLLJg==/lib/arm64/libnative-utils.so
    
  
      #05  pc 0x0000000000822f6c  /data/app/~~KPtQ_9O6KqxixjvNdrlq5Q==/chat.delta-loT4g48vjTcQzJYPVnLLJg==/lib/arm64/libnative-utils.so (dc_marknoticed_chat+388)
    
  
      at com.b44t.messenger.DcContext.marknoticedChat (Native method)
    
  
      at org.thoughtcrime.securesms.ConversationFragment.onResume (ConversationFragment.java:214)
    
  
      at androidx.fragment.app.Fragment.performResume (Fragment.java:3180)
    
  
      at androidx.fragment.app.FragmentStateManager.resume (FragmentStateManager.java:606)
    
  
      at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:285)
    
  
      at androidx.fragment.app.FragmentStore.moveToExpectedState (FragmentStore.java:113)
    
  
      at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1433)
    
  
      at androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:2977)
    
  
      at androidx.fragment.app.FragmentManager.dispatchResume (FragmentManager.java:2909)
    
  
      at androidx.fragment.app.FragmentController.dispatchResume (FragmentController.java:285)
    
  
      at androidx.fragment.app.FragmentActivity.onResumeFragments (FragmentActivity.java:334)
    
  
      at androidx.fragment.app.FragmentActivity.onPostResume (FragmentActivity.java:323)
    
  
      at androidx.appcompat.app.AppCompatActivity.onPostResume (AppCompatActivity.java:245)
    
  
      at android.app.Activity.performResume (Activity.java:8291)
    
  
      at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4547)
    
  
      at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4592)
    
  
      at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
    
  
      at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
    
  
      at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
    
  
      at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2125)
    
  
      at android.os.Handler.dispatchMessage (Handler.java:106)
    
  
      at android.os.Looper.loop (Looper.java:223)
    
  
      at android.app.ActivityThread.main (ActivityThread.java:7999)
    
  
      at java.lang.reflect.Method.invoke (Native method)
    
  
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:635)
    
  
      at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
```

**Comment by adbenitez** [comment] 2024-12-17 16:33
some how the call to `dcContext.marknoticedChat((int) chatId)` is getting stuck

**Comment by r10s** [comment] 2024-12-17 16:39
thanks for figuring that out!  so then sth. might be wrong in core, and there may be situations where 
marknoticedChat() does not return immediately? cc @link2xt 

ntw, it is ANR, not ARN :)

_ "ANR"_ is an abbreviation for the spanish term _"Aplicación No Responde"_

**Comment by adbenitez** [comment] 2024-12-17 16:46
oops! dyslexia! XD

**Comment by iequidoo** [comment] 2024-12-18 01:24
`chat::marknoticed_chat()` only has 3 `await`s and all of them are for SQL queries, though if it marks all messages in the archive as noticed, i think it may take noticeable time. Is this reproducible?

**Comment by Hocuri** [comment] 2024-12-18 12:04
In the stack trace, it can be seen that a specific chat was marked as noticed, not all messages in the archive. Because marknoticedChat was called from `ConversationFragment.java:214`, not `ConversationListArchiveActivity.java:69`.

Of course it might still be possible that this person had 1000s of unread messages, all of which were marked as unread, possibly while the phone was doing some other work in the background.

I can't think of anything core could do about it, so maybe we should just move `marknoticed_chat()` to a background thread?

**Closed** 2024-12-18 14:41 UTC
Labels: bug
