### ISSUE TITLE
taking up a huge amount of storage space

### ISSUE THREAD

**Issue by zecamigo** [deltachat/deltachat-android#376] opened 2018-08-07 22:36 UTC
**Delta Chat version**

v0.17.3

**Expected behavior**

Manageable storage (specially attachments)

**Actual behavior**

Overgrown data folder taking all my free internal storage space

**Steps to reproduce the problem**

1. Get an old phone (e.g. LG E 610) that doesn't support moving apps to the Ext SD Card
2. Chat and share files freely for a while
3. Watch your storage space go away
4. Unless you have rooted your phone and understand what files to erase from your data folder, dump either deltachat or the whole app data.

**Screen snapshots**

NA

**Debug logs**

Not really a bug, more a feature request:

- an option to pick a folder in an external SD card for storing attachments, or
- an option to erase attachments

Thanks!

**Comment by r10s** [comment] 2018-08-08 13:48
@zecamigo thank you for your post, maybe this is a duplicate of https://github.com/deltachat/deltachat-android/issues/22

**Comment by csb0730** [comment] 2018-08-08 14:15
Extension of #22 ?

**Closed** 2018-08-20 08:11 UTC
