### ISSUE TITLE
Suggestions to include a data and storage feature

### ISSUE THREAD

**Issue by abasifreke50** [deltachat/deltachat-android#778] opened 2019-03-22 22:51 UTC
I have used the Delta chat application for quite some time now, and I'll love to make a suggestion.

Going through the Delta application, there's no feature called the data and storage feature. I believe it will be good to have this feature on the delta chat application.

#### What is Data and storage usage feature ?

Well I thought of this feature today while conversing with my friend tobi. We were sharing pictures which we took in an event yesterday so it struck me that there is no feature on the delta chat which provides control over the media files shared within the platform.

I'm suggesting that data and storage usage feature should be included, and when it is done, it should provide options for media auto-download and an option to control how media files are downloaded when share.

The developers should make available an option to choose between WiFi, cellular and never when downloading a media file. Thank you

**Comment by hpk42** [comment] 2019-03-23 01:01
I think this is a duplicate of https://github.com/deltachat/deltachat-android/issues/779#issuecomment-475825687 ? Also closing this issue here as it better goes to the support forum.

**Closed by hpk42** 2019-03-23 01:01 UTC

**Comment by webratte** [comment] 2019-03-23 05:40
Hi,
similar things I suggested already in the forum:
https://support.delta.chat/t/ideas-for-image-compression-feature/313

Maybe the discussion should go on here.
Devs read in the forum. Maybe they will also think it's import and pick it up 😉
