### ISSUE TITLE
Disappearing messages activate after sending image to group

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-android#1974] opened 2021-07-11 13:08 UTC
A user on delta@merlinux reports that in their group, disappearing messages gets activated sometimes if someone in the group sends a picture. It's not a single person but happens for all of them. I asked for a log. will edit it as soon as i received it.

They all use deltachat on android with version 1.20.5

**Comment by link2xt** [comment] 2021-09-27 01:25
There are multiple fixes for disappearing message timer synchronization scheduled for deltachat core 1.61.0 covered by tests, the bug is likely fixed. There is no log, so the issue is not actionable anyway, closing.

**Closed by link2xt** 2021-09-27 01:25 UTC
Labels: bug
