### ISSUE TITLE
maybe switch to debug symbols as recommended by gplay

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1715] opened 2020-11-06 17:19 UTC
not sure, if this is useful/doable, just want to mention that the play store issues a hint saying:

_"This APK contains native code, and you've not uploaded debug symbols. We recommend you upload a symbol file to make your crashes and ANRs easier to analyze and debug. [Learn More](https://developer.android.com/studio/build/shrink-code#native-crash-support)"_

**Comment by Hocuri** [comment] 2020-11-07 11:21
Duplicate of #1716 :joy:

**Closed by Hocuri** 2020-11-07 11:21 UTC
Labels: discussion

**Comment by r10s** [comment] 2020-11-07 12:45
no idea why this was created two times. thanks for closing.
