### ISSUE TITLE
group encryption is disabled when new members added

### ISSUE THREAD

**Issue by fauno** [deltachat/deltachat-android#163] opened 2017-09-04 22:57 UTC
we've been testing the app with a few people (6 now) and we found that group encryption is disabled when at least a pubkey is missing.  if the other person takes a while to write back, the encryption is disabled until she sends a message.  wouldn't it be better to keep encrypting and inform the other person that she won't be able to read the messages until she sends one first?

**Comment by r10s** [comment] 2017-09-05 20:58
> wouldn't it be better to keep encrypting and inform the other person that she won't be able to read the messages until she sends one first?

The encryption in Delta Chat (which uses [Autocrypt](https://autocrypt.readthedocs.io/en/latest/features.html)) is [_opportunistic_](https://tools.ietf.org/html/rfc7435.html), this means, if we cannot end-to-end-encrypt for any reason at a given time, we stop end-to-end-encryption and start it again automatically as soon as this becomes possible again.

One reason for this approach is a better user experience and a better acceptance of encryption at all if the encryption does not prevent my from communicating.

However, for the concrete scenario, _a new group member whose key is unknown to most of the other members,_ there is already a better concept available: [_Key Gossip_](https://autocrypt.readthedocs.io/en/latest/level1.html#key-gossip) - we will add this as soon as we have the time (and/or the money :)

**Comment by testbird** [comment] 2017-10-14 12:15
I have not understood yet if the key gossip can really solve the problem reported here.

Even if the keys of all current recipients are included, the key of a new participant may not be already known, and not get included.

The problem is that this disrupts/breaks the crypto for all others of the group.
Maybe, use a special invitation messages (marked as such) to new members that won't revert all other recepients to send plain text again, until the new member sends a message. Or is there a "require autocrypt" option?

**Comment by r10s** [comment] 2017-10-14 12:31
Well, Key Gossip may reduce the problem: 

- A, B and C are in a group and communicate encrypted
- A adds member D to the group, A has the key of D but B and C not yet
- the mail "I've added member D the group" (already now send from A to B and C automatically when adding members) would automatically the key of D
- as a result, all members have all keys of all other members and they can continue communicating encrypted

Of course, this would not work if the key of D is not known to A - in this case, encryption breaks in favour to communication.

**Comment by r10s** [comment] 2017-11-18 13:37
Move this issue to the core, see https://github.com/deltachat/deltachat-core/issues/63

**Closed by r10s** 2017-11-18 13:37 UTC
