### ISSUE TITLE
Share to chat from share menu doesn't work

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#1028] opened 2019-08-27 21:24 UTC
Share to a specific (recently contacted) contact/chat was proposed and implemented with #900,
But it doesn't work as expected: I can click on share with this contact and it presents the select contact to share menu thingie anyways and ignores the contact I actually clicked on in the first place.

If its hard to reproduce I will share more device info and such things, just answer to this post.

**Comment by Vistaus** [comment] 2019-08-31 11:30
Can't reproduce on my phone.

**Comment by Simon-Laux** [comment] 2019-08-31 11:35
I have android 9 and DC 0.510.1 playstore edition.
What versions did you test on?

Am 31. August 2019 13:30:20 MESZ schrieb Heimen Stoffels <notifications@github.com>:
>Can't reproduce on my phone.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-android/issues/1028#issuecomment-526823105

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Vistaus** [comment] 2019-08-31 11:36
My phone has Android 8.1 and DC 0.510.1 Play Store edition.

**Comment by Simon-Laux** [comment] 2019-09-02 06:07
![image-1567404479](https://user-images.githubusercontent.com/18725968/64093445-a7f24780-cd58-11e9-9e14-3dcf70cf296e.jpg)
To make sure we're talking about the same thing.

**Comment by Vistaus** [comment] 2019-09-02 10:14
We are. Seems like this is a Pie-related bug.

**Comment by Simon-Laux** [comment] 2019-09-02 10:17
I'll update my phone, seems like there is a patch, lets see if it fixes our issue here.

**Comment by Vistaus** [comment] 2019-09-02 10:20
I didn't mean that this has to be a bug in Pie per se (although I can't rule that out either), but that this is a bug that only occurs on Pie since I don't have the issue on Oreo.

**Comment by Simon-Laux** [comment] 2019-09-02 12:28
Sharing works only sometimes now as expected. Also when discarding draft and going back I get the "share to" scree and on going back from there it goes back to homescreen/previous app and when entering it again its still in the "share to" screen and it closes the app again, in need to kill the app to get back to it.

**Comment by cyBerta** [comment] 2019-10-24 10:24
> Sharing works only sometimes now as expected. Also when discarding draft and going back I get the "share to" scree and on going back from there it goes back to homescreen/previous app and when entering it again its still in the "share to" screen and it closes the app again, in need to kill the app to get back to it.

So this seems to be another bug then. Do you have updates on the first one? You said you've installed a patch for your phone?

**Comment by cyBerta** [comment] 2019-11-22 15:35
What I saw is that if you have a chat opened, press the home button, chose an item to share, click on the same contact with the opened chat, only the chat list appears, instead of the actual chat. 
On the other hand, if you have the chat list opened and repeat this procedure you will end at the expected chat.  
It is reproducible and a bug, that should be fixed.

**Comment by Hocuri** [comment] 2020-03-29 15:50
In case this helps: I also have this bug on my phone. I'll see if I can fix it as soon as I find the time.

**Comment by Vistaus** [comment] 2020-03-29 16:22
As I said before, I didn't have the issue on Oreo, BUT I also don't have this issue on Pie. So not sure where the issue is coming from then, perhaps it's manufacturer-specific?

**Comment by Hocuri** [comment] 2020-03-30 08:18
Ok, I found it out: https://github.com/deltachat/deltachat-android/pull/1273

**Closed** 2020-04-02 13:12 UTC
Labels: bug

**Comment by r10s** [comment] 2020-04-02 15:43
great, thanks, @Hocuri :)
