### ISSUE TITLE
opening PDF directly not possible sometimes

### ISSUE THREAD

**Issue by gitgerardo** [deltachat/deltachat-android#1154] opened 2019-12-11 12:11 UTC
It isn't possible to **open** an attached **PDF** directly inside the App.  I have to save it in order to be able to open it.
Device:
Oneplus 6
OS :
Lineage 16 , latest build
( Android 9 )

**Comment by r10s** [comment] 2019-12-17 21:54
i cannot reproduce that on my devices. maybe the used PDF-viewer (Delta Chat has not a PDF-view build-in!) is not properly registered?

can you please retry with the [DocumentViewer eg. from F-Droid](https://f-droid.org/en/packages/org.sufficientlysecure.viewer/) that is known to work with Delta Chat. this way, we can try to figure out what the cause of the issue is.

**Comment by gitgerardo** [comment] 2019-12-17 22:12
Please look at the screenshot, it doesn't give me the option to open, like it did always before.

![Screenshot_20191217-230729_Delta_Chat](https://user-images.githubusercontent.com/33866993/71038459-29ac8c00-2122-11ea-873c-e5f3e4c4ab5d.png)

**Comment by r10s** [comment] 2019-12-17 22:48
did you tried with the "Document Viewer" installed? because the message just says that the system knows no app that can handle this kind of documents. i comes from the system, i fear there is not much we can do about that.

however, the message is weird, in theory, there should also pop up "Can't find an app to handle this type of data" before. but i change that.

**Comment by gitgerardo** [comment] 2019-12-18 07:39
Now I deinstalled the PDF viewer which I used before (xodo) and I installed "document viewer" from f-droid. Same result as you see in the screenshot I posted before.
In recent versions of DC (up to 0.510.1) I never had this problem!

**Comment by r10s** [comment] 2019-12-18 10:01
> Might it be a problem to have various versions of DC installed on the same device?

no this should not be a problem, however, for now, i am out of ideas here :)

**Comment by gitgerardo** [comment] 2019-12-18 11:53
Schade...
Ah , I tried out with ox coi : there pdf files are opened like expected ! May be interesting  for you .

**Comment by r10s** [comment] 2019-12-18 12:25
as mentioned, there are several way for sharing. might be that coi shares over a file - this is sth. we do not want to do for security reasons.

but it is a bit weird that the "Document Viewer" does not work for your setup, this is the one i always recommend and that is virtually always working :) i think it might be worth trying out xodo - we need sth. where we can reproduce the issue.

**Comment by r10s** [comment] 2019-12-18 12:26
@cyBerta did we change sth. between 0.510 and now that could produce this change?

**Comment by gitgerardo** [comment] 2019-12-18 13:01
> as mentioned, there are several way for sharing. might be that others shares over a file - this is sth. we do not want to do for security reasons.
> 
> but it is a bit weird that the "Document Viewer" does not work for your setup, this is the one i always recommend and that is virtually always working :) i think it might be worth trying out xodo - we need sth. where we can reproduce the issue.

Not only PDF opening is not working.
Same happens with DOCX files.

**Comment by webratte** [comment] 2019-12-18 13:38
Maybe v.0.510 dosn't use the rust core yet?

https://github.com/deltachat/deltachat-desktop/issues/1190 is fixed in the newest desktop version.

But not in the current OX-Coi version..

So I believe it's related to the core.

Just a idea.

**Comment by gitgerardo** [comment] 2019-12-18 16:24
> as mentioned, there are several way for sharing. might be that others shares over a file - this is sth. we do not want to do for security reasons.
> 
> but it is a bit weird that the "Document Viewer" does not work for your setup, this is the one i always recommend and that is virtually always working :) i think it might be worth trying out xodo - we need sth. where we can reproduce the issue.

Not only PDF opening is not working.
Same happens with DOCX files.

**Comment by gitgerardo** [comment] 2019-12-18 16:27
![Screenshot_20191218-172549_Delta_Chat](https://user-images.githubusercontent.com/33866993/71104115-93c53f80-21bb-11ea-811a-37a675ca1230.png)

**Comment by gitgerardo** [comment] 2019-12-18 16:32
[deltachat-log-20191218-173053.txt](https://github.com/deltachat/deltachat-android/files/3979439/deltachat-log-20191218-173053.txt)

**Comment by gitgerardo** [comment] 2019-12-20 10:27
> as mentioned, there are several way for sharing. might be that others shares over a file - this is sth. we do not want to do for security reasons.
> 
> but it is a bit weird that the "Document Viewer" does not work for your setup, this is the one i always recommend and that is virtually always working :) i think it might be worth trying out xodo - we need sth. where we can reproduce the issue.

If I open a PDF with DC 0.501.1  **it is automatically  downloaded to my download folder**.

**Closed** 2019-12-20 14:51 UTC
Labels: bug

**Comment by gitgerardo** [comment] 2019-12-20 14:58
👍
Thanx

**Comment by r10s** [comment] 2019-12-20 15:38
@gitgerardo thank you very much for reporting and in assisting fixing the bug!

**Comment by gitgerardo** [comment] 2019-12-20 15:44
I have been using Delta Chat since the beginning, so it is in my interest ... There is no news about my notification problem?
