### ISSUE TITLE
add badge counter

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#962] opened 2019-06-18 22:17 UTC
Since upgrade from v0.200.0 to v0.304.0 I see no new message counter any more beside DC icon at base screen.
In the version before I saw a small orange bubble which indicates the number of new messages.
This is gone away.

**Comment by r10s** [comment] 2019-06-20 22:12
might be optimized-away due to the notification-cleanup. 

in fact, samsung/moto/whatever had their own, different apis in the past which resulted in a lot unmaintainable code (and iirc in telegram also to the behavior of _wrong_ numbers)

since android8 or so these numbers are supported natively. I think this way should be supported by delta chat, however, not sure what the state is here. 

@cyBerta do you have more information here?

**Comment by r10s** [comment] 2019-06-27 12:57
@cyBerta maybe you can have a look at this after the release

**Comment by csb0730** [comment] 2019-07-08 22:11
@cyBerta @r10s 

Maybe some hints from compare sources of 0.200.0 and v0.304.0 ++

I found that code around badges in ../notifications/MessageNotifier.java has been deleted.

`import me.leolin.shortcutbadger.ShortcutBadger;`
is missing.

Two calls of update function is missing:
```
updateBadge(context, 0);
...
updateBadge(context, notificationState.getMessageCount());
```
And the function definition itself is missing:
 ```
private static void updateBadge(Context context, int count) {
    try {
      if (count == 0) ShortcutBadger.removeCount(context);
      else            ShortcutBadger.applyCount(context, count);
    } catch (RuntimeException t) {
      // NOTE :: I don't totally trust this thing, so I'm catching
      // everything.
      Log.w("MessageNotifier", t);
    }
  }
```

Could that be the reason for the missing badge?

**Comment by cyBerta** [comment] 2019-07-09 11:26
iirc the counter increased or set to 0 but was never read - that's why I've refactored that away.

**Comment by cyBerta** [comment] 2019-07-09 11:34
@csb0730 can you give a screenshot? I'm even not sure if I understand where the badge counter is missing. I assume you don't mean the green bubble on the right side of each unread chat in the chat list, right?

**Comment by r10s** [comment] 2019-07-09 12:39
it's about the count on the icon on some android desktops (as on ios). at least in the past, there was no android-api for that and samsung/lt/etc. provide some proprietary api that seems to be used by delta chat in the past - without knowing, this might have gone.

however, if the badge counter is _just not there_ as usual on android, i would not regard this with high priority. maybe we can support this some time later, currently, there are much "larger" issues with the notifications.
(if the badge counter is _wrong_, however, this should be fixed)

**Comment by csb0730** [comment] 2019-07-10 14:07
This is a screenshot which explains:
![Screenshot_2019-07-10-no badge](https://user-images.githubusercontent.com/30560716/60975538-7054b980-a32c-11e9-8943-6a3b676e9135.png)

Every instance of DC has a new message here. The one which shows the badge is v0.200.0, the other one is short before 0.500.0 release.

You see the two small delta's at the top of the screen. This indicates new messages in system alert area.

**Comment by csb0730** [comment] 2019-07-10 14:10
I propose to let the old functionality in, until another solution is found. That's the easiest way to keep the functionality (I don't know how many users are affected by this issue here).

**Comment by csb0730** [comment] 2019-07-10 14:28
@adbenitez 
I think You have the same old Android 4 than me. Do You see a badge indicating new messages with current version or not?

**Comment by webratte** [comment] 2019-07-13 07:07
For me, 
Android 7.0 on Huawei nova, 
it also doesn't work .

DC version 0.510.1

**Comment by adbenitez** [comment] 2019-07-14 00:04
csb0730, I now have an old Android 4.4 phone could try but some users already told me this feature is gone

**Comment by csb0730** [comment] 2019-07-15 10:09
That seems for me, that really "ShortcutBadger" is the reason for this feature is gone way.

In reality I notice, that I send messages to my friends and I often got the answer: "Didn't see any new message!". But when checking together afterwards: It's there!

==> They don't notice an alert any more!

On the other hand, If I see the small alert area of some phones of my friends: The small _delta_ is only hard to see between many other alert symbols there!

IMO we should re-implement the ShortcutBadger again.

As long as we don't have it, DC feels in some way unreliable :-/

**Comment by adbenitez** [comment] 2019-07-15 21:18
delta has troubles with notifications,I am getting complains of several users about missing notifications since no sound was played randomly, and that they don't get the badge was also reported
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by csb0730** [comment] 2019-08-03 08:46
Hi guys,
the code changes seem reasonable for me. When the PR is included in code I would check and close this issue.
I think it's solved now, but I can't verify. When the PR will be applied?

**Comment by r10s** [comment] 2019-08-03 09:16
@csb0730 there is no need to wait for merging, you can check out the code using `git checkout shortcutBadger` - a regular release will take a little more time as we're currently focusing on other things (also, there are holidays everywhere :)

**Comment by csb0730** [comment] 2019-08-12 20:33
PR #1010 works as expected :+1: 

@cyBerta, good job :+1: 

Now only pr has to be merged to master :-)

**Comment by webratte** [comment] 2019-11-24 18:55
Is there a chance to see the badge counter on the starter icon in the next version?

**Comment by r10s** [comment] 2019-11-25 09:54
probably not in the next version. the notifications need some refactoring before, adding complexity does not help on that.
also, by some refactoring, so called "notification dots" ([random link](https://www.howtogeek.com/324124/how-to-enable-or-disable-notification-dots-in-android-8.0-oreo/)) might be supported for android-oreo or newer, i think, this is more the way to go and will probably come with less maintenance effort.

**Comment by r10s** [comment] 2019-12-22 14:53
yip, verified that, starting with android8, there will be notification dots, once we rework the notifiy things, they will be supported. i file an explicit issue for that, closing this once.

**Closed by r10s** 2019-12-22 14:53 UTC
Labels: feature proposal, notify

**Comment by csb0730** [comment] 2020-01-07 14:46
All my friends complaint about DC is not showing new messages,(not reliable). Some of them are using a second mail app meanwhile to detect new messages!   What a pity!
All Android versions from 4 to 10 are affected.

cc @r10s @webratte @adbenitez @hpk42 @cyBerta 

IMHO this issue (or new one) should be reopened and existing PR from cyBerta should be included in current version until a better solution is available.

**Comment by r10s** [comment] 2020-01-07 15:32
> All my friends complaint about DC is not showing new messages,(not reliable)

but these are other issues that are targeted, see eg. https://github.com/deltachat/deltachat-android/issues?utf8=✓&q=is%3Aissue++label%3Anotify+

**Comment by csb0730** [comment] 2020-01-09 14:58
> > All my friends complaint about DC is not showing new messages,(not reliable)
> 
> but these are other issues that _are_ targeted, see eg. [https://github.com/deltachat/deltachat-android/issues?utf8=✓&q=is%3Aissue++label%3Anotify+](https://github.com/deltachat/deltachat-android/issues?utf8=%E2%9C%93&q=is%3Aissue++label%3Anotify+)
> 
@r10s excuse but I think I described the issue not correctly! :-/

Messages are arriving at DC but friends can't see it because of the missing badge counter at start screen icon. They need to open DC manually to see if there is a new message. In practice they don't do that and waiting and waiting in spite of new messages are there meanwhile!

**Comment by adbenitez** [comment] 2020-01-20 19:45
hello, the message counter is show along with a notification, if your friends are not getting the system notification (maybe they disabled it because it is a bit annoying/obtrusive) that explain why they are missing the messages, but in my personal case, I don't expend my time going to the home screen to see the delta chat icon is badge, I know when I have new messages because a notification with a sound is issued showing that I have a new message, maybe the issue is your friends "muted" some chat group? so they are not notified?

**Comment by csb0730** [comment] 2020-03-27 23:27
Hi adbenitez,
my friends most of time have their phone not with them so they don't hear any sound most of times. Additionally they use other apps and whatsapp too, so they don't have DC open in standard case.
From time to time they have a look at home screen to check the badges. Whatsapp provides this and so they are waiting for a badge at DC too ... but it will not come!

That's what I see as the use case.

**Comment by adbenitez** [comment] 2020-03-28 05:50
I get the badge, and also a notification in the top bar, your friends don't see the notification?

**Comment by adbenitez** [comment] 2020-03-28 05:55
@csb0730 if your friends don't get a notification, that means delta chat doesn't know they have new messages (delta chat was killed by the system for example and isn't checking the inbox) in that case how could the app show a badge counter? if the app know there are new messages, it will display a notification in the top bar, and you see also the delta chat icon, so badge counter is not really necessary IMHO, with the notification you know that you have new messages, I think what is happening to your friends is that the app is not working in the background

**Comment by csb0730** [comment] 2020-03-29 21:59
Hi @adbenitez 
please see picture at my comment from 10 Jul 2019.

My friends get new messages in DC and see the small delta sign at black top notification bar.

The problem is, that they have many small notifications at top bar from other apps so they don't notice delta's badge.

The orange badge counter at delta's icon is much more clear for them and they notice the badge immediately. Especially keep in mind, that most of my friends use WhatsApp too and WA shows such an orange counter. So they are waiting for it from DC too. You know?

But by the way: We had it in the past, why don't have it again? It's only a small tweak in app. PR is (has been) existing.

**Comment by csb0730** [comment] 2020-03-29 22:01
In my personal build I have it (by the way).

**Comment by webratte** [comment] 2020-03-30 04:15
I absolutely agree.
I also would like to have the badge counter.

**Comment by adbenitez** [comment] 2020-03-30 20:10
please, I have said it several times: I have the badge counter!!! it works!!! at least in my Android 9 (Samsung Galaxy 10)

**Comment by csb0730** [comment] 2020-03-30 23:58
I suspect that Android 4 - 7 (or even 8) doesn't provide a badge without the PR

**Comment by webratte** [comment] 2020-03-31 04:16
I agree also in this point.

My phone with Android 7 and also my test phone with Android 9 dosn't provide a Badge counter.
