### ISSUE TITLE
German Umlaut not displayed correctly

### ISSUE THREAD

**Issue by Offerel** [deltachat/deltachat-android#1043] opened 2019-09-29 19:12 UTC
- Platform (android/blackberry/anbox): Android
- Device: Samsung Galaxy S9
- Delta Chat Version: F-Droid
- Expected behavior: German Umlauts are displayed correctly
- Actual behavior: German Umlauts are displayed as ?
- Steps to reproduce the problem: receive a text with german umlauts
- Screenshots:
- Logs:

Workflow:
- Send a message to some user
- User or better the exchange Server of the user responds with auto-away message
- message contains  german umlauts
- umlauts are displayed as ? - sign

**Comment by r10s** [comment] 2019-10-28 14:33
i cannot reproduce this.

> Steps to reproduce the problem: receive a text with german umlauts

does this also happen from deltachat to deltachat?
otherwise it might be the message sent is already malformed.

for reproducing, we would need a message-source-file (*.eml containing the raw mail) that you can download eg. via thunderbird.

**Comment by Offerel** [comment] 2019-10-28 14:54
Currently I can't reproduce that either. All characters are displaying correctly. However at the time this happened, umlauts are not correct in deltachat, but the same mail displayed correctly in M$ Outlook and emClient.

**Comment by r10s** [comment] 2019-10-28 15:08
@Offerel okay, thanks for coming back to that.

so i close this for now. feel free to reopen when you come over the issue again and/or when you have additional information.

**Closed by r10s** 2019-10-28 15:08 UTC
Labels: needs-retry
