### ISSUE TITLE
Notifications not visible when using multiple accounts

### ISSUE THREAD

**Issue by frankiezafe** [deltachat/deltachat-android#2150] opened 2021-11-26 14:06 UTC
- Android version: LineageOS 14.1
- Device:LG Spirit 4G LTE
- Delta Chat version: 1.20.5
- Expected behavior: receive notifications for ALL connected accounts
- Actual behavior: receive notifications only for selected account
- Steps to reproduce the problem: link 2 accounts in the client, activate account A and send an email to account B
- Screenshots:
- Logs:

**Comment by r10s** [comment] 2021-11-26 14:31
this is by design currently, notifications arrive for the selected account only.

there are also people expecting it to work in exactly that way :)

changing that is possible, however, a bit of work. 

as this is a feature request, i suggest to close this issue and to open a feature request in the forum at https://support.delta.chat/c/features/6 - that way, it also becomes visible in a cross-platform way,

**Comment by frankiezafe** [comment] 2021-11-27 16:25
it makes sense, i propose to let user decides if s.he enable notifications for inactive accounts
is there already a topic about this in support.delta.chat? can not find it...

**Comment by r10s** [comment] 2021-11-27 23:42
> it makes sense, i propose to let user decides if s.he enable notifications for inactive accounts

yip, sth. like that will come likely at some point.

> is there already a topic about this in support.delta.chat? can not find it...

just create a new one - you can log in with your github account there.

**Closed by r10s** 2021-11-27 23:42 UTC
