### ISSUE TITLE
Search function very slow on dev-version, Android 4, S3 mini

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#868] opened 2019-04-23 23:23 UTC
v0.200.0, Android 4.1.2, S3 mini

Search function in chat view is very slow and unresponsive. IMHO much much slower than in old 0.20.0 !

Example:
I'm searching for a chat in chat list by entering first four characters in search input field.
Then:
1. after approx 10s (!) first results appear which shows 65 chats affected (strange!), then
2. after another approx 20s last results appear (2 chats and 4 mails; end result).

While searching time UI and phone is quite unusable.

Are there any changes in search functions since 0.20.0? I mean there was an issue in 0.20.0 regarding unresponsive UI but in 0.20.0 search was not done in separate thread.
With current 0.200.0 again search function get's much slower again :-(

Any idea? Are there several searches started in parallel with every next character typed?

**Comment by csb0730** [comment] 2019-04-27 23:54
Have a first approach:
Identified search functions in _chatlist.c_ `dc_chatlist_load_from_db()` and _context.c_ `dc_search_msgs()`.
Activated `dc_log_info()` in `dc_chatlist_load_from_db()` again.
In both functions a text query is used which starts search query with - every - char typed. Even with first char! 

My first approach is to start search with 3rd char, not with 1st. This shows a significant speedup of search function :)

**Comment by csb0730** [comment] 2019-04-29 23:35
See https://github.com/deltachat/deltachat-android/issues/296

The problem itself about overloading the device with unnecessary searches is still existant.

My 2nd approach now is: start search in chatlist with 3rd char (`dc_chatlist_load_from_db()`) and full text search (`do_search_msgs()`) with 4th char typed.

This makes search function much more responsive, gives response for contacts quite immediately and starts slow full text search later.
IMHO this makes sense because my standard use case for search function is finding contacts in huge chat list. Not full text search in msgs.

Maybe is would be an approach too, to separate full text search from contact and chat search.

**Comment by csb0730** [comment] 2019-05-01 22:34
@adbenitez 
You know many users with old mobiles. Are there no experiences about?

**Comment by adbenitez** [comment] 2019-05-01 23:50
Dear Christian Schneider,
I have  a pretty close friend that have a crappy phone: myself ;) 
my phone has like 450MB of RAM and android 6.0
I have more than 360 contacts, currently more than 190 chats, and more than 27000 chat messages,
If I search the letter "a" I get matching:
194 chats
284 contacts
23684 messages
I get te result instantaneously, maybe in 1 second.
So maybe the issue is related to Android versions because my phone is pretty slow, it gets slow even when dc is sending a message but the search is pretty fast, btw I did the test using Delta Chat 0.301.1

hope this help,
Regards,
adb
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by r10s** [comment] 2019-05-02 09:32
i also think this is more an issue of the os/hardware combination. in general, the search may take a second, however, as started in a working thread, it should be interrupted by the "back" button or by entering a new search term (which included the next letter).

i also have > 30K messages and get results within a second or so.

of course, it can be improved, however, compared to 0.20 it is much faster on my test phones - as the old version did not use threads for the search.

one reason for the slowness: did you tried the search in a self-compiled version or did you use a dev-version? these versions might contain debug code which slows down things often by factor 20 or so.

**Comment by csb0730** [comment] 2019-05-02 13:53
First the basics:
The version I use is compiled from the sources downloaded from github (+changes for imex backup).
In Android Studio it is a so called fat-debug version.
My current used sources are at level 0.200.0 (dc android) and 0.42.0-dev (core).

 number of chats=181
 number of chat messages=7449
 number of contacts=437
 database version=54

All my experiences seems strange to me if I see your experiences about it !
Even in v0.20.0 search was slow (@r10s you know, I opened an issue about).

If I see your experiences I suspect here a problem with an index in database or as r10s assumes some debug code which slows down the code extremely.

The question is: How can I get it? What to check?

Switch in Android Studio to release version (But we had discussed that in the past not to be an issue) or some build switches for the core (ndk-build)?

**Comment by csb0730** [comment] 2019-05-02 13:54
Shall I post a log?

**Comment by r10s** [comment] 2019-05-02 14:11
in fact, there might be an index missing in your concrete database.
may come after some development tries, unstable versions etc.
probably, after some export and imports its still the same database file from 0.20 up to now.

so, from my point of view, it's not really worth putting much development effort on this, i assume a "normally" created database will be fast (enough).

you can post an log here, however, as there is nothing concrete to do and as it is probably only reproducible on your machine, i will close it for now.

**Comment by r10s** [comment] 2019-05-02 14:15
please also note that there are _huge_ differences in performance between debug and release versions. i also run into this trap several times; it's not just "half slower", esp. on old devices it may be factor 10 or 20 or even more.

(i am also using a quite old device, a nexus 4 from 2012 btw. - it's as old as the s3 mini)

**Comment by adbenitez** [comment] 2019-05-02 23:11
I am using also a fat debug so it isn't that

On May 2, 2019 9:53:24 AM GMT-04:00, Christian Schneider <notifications@github.com> wrote:
>First the basics:
>The version I use is compiled from the sources downloaded from github
>(+changes for imex backup).
>In Android Studio it is a so called fat-debug version.
>My current used sources are at level 0.200.0 (dc android) and
>0.42.0-dev (core).
>
> number of chats=181
> number of chat messages=7449
> number of contacts=437
> database version=54
>
>All my experiences seems strange to me if I see your experiences about
>it !
>Even in v0.20.0 search was slow (@r10s you know, I opened an issue
>about).
>
>If I see your experiences I suspect here a problem with an index in
>database or as r10s assumes some debug code which slows down the code
>extremely.
>
>The question is: How can I get it? What to check?
>
>Switch in Android Studio to release version (But we had discussed that
>in the past not to be an issue) or some build switches for the core
>(ndk-build)?
>     

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by csb0730** [comment] 2019-05-03 10:55
My strongest assumption is that there is an index problem in my database, but I'll see :-/

As I have two DCs on my phone I'll compare the databases.
I have (a) the production version which has been upgraded since two years now from version to version and (b) a new installation for testing. Both the same sources.
In principle the database structure of both versions should be identical.

But the quicker way would be compiling a release version, but how to do that? One hint for that problem is that DC in general feels not very responsive.
@r10s can You give me a hint?

**Comment by csb0730** [comment] 2019-05-04 23:50
@r10s @adbenitez 

My first findings:
1. To disable debugging code I added `debuggable false` in debug section of build.gradle and rebuild the project. And really this new version is more responsive than before :)  But the search problem was unchanged.
2. Examining the database by checking with `pragma integrity_check`. This shows an OK result.
For that check I used the old database format which keeps the structure I still use.
3. Examinging the indexes: There is no index for message text or similar.
4. Examining log about search functions:
 Found that full text search at my phone has a duration of around 4-5s.
 Found strange behaviour which shows that several calls of search functions run in parallel (!)
 This is not to see if You try only one text and wait. I saw this not until I tried two different texts quickly one after one (!).
 See log (start at 23:05:12):
[dc-log-0504-2305-slow-search.txt](https://github.com/deltachat/deltachat-android/files/3144962/dc-log-0504-2305-slow-search.txt)
Maybe there is a missing locking in code?

(See remark at beginning of the file. Search functions are not starting with 1. character. Therefore very quick results at beginning)

**Comment by r10s** [comment] 2019-05-05 00:07
hm, there is a debouncer that should prevent multiple searches being executed at the same time, see https://github.com/deltachat/deltachat-android/blob/91be337fb68cb75712c64a3d01b94409329af675/src/org/thoughtcrime/securesms/util/Debouncer.java

not totally sure if all this works 100% and maybe it can be faster in a way, however, in general it seems to work. would be interesting if on your device a "play store" or "f-droid" apk works.

**Comment by csb0730** [comment] 2019-05-05 00:27
Yes that would be interesting but not so easy, because I cannot import my current database with old method any more :-(
And I think with a small database You don't see that problem at all.

But some thoughts:
1. search is still much slower than at your phone: Why? Indexes are all there and ok, but for message text itself, there is no index. Would that help to add one?
It seems that your phone is simply quicker than mine ;-)
2. isn't it a job from the core to secure a proper handling of the queries (sync)? I mean, the core does the query, not the UI. I could add a sync variable for testing!
Maybe with that a phone freeze could be prevented?

In any case: the slower the phone the less queries should be raised to speed up results.

Will think about best approach ...

**Comment by csb0730** [comment] 2019-05-05 00:39
Debouncer is useless because even first searches are slower
that value used!
This value is used at v0.200.0 `this.debouncer        = new Debouncer(150);

Will increase that value tomorrow. I think this will help in some way, but not speed up full text search.

**Comment by csb0730** [comment] 2019-05-06 23:31
Increased Debouncer from 150ms to 1000ms. This delivers much better results :-)
With that I can take out "defer search until min. 3/4th characters given" approach with relative good results.

A value of 600ms gets back again some freezing behaviour.

I'm trying various approaches for mitigating/optimize search behaviour and will post some logs soon.

**Comment by csb0730** [comment] 2019-05-06 23:33
@r10s We should open this issue again and mark it accordingly (Optimize UX) ?.
Please assign it to me.

**Comment by r10s** [comment] 2019-05-07 10:05
did so :)
thanks for investigate further - as mentioned on irc, you have the perfect testing device :)

**Comment by csb0730** [comment] 2019-05-13 21:40
Played around with some tweaks (debouncer, start search not with first char, separate quick search in contacts from slow full text search).
All this mitigates the UX but at the end it's not the best solution. At the end full text search disturbes my phone more or less. If I tap quick enough to the first upcoming contacts I'm able to choose that, but later most of time phone freezes for some seconds by full text search. 

I think we have two different use cases:
1. searching for specific chat and/or contact
This is used when chatlist is very long and you need to find quickly a chat which is really not at the top of the list or when forwarding a message. Used very often.
It's very annoying when this needs more time. Fortunately this search is very quick already. So no problem :-) 
2. searching for pattern in full message pool (full text search)
This used not so often and I think in this case it's ok when search consumes some seconds until results are coming. Sometimes You'll get hundred of messages anyway.

The bad UX is coming up only when mixing both search types. This slows 1. unnecessary.
Case 1. means control of user interface. Would expect that this is always as quick as possible.
Case 2. means really starting a big search operation. Would expect some seconds to run.
 
So the best approach seems to me to separate both search types. User should decide what he wants to do.

This is the first outcome.

**Comment by csb0730** [comment] 2019-05-13 21:54
So now how to let user decide?
1. using short and long tap onto search symbol could switch to the desired mode.
Unfortunately I've not the knowledge in the moment to use and try that :-(
For me that seems to be the best approach.
2. using a control character. For example "/" which is able to switch search mode.

I made some trials with option 2. with very good results. But unfortunately I found, that something filters input string for desired character(s). I think it's not in c code. At the end I used charater "x" to do the tests.
This is my current state and works fine :-)

Need some hint's for short/long tap and filtering to come to a "round" solution now.

**Comment by violoncelloCH** [comment] 2019-05-14 13:10
I don't think that it makes for a good UX if one has to know a long tap on the button or a special char triggers full text search... Most users will probably just never detect that there ix a full text search...
From a UI perspective the best thing would be to run the slow search in a second thread in a way it doesn't freeze... But it's okay that it takes some time until results come up there...
What I mean is: Is there no way to have the chat / contacts filtering as quick as we have it and after that's done a second thread with the fulltext makes searches while the UI presents a loading spinner Indicating there will pop up more results below the filtered contacts...?

**Comment by r10s** [comment] 2019-05-14 15:40
yip, i also thinkg a long tap is nothing we should go for.

> From a UI perspective the best thing would be to run the slow search in a second thread in a way it doesn't freeze...

well, this is the intention of the current code - and it works at least on devices i have around here and improvements should follow this direction. also, iirc, it is still unclear if the issue @csb0730 has isn't related to a corrupted database (might result from testing versions or so). would be interesting if the issue on the device also appears with a "fresh" delta chat installation (without importing a backup)

**Comment by csb0730** [comment] 2019-05-16 00:24
Any idea is good to reach the goal. But what I can say is:

With a new installation I see no delay if starting search with current approach. All results are there immediately: chats, contacts, messages.
But this doesn't reflects reality. In this case I have a very small database. Only some few test messages and chats.

Some thoughts:
1. In my productive installation I have a message db of around 150MB with 7000 messages. For me it's not unusual if a full text search (without index) onto that needs 4-5s, isn't it?
2. When doing a backup (which I did several times) dc runs a vacuum first before doing the backup.
This is building all data structures from scratch in a new file. So this will provide a fresh database anyway.
3. to see what dc really does with a fresh installation we need to have a fresh database with all old data into that db. As I explained in 2. vacuum exactly does this. See sqlite documentation.

Another try:
What I did last days: Using the control character "/" for switching search method. Unfortunately I can't get this character later in core! Has anyone of you an idea how to get that?

**Comment by r10s** [comment] 2019-05-16 11:51
would be interesting if the new-install-fast-database also gets slower as more messages come in. in fact, i have about 29000 messages on a pretty old nexus 4 from 2012 and the search is fast enough (less than, say, 1s)

**Comment by csb0730** [comment] 2019-05-16 14:11
I'll think about a way to get the new database filled with my old messages. Copy them in some way?
Don't know, but will see.

But on the other hand if you would see how fast my device is,  You would believe me ;-)

Do You have an idea how to tunnel the "/" by the text field to the core ?

**Comment by csb0730** [comment] 2019-05-20 23:00
All tries to find the code where special chars like "/#$&" are filtered out ended without success :-(
I examined in detail all the related .xml .java and .c sources.
Any assistance is very welcome.
@r10s - are you able to give me a hint or an idea?

**Comment by csb0730** [comment] 2019-05-20 23:24
On the other hand I examined the database itself.

Found that structure and indexes are all existing and integrity check was Ok.

But,
 I found some datasets in msgs where txt size is much bigger than 1MB (9x size of txt > 4MB, 1x size of txt > 8MB) !!!
Some old messages with uuencoded content. 22 in summary (54MB of data in txt column only)!
Database size is 166MB now.

Made some performance tests with that database at PC with following simple statement:
`select * from msgs where txt like "%baum%"` (one of my testing pattern).
Result: 22 rows in **650ms** found.

Then deleted all these big txt messages
Result: 22 rows in **85ms** found !!!

Then did commit and vacuum:
Database size drops to 37MB.
But search result stays at around 85-100ms with the given query.

Outstanding test is now the real test at phone hardware ...

**Comment by r10s** [comment] 2019-05-21 00:24
thats pretty good, i think :)

in general, maybe the core should avoid to get too long texts into the raw field, afaik it is truncated for displaying, but not on insertion. the txt_raw can then contain the untruncated text, which, however, is not searched.
in the long-run, however, maybe we switch to a "real" fulltext search.

**Comment by r10s** [comment] 2019-05-25 12:51
okay, now that we have the cause of the problem, we can close this here, there is nothing android can really do about that.

to track the idea of truncating long messages in the core, i've created https://github.com/deltachat/deltachat-core/issues/686

**Closed by r10s** 2019-05-25 12:51 UTC

**Comment by csb0730** [comment] 2019-05-27 23:02
Hi @r10s  I think it's ok to close that issue now and we can use it as a knowledge base for future use.

- I deleted the big messages at the devices messenger.db file (export/modify/import) and the database size decreases dramatically from 166 down to 40 MB !
- Full text search is now around 500ms or even quicker so that's absolutely ok :-)

But I think, the core has (had?!) a fence against very big messages. You imagine about uuencode issue? You introduced a max message size of 30000 bytes. I didn't checked that now but it still should be there?

**Comment by csb0730** [comment] 2019-05-28 23:15
@r10s 

One last thing:

To attack slow search with big data in txt I tweaked SQL query. This works very efficient too and
prevents search from slow down efficiently :-)

See code snippet (<==== this line added): 

	else {
		int show_deaddrop = 0;//dc_sqlite3_get_config_int(context->sql, "show_deaddrop", 0);
		stmt = dc_sqlite3_prepare(context->sql,
			"SELECT m.id, m.timestamp FROM msgs m"
			" LEFT JOIN contacts ct ON m.from_id=ct.id"
			" LEFT JOIN chats c ON m.chat_id=c.id"
			" WHERE m.chat_id>" DC_STRINGIFY(DC_CHAT_ID_LAST_SPECIAL)
				" AND m.hidden=0 "
				" AND length(m.txt) < 10000 "             <===== this line added
				" AND (c.blocked=0 OR c.blocked=?)"
				" AND ct.blocked=0 AND (m.txt LIKE ? OR ct.name LIKE ?)"
			" ORDER BY m.timestamp DESC,m.id DESC;"); /* chat overview starts with the newest message*/
		sqlite3_bind_int (stmt, 1, show_deaddrop? DC_CHAT_DEADDROP_BLOCKED : 0);
		sqlite3_bind_text(stmt, 2, strLikeInText, -1, SQLITE_STATIC);
		sqlite3_bind_text(stmt, 3, strLikeBeg, -1, SQLITE_STATIC);
	}
