### ISSUE TITLE
Delta Chat does not receive any messages on Android 7.1.2 Nougat after v1.6.2 update.

### ISSUE THREAD

**Issue by ChrisPHL** [deltachat/deltachat-android#1352] opened 2020-05-11 20:34 UTC
Delta Chat does not receive any messages on Android 7.1.2 Nougat after v1.6.2 update.

- Android version: 7.1.2 / LineageOS 14.1
- Device: Moto G4 athene and Moto G3 osprey
- Delta Chat version: 1.6.2
- Expected behavior: Receive an incomming message
- Actual behavior: No message received. (No battery optimization active.)
- Steps to reproduce the problem: 
- Screenshots:
- Logs:
[deltachat-log-20200511-221742.txt](https://github.com/deltachat/deltachat-android/files/4611924/deltachat-log-20200511-221742.txt)

**Comment by r10s** [comment] 2020-05-11 20:49
thanks for reporting - and sorry for the troubles.

the issue is there because of one badly formatted message from somewhere in the INBOX - however, of course, Delta Chat should also handle such messages and did that also in the past, it was just a bug :/ 

however, the bug is already fixed in 1.8.0 which is already pushed to google play and should be available soon (or already now :)

see https://github.com/deltachat/deltachat-core-rust/issues/1461 for details.

**Comment by r10s** [comment] 2020-05-11 20:50
although fixed, we can keep it open a few days, maybe others stumble upon the same issue.

**Comment by elovin** [comment] 2020-05-12 07:19
@r10s Thanks for the quick fix, when will it be available in the F-Droid store ?

**Comment by Hocuri** [comment] 2020-05-12 08:43
> when will it be available in the F-Droid store ?


probably in some days. F-Droid updates usually take a bit longer than
GPlay because someone of the F-Droid guys has to manually pick up the
updates and publish it (to improve security).

**Comment by AndreazLattmann** [comment] 2020-05-14 20:29
For now it seems that all the messages are coming.
I am using Delta Chat 1.8.1

**Comment by r10s** [comment] 2020-05-14 21:35
@AndreazLattmann great, thanks for reporting. i think we can close this issue then :)

**Closed by r10s** 2020-05-14 21:35 UTC
Labels: bug
