### ISSUE TITLE
Multiple pastings via sharing 

### ISSUE THREAD

**Issue by playforvoices1** [deltachat/deltachat-android#2054] opened 2021-09-21 05:57 UTC
I get an issue when I want to share a link or pictures. The link (or picture) will paste multiple times into the relevant chat. Currently, it happens randomly. 

It happens with DC version 1.22.1 on Sony Xperia 10 II and Samsung S8 both with recent version of DC and system updates.

**Comment by webratte** [comment] 2021-09-21 18:40
I can confirm this behaviour on my Nokia 5.3 Android 11

Steps to reproduce:
- choose a file in your file manager
- choose share
- choose DeltaChat
- press send

Now the message wil sent.
But the same message will arrive as a draft.

For me the only way is to close the app via "brute force".
After a new start I can delete the draft.

**Comment by gerryfrancis** [comment] 2021-09-24 20:26
Duplicate of https://github.com/deltachat/deltachat-android/issues/2040 .

@r10s Shall we keep this one open or close it?

**Comment by r10s** [comment] 2021-09-25 09:26
let's close duplicates, once they are references (as here), they are easily accessible in the original issue.

**Closed by r10s** 2021-09-25 09:26 UTC
Labels: bug, duplicate

**Comment by gerryfrancis** [comment] 2021-10-05 10:22
@playforvoices1 The issue should be fixed in the next version of Delta Chat.
