### ISSUE TITLE
Wrong avatar in notification

### ISSUE THREAD

**Issue by anaskaejdar** [deltachat/deltachat-android#2611] opened 2023-07-01 16:18 UTC
- Android version: 13
- Device: Galaxy S22
- Delta Chat version: 1.38.2 (DeltaLab)
- Expected behavior: No avatar would be displayed.
- Actual behavior: Sometimes— _only_ sometimes, though very frequent— a message from an avatarless non-contact arrives, only to have one of my friends' pictures put next to it. It doesn't make sense to me. See the screenshot: my friend and his wife next to a car wash bulk mail. Makes no sense to me.
- Steps to reproduce the problem: I don't know
- Screenshots: 
![Screenshot_۲۰۲۳۰۷۰۱_۰۹۰۹۳۶_Neo Launcher](https://github.com/deltachat/deltachat-android/assets/32847759/763c009e-e843-4877-bedb-f5a2819541f8)

- Logs:

**Comment by adbenitez** [comment] 2023-07-13 11:02
mmmh weird, could you perhaps provide a log when this happens again, or does it always happens? what happens when you touch the notification? do you land in your friend's chat or in other chat? does that chat has the avatar of your friend?

**Comment by anaskaejdar** [comment] 2023-07-13 11:22
@adbenitez Sure, I'll try to grab a log for you! It doesn't happen all the time; I haven't figured out any pattern to when it does _happen_. When you click the notification, it lands you in the proper place (in this case, the car wash). Once inside DC, the thread is avatarless as it should be: 
![Screenshot_۲۰۲۳۰۷۱۳_۰۴۱۷۵۰_DeltaLab](https://github.com/deltachat/deltachat-android/assets/32847759/06ce0768-202c-4f7d-b104-fb78b611d7b7)

**Comment by adbenitez** [comment] 2023-07-13 11:25
> It doesn't happen all the time;

oh :( that makes it harder to debug and figure it out the source of the bug

**Comment by gerryfrancis** [comment] 2023-07-21 08:50
I believe this could be related to the RTL text flow that can be seen on the images. Obviously, Android prefers to position the app icon on the right of each notification, but we might not consider that in RTL. As a conclusion, I can think of wrong positioning/clearing of avatar images, resulting in a mess of the notification board.

**Comment by adbenitez** [comment] 2023-10-01 16:30
yes, I am also checking, there is a problem with multi-account for sure, but in the chat list, the notification should be fine,

for the chatlist I have seen some weird black chats avatars with # symbol, sometimes when clicking a notification, but also i don't have a reliable way of reproducing it, maybe related to the async loading of the chatlist in a thread

**Comment by adbenitez** [comment] 2023-10-01 17:08
created a PR for the chatlist part: https://github.com/deltachat/deltachat-android/pull/2694

closing here

**Comment by adbenitez** [comment] 2023-10-01 17:57
> #2694 is not related to notifications and cannot fix this issue.

I closed here because of lack of ability to reproduce, the linked PR is related in the sense that is also related to multi-account notifications issues and what I mentioned earlier, not that is solves this issue

but with your feedback I think now the source of the issue is clear thanks a lot! will create a PR

**Closed** 2023-10-01 20:29 UTC
Labels: bug
