### ISSUE TITLE
The preview-v0.910.0 version closes when I want to send a message.

### ISSUE THREAD

**Issue by JordanySutil** [deltachat/deltachat-android#1056] opened 2019-10-07 18:14 UTC

**Comment by r10s** [comment] 2019-10-07 20:11
can you please provide more information, your provider, a log etc.

**Comment by r10s** [comment] 2019-10-07 20:13
also: does it happen reproducible every time? also on a fresh account?

**Comment by JordanySutil** [comment] 2019-10-07 21:03
Regards, unfortunately I can not send the log, since the application closes when you access these options, my android is 5.0.1

**Comment by JordanySutil** [comment] 2019-10-07 21:08
A friend of mine, on Android 4.4 and Android 8.0, works fine, but on Android 9 it doesn't

**Comment by r10s** [comment] 2019-10-07 21:14
okay, thanks for reporting. maybe others have some more information (a log can be accessed using eg. the android-debug-bridge).

and the issue is only _sending_ plain text messages? receiving messages and other things work as expected?

**Comment by JordanySutil** [comment] 2019-10-08 11:17
[deltachat-log-20191007-224947.txt](https://github.com/deltachat/deltachat-android/files/3702096/deltachat-log-20191007-224947.txt)

**Comment by r10s** [comment] 2019-10-08 14:05
thanks, this is very helpful :) so we have the repeated error `SMTP failed len=2225: error: other os error` - this is logged here: https://github.com/deltachat/deltachat-core-rust/blob/master/src/smtp.rs#L159

@JordanySutil you wrote initially that the app "closes" - what exactly do you mean by that? does it go away? cause i cannot see some things to that in the log. however, this "closing" might also be another issue :)

**Comment by JordanySutil** [comment] 2019-10-08 14:42
Greetings, when you start a new chat, or access any option related to this, you do not receive, or send new messages and the application closes or stops, so you can not access "contact request" or new chat, in the application without performing new actions it works, that is it logs in, and the mail servers are configured, but it does not send or receive any

**Comment by Vistaus** [comment] 2019-10-10 19:40
Doesn't work for me either and crashes a lot.

OS: Android 8.1

**Comment by r10s** [comment] 2019-10-10 20:41
i think this is the same problem: https://github.com/deltachat/deltachat-android/issues/1061

**Comment by r10s** [comment] 2019-10-26 11:40
closing this for now. the assumed duplicated https://github.com/deltachat/deltachat-android/issues/1061 is fixed by https://github.com/deltachat/deltachat-core-rust/pull/736 

@JordanySutil if this issue here is still active in [0.930.2](https://github.com/deltachat/deltachat-android/releases), please reopen, at best with a fresh log.

**Closed by r10s** 2019-10-26 11:40 UTC
Labels: bug
