### ISSUE TITLE
webxdc app doesn't load if you tap it 2+ times very quickly

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-android#2546] opened 2023-04-19 15:10 UTC
- Android version:
- Device:
- Delta Chat version: 1.36.4
- Expected behavior: Only one instance of the webxdc app launches, no matter how many times I tap on it, and the app loads.
- Actual behavior: Two instances of the app get launched, and they both get stuck at 50%.
- Steps to reproduce the problem:
  1. Send a webxdc app to a chat
  2. Tap rapidly 2+ times (before the app window blocks the view so you can't tap it anymore)
- Screenshots:
- Logs:

Here's the code where the progress bar is updated:

https://github.com/deltachat/deltachat-android/blob/2611a677fc7ad000a8bc8a80234a7f3be9bfdf3d/res/raw/webxdc_wrapper.html#L67

**Comment by r10s** [comment] 2023-09-27 22:11
> Two instances of the app get launched

are you sure, really two instances get launched? [^1]

the behaviour you describes happens to me as well sometimes, however the reason was not two instances of the webxdc, but that FILL500 get stock sometime. the slower a phone is, the easier it is to get to that state. it could get to the issue also when eg. exit a webxdc quick and re-enter

[^1]: you can check this if if you hit "back" on the webxdc, you see a exit-animation and are in the same webxdc again. next "back" will bring you to the chat

**Comment by adbenitez** [comment] 2023-09-27 23:28
![image](https://github.com/deltachat/deltachat-android/assets/24558636/7d89fd6d-135f-4333-b7a1-26f74a082185)

this is what happens when you open and go back in the webxdcActivity, onDestroy() is called rather slowly when you are already back and the conversation, and if you open the app again fast, as you can see at the end of the logs, I managed to launch a new instance of the activity before the onDestroy() of the other one was called, so at the time the new one is running, the onDestroy() of the old one has not run yet, meaning that webxdc.destroy() has not being called yet so the fill500 is still in place

something like this might be what happened for wofwca

**Comment by WofWca** [comment] 2023-09-28 11:40
> are you sure, really two instances get launched?

Yes. There are two apps that I have to close.
If you have a fancy phone, try with two fingers XD

> but that FILL500 get stock sometime

Yes, it happens to me as well, I believe it's because the old instance's process doesn't get cleaned up in time and is reused by the new app launch.

**Comment by r10s** [comment] 2023-09-28 12:54
k, so there are two independent issues

1. FILL500 get stuck sometimes, when xdc are ended and restarted within a few seconds. there is not much we can do about that, the delay is part of the fix (@adbenitez tried to shift destroy-function around, but everything seemed to be optimal already)

2. fast tapping to start an activity two times - neither  @adbenitez nor me could reproduce this on our test phones or in any emulator - so, tbh, while totally believing that it can happen, not sure if that really is an in-the-wild issue - maybe it needs some animations disabled, two fingers, being very fast

in theory, there are fixes as [here](https://stackoverflow.com/questions/65856021/prevent-or-avoid-multiple-clicks-in-android-app-kotlin-language) possible, however, before adding that, with tradeoffs as maintaining or adding brakes where they are not needed, i would like to avoid that

regarding that 1. is the far larger issue (as it happens within seconds, not milliseconds), and we cannot even do sth. about that, i suggest to close this issue at least until it is reproducible by some dev or other users come back with the same complains

**Comment by WofWca** [comment] 2023-09-28 13:04
> not sure if that really is an in-the-wild issue

On my not-so-fast older phone it's entirely doable. In fact I discovered the issue in the wild.

**Comment by adbenitez** [comment] 2023-09-28 13:08
> On my not-so-fast older phone it's entirely doable. In fact I discovered the issue in the wild.

we modified the code to launch the activity twice with a single tap, even then, the activity is launched only once, (ex. the second launch kill the previous one) so it is impossible this is happening for you, unless it is different per android version

**Comment by adbenitez** [comment] 2023-09-28 13:11
could you record an small video reproducing the situation in your phone? also please tell us your android version because the activity stacking behavior is different depending on android version

**Comment by WofWca** [comment] 2023-09-28 13:24
> it is impossible this is happening for you

Based.
Here's proof tho

[webxdc-two-instances-android.webm](https://github.com/deltachat/deltachat-android/assets/39462442/b310474d-e301-409c-a26f-9624b18be10e)

Android 13, and the other is older, but it looks the same.

**Comment by r10s** [comment] 2023-09-28 14:33
just as i am trying to reproduce: the video looks as if you're using  two fingers, right?

**Comment by adbenitez** [comment] 2023-09-28 16:20
> Based.
> Here's proof tho

so the second part applies: "unless it is different per android version"

**Comment by r10s** [comment] 2023-09-30 20:34
> > animations are double time or so?
>
> WDYM? I have to close two apps if this is what you're talking about.

 i meant the animantion when opening the webxdc activity (this slide & fade in) - however, looking closer to the video, it seems as if there is still an animation

(i'm still trying to find a way to reproduce, and failing so far)

**Comment by r10s** [comment] 2023-09-30 20:52
i created a pr that may help on this issue, otherwise, closing this issue as there is no actionable item

**Closed by r10s** 2023-09-30 20:52 UTC
Labels: bug, webxdc
