### ISSUE TITLE
Can't share image with "share file"

### ISSUE THREAD

**Issue by havet** [deltachat/deltachat-android#1949] opened 2021-06-08 07:47 UTC
- Android version: 8.0.0
- Device: Sony Xperia X
- Delta Chat version: 1.20.2
- Expected behavior: The message with the image attachment is sent by the device and received by the recipient.
- Actual behavior: Either the message is not shown on any of the devices (not sender, nor receiver), or the message is shown at the sender with an for ever spinning progress symbol cirkel.
- Steps to reproduce the problem: Start typing a text, then the attachment symbol disappears. You have to use the ... -menue to attach the image with "Add attachment". Send.
- Screenshots:
- Logs:

**Comment by havet** [comment] 2021-06-08 08:01
The issue appeared when chatting with an iOS-user (Iphone). Now I cannot reproduce the error when communicating with a Windows-user. I will retry later with the iOS-user.

**Comment by havet** [comment] 2021-06-08 14:14
Today I've successfully sent two images to the same recipient. One using the attachment symbol (before typing the message) and one using "share file" (after typing the message).

**Comment by havet** [comment] 2021-06-13 19:01
This actually one side of the issue DeltaChat messages are kept in infolder #1255

**Comment by gerryfrancis** [comment] 2021-06-14 09:57
@havet Thanks for your report. I am a little confused, because the steps to reproduce the problem you described have nothing to do with sharing a file:

> - Steps to reproduce the problem: Start typing a text, then the attachment symbol disappears. You have to use the ... -menue to attach the image with "Add attachment". Send.

Please give more details, thanks in advance.

**Comment by havet** [comment] 2021-06-14 18:35
There are two ways of sharing a file. Usually I use the attachment symbol, because I choose the file first and then write the message. This time I did the inverse and had to use the ...-menu to attach the file after writing the text. I suspected this was what caused the problem.
Later, I was inclined to believe that the problem is caused by bad network or some temporary trouble with the e-mail server; in combination with DeltaChats inability to cope with the problem.
But the message was not stuck in the receivers in-box, instead of be moved to the DeltaChat-folder as I suspected. Instead there where copies of old messages in that inbox.
https://github.com/deltachat/deltachat-ios/issues/1255
Now, there are two possibilties:
1) My original assumption was right: the problem was caused by the way I attached the file
or
2) It was caused by some network problem or problem with the e-mail server.
Anyhow, the receiver never got my message - it's not in the inbox and not in the DeltaChat-folder.

**Comment by gerryfrancis** [comment] 2021-07-06 12:27
A member of the testing group reported a similar behaviour after a video has been shared with a Delta Chat user.

**Comment by Hocuri** [comment] 2021-10-06 12:38
Let's close this as no actionable item, probably there were just network problems.

> Either the message is not shown on any of the devices (not sender, nor receiver),

It sometimes happens that it takes quite some time between pressing "send" and the image appearing on the sender's side, which definitely isn't nice but not easy to fix, either. Anyway, this is a possible explanation for this.

**Closed as completed by Hocuri** 2021-10-06 12:38 UTC
Labels: fwdAndShare, needs-feedback
