### ISSUE TITLE
Send button difference between landscape and portrait mode.

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#835] opened 2019-04-14 10:38 UTC
Platform (android/blackberry/anbox): Android 7.0

Device: Huawei nova

Delta Chat Version: 0.200.0 (Gplay version)

Expected behavior: the same send button in both views

Actual behavior: different send button in landscape mode and portrait mode

Steps to reproduce the problem: 
-start typing in portrait mode
-you see the paper plane
-turn your phone
-now the paper plane will be replaced by a normal button "message".

**Comment by adbenitez** [comment] 2019-04-15 14:32
I think this have nothing to do with DC, it is your keyboard, at least mine have an option to disable the functionality to enter that full screen mode in landscape which is better to type in a text field in landscape mode, what you are seen is not the DC UI but your keyboard UI, you hadn't shared any screenshot so I am assuming that is what you are talking about.

**Comment by webratte** [comment] 2019-04-15 16:14
Have you tried it with your phone?

It's definitely a bug in DC.

In landscape the send button is a regular button with the text "message".

I have tested it also with other messengers an the same keyboard and it works perfect.

At the moment I'm not able to upload a screenshot. I will do it later.

**Comment by Hocuri** [comment] 2019-04-17 15:46
That's WhatsApp in landscape (yes I use it ☹️) 
![Screenshot_20190417-174322_1](https://user-images.githubusercontent.com/18012815/56301734-affa7380-6138-11e9-9018-e380a8aead4d.png)

**Comment by Hocuri** [comment] 2019-04-17 15:48
So @adabinez is right

**Comment by webratte** [comment] 2019-04-17 16:20
Ah, Ok.
But in this case maybe there should be the Text "send" and not "message".

"Message" sounds wrong for me.

And still the paper plain would be the nicer soulution.

Kontalk do it this way.

**Comment by r10s** [comment] 2019-04-17 17:36
yip, a simple "send" would be better. 
apart from that, the layout seems to be normal "enlarged keyboard" layout. i would leave this as it is, also wrt accessibility or so.
an alternative would be to show the normal chat layout as in portrait-mode, however, this may be unusable on smaller screens if the keyboard is expanded.

**Comment by webratte** [comment] 2019-04-17 17:45
Yes, this sounds good to me.

**Comment by adbenitez** [comment] 2019-04-17 18:44
+1 for the send

**Comment by adbenitez** [comment] 2019-04-17 18:46
> apart from that, the layout seems to be normal "enlarged keyboard" layout. i would leave this as it is

agree, this is the expected behaviour, at least for me, I had never seen an app that don't do it this way

**Comment by adbenitez** [comment] 2019-04-17 18:46
> That's WhatsApp in landscape (yes I use it frowning_face)

shame on you!!! ;)

**Comment by webratte** [comment] 2019-04-17 19:25
I like the paper plane.
Isn't it nice ;-)

![IMG_20190417_212320](https://user-images.githubusercontent.com/6864851/56315156-4ccc0980-6157-11e9-8acf-758413e0b020.png)

**Comment by r10s** [comment] 2019-04-17 20:55
@adbenitez well, this is a normal activity, not quite the same. also the kontalk-title bar wastes space and prevents a multi-line edit field.

**Comment by r10s** [comment] 2019-04-17 21:42
fixed by #850

**Closed by r10s** 2019-04-17 21:42 UTC

**Comment by webratte** [comment] 2019-04-18 03:58
As I said before.
The text button "send" is ok to me.

But just for understanding.
Why not replace the text button with the graphical button "paper plane"?

There would be no waste of space but the UI would be more similar to the portrait mode.

**Comment by r10s** [comment] 2019-04-18 10:40
> Why not replace the text button with the graphical button "paper plane"? 

it seems not to be possible when using the keyboard this way, there is a function to change text text, but i found nothing to set an image or so:
https://developer.android.com/reference/android/widget/TextView#setImeActionLabel(java.lang.CharSequence,%20int)

again, it is possible when using a fully qualified activity, however, this will have some drawbacks as mentioned above.

**Comment by webratte** [comment] 2019-04-18 11:03
OK, thank you for clarifying this 👍

**Comment by r10s** [comment] 2019-04-18 12:30
you're welcome!
