### ISSUE TITLE
Wrong notification LED color after backup import

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1803] opened 2021-02-11 10:56 UTC
- Android version:
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2021-02-05).

- Device:
Fairphone FP2.

- Delta Chat version:
1.15.0-beta (latest nightly build).

- Expected behavior:
The notification LED should blink purple. (It did so before the backup was created.)

- Actual behavior:
The notification LED blinks blue.

- Steps to reproduce the problem:
-- Ensure that the current notification LED color is "Purple".
-- Select "Backup chats to external storage" from "Chats and media" to perform a backup.
-- In Android app settings, clear all memory for Delta Chat app.
-- Launch Delta Chat and import the backup you have created before.
-- Turn on sleep mode of the device and wait for an incoming message. (Result: The notification LED blinks blue.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by Hocuri** [comment] 2021-02-11 11:47
The backup only saves settings from the core; ui-specific things are not saved. We can store the led color in a config in the core, but it's rather low prio I'd say.

**Comment by gerryfrancis** [comment] 2021-02-11 12:01
> The backup only saves settings from the core; ui-specific things are not saved.

@Hocuri You are right, but the fact that the first notification LED color is blue and all following ones are purple exists. ;)

**Comment by gerryfrancis** [comment] 2021-02-11 12:17
Update: The color stays blue until "Appearance" is opened for the very first time, then the LED blinks purple. So the init value should be "Blue", not "Purple".

**Comment by adbenitez** [comment] 2021-06-20 23:48
that LED color is not persisted is the intended behavior for now, not a bug. If there is another related issue? I think it is better to create a new issue or rename this one and change description with more details of the actual bug. Sadly I don't have LED so can't help with issues in that area

**Comment by adbenitez** [comment] 2022-03-14 05:58
closing this as this is not a bug but a feature requests, please open thread in the forum if you think it is worthy

**Closed by adbenitez** 2022-03-14 05:58 UTC
