### ISSUE TITLE
Using alias email address creates group conversations when you receive replies

### ISSUE THREAD

**Issue by vatonbero** [deltachat/deltachat-android#1500] opened 2020-07-25 23:48 UTC
- Operating System Android: **Lineage OS 17.1 (Android 10)**

- Delta Chat Version: **1.10.5 (F-Droid version)**

- Expected behavior: When you use "Mail Provider" and have 2 alias addresses, changing from one to another email should be quite easy and it is: you just need to change email address without changing password and/or server settings in Delta Chat. The trouble seems to be with replies: you have your chats in the list ("Person 1", "Person 2", "Person 3" etc) and if you change alias address, Delta Chat app will allow you to continue chatting with the users (if you re-enter autocrypt block of numbers)

- Actual behavior: If you change alias address, Delta Chat will create group conversation containing currently used Delta Chat email (alias 1), you previous alias email address (alias 2) and receiver of this message.

- Steps to reproduce the problem:
-- Use email service allowing you alias email address
-- start chat with **person A**
-- create alias address **(alias 2)**
-- change email in Delta chat settings without changing anything else (from **alias 1** to **alias 2**)
-- re-enter autocrypt hidden key (blocks of numbers)
-- resume chatting with **person A**

- Logs: It seems that logs were overwritten when i added alias address and i cannot get logs with previous email. Still, here is the log (i have removed personal identifiable blocks): [deltachat-logs.zip](https://github.com/deltachat/deltachat-android/files/4976925/deltachat-logs.zip)

**Comment by gerryfrancis** [comment] 2020-07-26 22:43
Not absolutely sure about this, but I think it is not considered to change the mail address during a chat conversation, because it is still the same person who has attended the chat.

**Comment by angelo-fuchs** [comment] 2020-07-27 10:52
As "Identity" in DC is currently bound to the E-Mail address, this is not a bug but works as designed.

To explain the background:
"You" are only the currently logged in E-Mail Address.

That means from the perspective of DC a message delivered to your account with a different address in the "To" Header is treated as a Mail
FROM Someone (Sender) 
TO (Alias 1) with 
BCC (Alias 2).
Therefore a group with three participants.

I will close this issue as DC is working as designed.
Please do open a conversation on the forum about this. It is far better suited to discussing feature requests.

**Closed by angelo-fuchs** 2020-07-27 10:52 UTC
Labels: bug
