### ISSUE TITLE
Does not work with office 365 or outlook

### ISSUE THREAD

**Issue by Karkus476** [deltachat/deltachat-android#168] opened 2017-09-17 18:34 UTC
App refuses to authenticate with office 365 or outlook for smtp. (STARTTLS)
Server: smtp.office365.com/smtp-mail.outlook.com Port: 587
I am using my full email address as login name and the same password as for IMAP (which I think works).
For thunderbird, I have to set the authentication to "Normal Password" (and then I am able to send mail just fine.)
Thanks.

**Comment by Wiredframe** [comment] 2017-10-06 12:31
I can confirm that I can't login either. I'm using a Microsoft Exchange 2013 account. Any chance this will be fixed in a future release? 👍

**Comment by r10s** [comment] 2017-10-06 17:27
> Any chance this will be fixed in a future release?

Of course there are chances, it's just a thing of time and money ...

**Comment by CitoplasmaX** [comment] 2017-10-15 22:49
You can create al account for free (of charge).

**Comment by CitoplasmaX** [comment] 2017-10-15 22:49
An*

**Comment by Wiredframe** [comment] 2017-10-16 07:58
Thanks. I just added an alias adress and set it to IMAP. 👍

**Comment by QuibblingAsh42** [comment] 2017-10-17 23:11
Confirmed it's not working for me, either.  Hopefully you'll be able to find something.

**Comment by Ampli-fier** [comment] 2017-11-23 23:13
Performed test with own account and got:

`hh:mm:18.402  I com.b44t.messenger: No worthy mechs found`
`hh:mm:18.406  E DeltaChat: Error: SMTP-login failed for user xxxx@xxx.xxx (Login failed)`

Sent full logs (logcat zipped) to r10s.

**Comment by Ampli-fier** [comment] 2017-12-10 08:30
> `hh:mm:18.402 I com.b44t.messenger: No worthy mechs found`

I think this is related to missing configuration in the Android UI, which leads to wrong setting of the `server_flags`.
When I tested with **Delta Chat Core**, I set the value for `server_flags` to `66052`. With this value I was able to connect (to office365 server).

Here the calculation:

`4 (MR_AUTH_NORMAL) + 10000 -> (MR_SMTP_SOCKET_STARTTLS) + 200 -> (MR_IMAP_SOCKET_SSL)`
`=> 10204 (hex) => 66052 (dec)`

When I use Android and try to connect, I only see this configured in sqlite db:
`11|server_flags|66048`

After changing the value in sqlite manually to `66052`, the error message from above is gone (I am still not able to connect successfully, though. I receive a `Connection refused`).

Searching the web leads to some hints regarding authentication mechanism ("**mechs**") problems, too.

The authentication mechanism setting (flag) is not available in the UI and not used. I think this must be added.

**Comment by Ampli-fier** [comment] 2017-12-10 16:25
Suspecting the problem in "mrmailbox_configure.c" ... seems the intention was to hide this setting from the user.

**Comment by wilsonrljr** [comment] 2018-03-31 13:05
Is there anything that I could do in order to solve this issue?

**Comment by r10s** [comment] 2018-03-31 13:19
iirc @Ampli-fier has a workaround, however, i personally have not tried this out yet.

**Comment by wilsonrljr** [comment] 2018-03-31 13:28
I get it. I'll keep an eye in this. Delta chat is exactly what I was looking for, but my main account is a outlook account. Anyway, congratulations. The app is really great.

**Comment by r10s** [comment] 2018-03-31 14:26
sooner or later, the outlook support will be fixed :)

**Comment by Ampli-fier** [comment] 2018-04-02 19:28
Unfortunately, I have no workaround. Connecting with **Core** works straight when setting all params manually.

A possible workaround I had in mind was to copy the DB content from Linux (Mint) - where **Core** is running - to Android. Doing so would skip the (potentially buggy) _configure_ part and only run _connect_.
I tried that and connecting with IMAP works fine, but with SMTP not:

```
mm:32.007 I DeltaChat: T2: Connecting to SMTP-server "smtp.office365.com:587" via Socket...
mm:32.277 I DeltaChat: T2: Switching to SMTP-STARTTLS.
mm:32.480 I DeltaChat: T2: Connection to SMTP-server ok.
mm:32.480 I DeltaChat: T2: Login to SMTP-server as "<user>@<domain>.com"...
mm:32.653 I com.b44t.messenger.beta: No worthy mechs found
mm:32.654 W DeltaChat: T2: SMTP-login failed for user <user>@<domain>.com (Login failed)
```

Here the successful attempt with **Core**:

```
T2: Connecting to SMTP-server "smtp.office365.com:587" via Socket...
T2: Switching to SMTP-STARTTLS.
T2: Connection to SMTP-server ok.
T2: Login to SMTP-server as "<user>@<domain>.com"...
T2: SMTP-Login ok.
```

The same **Core** version (0.16) is used and the same sqlite DB content ... How can this be?!?

**Comment by Ampli-fier** [comment] 2018-04-13 21:29
Today is Friday, the 13th ... and it is a good day :)

I found a change in the configuration for SASL (where the `No worthy mechs found` comes from) that makes it possible to log in to the smtp.office365.com server with STARTTLS.

The mechanism that is missing is called `LOGIN`.

When I enable this in [config.h](https://github.com/deltachat/deltachat-android/blob/5e61857384d4cdc7c5917af261cacf9a6731abd5/MessengerProj/jni/cyrussasl/include/sasl/config.h#L406) with `#define STATIC_LOGIN`and compile a new version of DC for Android, then I get

`04-13 22:54:03.299 I DeltaChat: T3: SMTP-Login ok.`

I still need to 'hack' the configure part to correct the `server_flags`.

For rooted phones it is easy. Start DC (initial) and enter the settings for Office365 and try to connect. It will fail and you must stop DC on the phone. Open a root shell and do:

```
cd /data/data/com.b44t.messenger*/files
sqlite3 messenger.db "update config SET value='66052' where keyname='server_flags';"
```

Restart DC and go back to the configuration screen. Click the checkmark to connect ... 

This is how it worked for my account/settings:

```
*IMAP*
server: outlook.office365.com
port: 993
  connection-security: SSL_TLS_REQUIRED
  authentication-type: PLAIN

*SMTP*
server: smtp.office365.com
port: 587
  connection-security: STARTTLS_REQUIRED
  authentication-type: PLAIN
```

**Comment by Ampli-fier** [comment] 2018-04-14 05:33
Did you compile a new version with the change in config.h?

When you tried, you used 

smtp-office365.com:587 or 
smtp.office365.com:587?

**Comment by wilsonrljr** [comment] 2018-04-14 18:59
I forgot to change the config.h .. 
But now I have compiled again and the new apk keep crashing after install... 
I'm sure I'm doing something wrong, so I'll wait for updates from here..

**Comment by Ampli-fier** [comment] 2018-04-15 21:01
I'm pretty sure that the issue is fixed with the above PR.

The wrong flags that I mentioned above are only temporary. They result from the selections in the Android UI and are written to the Database before the Core part starts.

In "mrmailbox_configure.c" the AUTH flags are added before the attempt to login (both: IMAP & SMTP).
Now, with the mech available, both logins succeed and the configuration can be finished.

Worth mentioning that the smtp.office365.com server sometimes seems not to respond too fast.

By reaching this point, DC write the used flags to the database (as configured_server_flags):

```
localhost files # sqlite3 messenger.db "select * from config where keyname like '%flag%';"
8|server_flags|66048
43|configured_server_flags|66052
localhost files #
```

**Comment by wilsonrljr** [comment] 2018-04-17 14:28
I tried to follow the steps you mentioned before. But I'm just an user that liked DC a lot and I this was the first time I tried to compile an Android app.. So I surely messed up in some steps because the app crash when I open it.

Anyway, thanks for the help. I will wait for an update on F-droid.

**Comment by r10s** [comment] 2018-04-17 15:56
@wilsonrljr the pull request is merged and 0.17.0 or later will contain the fix then.

**Comment by t-oster** [comment] 2018-06-02 23:00
so this should be working now and can be closed?

**Comment by t-oster** [comment] 2018-06-08 08:29
@Karkus476 @Wiredframe does it work with the latest version? Can we close this issue? Or can you provide test-account credentials so I can have a look into this?

**Comment by BishopT** [comment] 2018-06-14 06:42
Tested with 0.17.3 and a something@outlook.fr account: Leaving all automatic in connection parameters does not work but it works when entering connection parameters specified in the account settings.

**Comment by t-oster** [comment] 2018-06-14 13:23
Ok. The autoconfig for outlook is a separate issue. Somebody should:

- Take the info from this page https://support.office.com/en-us/article/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040
- Create an XML like this https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration/FileFormat/HowTo
- Submit it here https://bugzilla.mozilla.org/enter_bug.cgi?format=guided#h=dupes|Webtools|ISPDB%20Database%20Entries like described here https://developer.mozilla.org/de/docs/Mozilla/Thunderbird/Autokonfiguration#ISPDB

after they integrated the config, it should work in thunderbird and DC automatically. You can use multiple domains in the file, I think it's the same for outlook.de, outlook.com etc.

**Comment by r10s** [comment] 2018-09-07 15:17
moved to https://github.com/deltachat/deltachat-core/issues/267

**Closed by r10s** 2018-09-07 15:17 UTC

**Comment by moriel5** [comment] 2022-05-10 15:24
Since deltachat-core is now read only, I'll post here.

I am unable to login to my Outlook.com inbox (with grandfathered Live credentials), however it just fails, with what looks to be a timeout?
This is a personal account, not an organization account, and I do have OTP enabled, although OTP isn't mentioned at all in the error.

The error consists is as follows:
- no response: code: None, info: Some("LOGIN failed.")

**Comment by Hocuri** [comment] 2022-05-12 13:07
This issue is 4 years old, it's really unlikely that this has something to do with the issue you are having today. Anyway, unfortunately I don't know what your problem could be, but you should ask at https://support.delta.chat , maybe someone else has had a similar issue, and here in an old closed issues chances are that no one will see your message :)

**Comment by moriel5** [comment] 2022-05-14 21:18
Thanks, when I have the time, I'll do so immediately (perhaps I'll be able to do in the morning).
