### ISSUE TITLE
Delta chat uses device time not message time to sort messages

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#398] opened 2018-11-04 16:58 UTC
Delta chat uses device time to mark sort new messages. After a reset my phone time went to Jan 14 2014  and for 2 hours all new messages were marked with that time and sorted to the very front of my message list.. Needless to say I did not see a one.After I fixed the time on my device the messages stayed at the wrong time. Messages should be marked new and put at the end of the list where they are visible and the message sent time and received time should be checked in some way to notify of newly acquired messages with unusual time stamps.

**Comment by testbird** [comment] 2018-11-11 20:51
Isn't there a database index with chronological sorting order that could be used?
Using that could also remove the need to overwrite the sending time.

**Comment by r10s** [comment] 2018-11-11 21:15
i think the problem is not a lack of time information as such.
it's more about bad timestamps.

i think there is not much apps can do with a reasonable effort if the time of the phone is just bad.

Delta Chat uses the "effective data" from Autocrypt as defined at https://autocrypt.org/level1.html#effective-date - in short, if a timestamp from a received messages cannot be in the future. this makes some sense and protects against different issues. however, if the device data is bad, this check will fail - but if will protect _other_ users eg. if your device time is in the future ...

**Comment by testbird** [comment] 2018-11-11 22:00
What I meant wasn't a lack of time information, but to avoid the error entirely by using a local DB index column instead.

Sqlite seems to use a "rowid" index column, and allow to have own index (counter) colums. As an index is increased with every entry saved, it should serve well to sort the messages in the order in which they arrived, independently of local or remote system times.

If using the index to sort the message when displaying, the "effective date" set in the message may then possibly be curious, but irrelevant. (Also no need to overwrite it anymore, which is a bad idea with time zone differences. I think there was also already a bug report for that. )

**Comment by r10s** [comment] 2018-11-12 00:37
but this would not change the message order if the system time changes, imu this was the gist of the original post.

wrt to the id: in fact, we're using sth. similar, the sort_timestamp - in contrast to a uid, this keeps the messages in order. eg. when forwarding 10 messages, they may arrive in any order at the recipient - but if this is a conversation, they should appear in the correct order. this is ensured by the sort_timestamp and so called "time smearing", however, all this requires a correct date on the system (if works with a bad date, however, as mentioned, things are not resorted when the system date change, for the reasons mentioned above)

see https://github.com/deltachat/deltachat-core/blob/master/src/dc_receive_imf.c#L268 for more details about the calculation

**Comment by testbird** [comment] 2018-11-12 11:38
> but this would not change the message order if the system time changes, imu this was the gist of the original post.

But that's the idea. If the messages are stored to the database in the order in which they arrive, they get subsequent index values. That order always remains the same then (order of arrival) regardless of any local or remote time value, their correctness, or time zone or error corrections. That's why I think it may solve the issue.

In the case of forwarded messages, when an earlier message arrives later due to some transport issue, the timestamps could still allow to reorder the messages in the database, e.g. switch the index values (during message saving).

**Comment by r10s** [comment] 2018-11-12 13:43
> That's why I think using such an index for the display order could solve the issue.

it may solve one issue but raise different ones, maybe worse ones - as mentioned above.

**Comment by testbird** [comment] 2018-11-12 13:57
Which problem do you see unsolved?

**Comment by r10s** [comment] 2018-11-12 15:17
ordering of messages. forwarded ones, but also if it comes to restore old messages from imap. how should this be solved when _only_ sorting by incoming date? (in fact, using the uid is similar to that) (apart from that the uid would need some tweaking as unused ids may be recycled, eg.)

**Comment by r10s** [comment] 2018-11-12 15:37
@testbird and how does sorting by uid help on the initial issue reported by @nutpantz?

**Comment by testbird** [comment] 2018-11-12 17:37
https://stackoverflow.com/questions/7905859/is-there-an-auto-increment-in-sqlite
http://www.sqlitetutorial.net/sqlite-autoincrement/

**Comment by testbird** [comment] 2018-11-12 23:57
The incoming date measured depends on the local system's time setting (which may be wrong, corrected, or regulary change when switching time zones). That's the cause for this issues' problems.

Simply saving received messages to the database in the order in which they arrive does not depend on any time setting. Displaying the messages in the order in which they were saved to the database will always result in the same order, the order of arrival as wanted for diplaying the messages.

As said, the order of incoming *forwarded* messages may still be checked by their sending date, and if there were changes from the sending order they can be (re)written to/in the database so they show in the same order as sent by the forwarding party (which would be the order in which the forwarding party originally received and answered the messages).

Limiting the sending time to the local reception time ("time smearing") would not be required anymore (It won't lead to later messages being shown before the messages from the "future".) It would thus be possible to actually provide the correct information about the sending time, as it was effective/given at the sender. This is especially useful and important across time zones. If the timestamp contains information about the time zone, the sending times from other time zones should of course be *displayed* converted to the correct local reception time zone.

**Comment by r10s** [comment] 2018-11-13 00:39
let us put time smearing away, this is not really related.

so, to the original issue:
- Delta Chat _uses_ the message time _unless_ it is newer than the Device Time
- this is not a Delta-thingie, this is from the Autocrypt-spec, we _cannot_ change this without breaking the spec
- the truncating to the current time has good reasons - it protects against malformed incoming mails
- downsides are - if the Device time is bad, things stop working

maybe we could get around this by using a fixed increment as the sort_timestamp, however, this raises problems when mails come out of order and also we could never download _old_ mails then. or react to IMAP giving us, for any reasons, old mails.

so, not relying on the device time may solve some problems, but will raise a bunch of others.

**Comment by testbird** [comment] 2018-11-13 10:39
From what I read in the autocrypt spec now I think all timestamps should be UTC, thus because times should only be *displayed* in the current local time zone there should be no time zone traveling problems.

The only problem I see with this fix for time resets would if a system time would initially be set to a future time when a first message arrives, but well as devices usually initialize with a past date that's quite unlikely.

**Comment by testbird** [comment] 2018-11-13 10:44
BTW I've also seen this "phone reset moves message into the past" thing.

**Comment by testbird** [comment] 2018-12-16 16:51
Another confirmation of this issue: https://support.delta.chat/t/desktop-app-and-previous-chats-not-showing-up/174/9

**Comment by r10s** [comment] 2019-02-10 16:58
i think the fix is to set the correct device time.

however, as the discussion is already shifted to the forum, i'll close this issue. the result of the forum discussion might be a concrete actionable and reasonable item then.

**Closed by r10s** 2019-02-10 16:58 UTC
Labels: core, discussion, system-interaction

**Comment by testbird** [comment] 2019-02-11 19:04
Device clocks will always get adjusted and reseted. The problem occures just because the sorting timestamp is only cut-off (limits future dates) by the current system time, and not also by the sorting time of the last already received message (limits past dates).

I think this is about as actionable as a user reported, and repetedly confirmed issue can get. My clumsy pull request draft would of course be in need of some developer insight to only do the cut-off for fresh messages in the code without affecting the other functions. https://github.com/deltachat/deltachat-core/pull/435#issuecomment-447657221

**Comment by r10s** [comment] 2019-02-11 23:59
for sure - therefore the discussion can continue in the forum. 

it's just nothing the android-ui can do in this item imu.

and also for the core it's not _that_ clear, as the comments in this thread and in the pr - that raised other problems - pointed out.

**Comment by testbird** [comment] 2019-02-12 12:48
message time is in the future, Delta chat uses [a transient past] device time not [bound by the last] message time to [correctly] sort messages

**Comment by adbenitez** [comment] 2019-04-02 13:31
if there are messages from date X, and for some reason(ex. factory reset) I send a new message with a wrong date X-1, following what r10s said that it would be better to fix the date as soon as possible, maybe some warning can be shown to help users, telling them something like "hey! seems like your phone date is wrong" would be helpful.
related  #749

**Comment by testbird** [comment] 2019-04-03 16:52
It's a good idea to provide a hint to the user that the system time has been set back, it **may** be wrong but might also be properly set back to another timezone.

When this happens, however, it is already too late to correct the system time before a message arrives.
And it would only be possible to correct the time, if it wasn't actually correctly set back to another timezone.

Thus, the test for messages with timestamps before the last sort_timestamp should probably still cause in a lower bound for the new message's sort_timestamp, **plus** the hint to the user in case of a system reset.

**Comment by nutpantz** [comment] 2019-04-03 17:00
My berry has a rtc so that may not be applicable.

**Comment by testbird** [comment] 2019-04-03 20:38
If you travel back in timezones, I think even with a radio controlled rtc new messages would need to get sorted behind the last message's sort_timestamp ("from the future").
