### ISSUE TITLE
Message font size setting not applied to some text fields

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#3290] opened 2024-09-13 14:00 UTC
- Android version:
Android 13 & 14.

- Devices:
Google Pixel 8 & Samsung Galaxy A71.

- Delta Chat version:
1.46.13.

- Expected behavior:
The message font size setting in Delta Chat is applied _adequately_ to all text fields.

- Actual behavior:
The message font size setting in Delta Chat is applied _adequately_ to some text fields only, e.g. text for Webxdc apps is displayed with a small font.

- Steps to reproduce the problem:
-- Set the message font size to "Extra large" in the app settings.
-- Open a chat that contains a Webxdc app. (Result: The font that is used for the Webxdc app is too small, other text fields are affected, too, see the screenshot below.)

- Screenshot:
![grafik](https://github.com/user-attachments/assets/a445445f-74dd-4476-b60d-309e08ce04ea)

- Logs:
N/A.

**Comment by adbenitez** [comment] 2024-09-16 16:17
also system messages keep the same size, probably the same for audio and file messages I think this is intentional and not a bug, so this is a feature request :thinking:

**Comment by r10s** [comment] 2024-09-22 22:36
> The message font size setting in Delta Chat is applied adequately to all text fields.

this is not how it is meant to work. it really only changes the text the others has types, so the most important bit of information :)

the option also reads "Message Font Size", _not_ "UI Font Size" or just "Font Size".

if it would change the text here adequately for all text fields, the option would also be a bit superfluous, as one can do this with the system settings already (eg. for need accessibility).

anyways, closing this issue here as things are on purpose and there is no actionable item.  if needed, of course, discussion can continue in the [forum](https://support.delta.chat)

**Closed by r10s** 2024-09-22 22:36 UTC
Labels: feature proposal

**Comment by hpk42** [comment] 2024-09-23 08:01
FWIW just this morning i went to Android system settings and adjusted font-size --
worked nicely also for Delta Chat -- chatlist, messages, input field were all adjusted.

**Comment by gerryfrancis** [comment] 2024-09-23 08:16
> if needed, of course, discussion can continue in the [forum](https://support.delta.chat/)

I have opened a new thread to discuss the topic, as I think this might be important for people with bad eyesight: https://support.delta.chat/t/different-message-font-sizes/3268
