### ISSUE TITLE
Detect active airplane mode

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1573] opened 2020-08-17 14:34 UTC
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2020-08-14).

- Delta Chat Version:
1.12.2.

- Expected behavior:
Detect active airplane mode.

- Actual behavior:
Active airplane mode is not detected.

- Steps to reproduce the problem:
-- Enable airplane mode.

- Screenshots:
N/A.

- Logs:
This was logged during airplane mode:

```
08-17 15:29:42.212  6355  6407 W DeltaChat: src/imap/idle.rs:110: Idle wait errored: Io(Os { code: 110, kind: TimedOut, message: "Connection timed out" })
08-17 15:29:42.232  6355  6407 W DeltaChat: src/scheduler.rs:147: IMAP IDLE protocol failed to init/complete: io: Broken pipe (os error 32)
08-17 15:29:42.276  6355  6407 I DeltaChat: src/imap/select_folder.rs:32: Expunge messages in "DeltaChat".
08-17 15:29:42.277  6355  6407 W DeltaChat: src/imap/mod.rs:342: failed to close folder: NoSession
08-17 15:29:42.277  6355  6407 W DeltaChat: src/imap/idle.rs:110: Idle wait errored: Io(Os { code: 110, kind: TimedOut, message: "Connection timed out" })
08-17 15:29:42.277  6355  6407 E DeltaChat: Antwort von IMAP posteo.de:143: io: could not resolve address `("posteo.de", 143)` Einige Anbieter platzieren zusätzliche Informationen im Posteingang, die Sie z.B. im Web-Frontend abrufen können. Bitten Sie Ihren Anbieter oder FreundInnen um Rat, wenn es Probleme gibt.
08-17 15:29:42.278  6355  6407 W DeltaChat: src/imap/mod.rs:421: failed to setup imap handle: IMAP Connection Failed params: io: could not resolve address `("posteo.de", 143)`
08-17 15:29:42.278  6355  6407 W DeltaChat: src/scheduler.rs:130: imap connection failed: IMAP Connection Failed params: anonymous@posteo.at imap:anonymous@posteo.de:***:posteo.de:143:cert_automatic smtp:anonymous@posteo.de:***:posteo.de:587:cert_automatic AUTH_NORMAL 0x4IMAP_STARTTLS 0x100SMTP_STARTTLS 0x10000
08-17 15:29:42.278  6355  6407 I DeltaChat: src/imap/idle.rs:136: IMAP-fake-IDLEing...
08-17 15:29:42.279  6355  6407 W DeltaChat: src/scheduler.rs:147: IMAP IDLE protocol failed to init/complete: io: Broken pipe (os error 32)
08-17 15:29:42.281  6355  6407 I DeltaChat: src/imap/select_folder.rs:32: Expunge messages in "Sent".
08-17 15:29:42.281  6355  6407 W DeltaChat: src/imap/mod.rs:342: failed to close folder: NoSession
08-17 15:29:42.282  6355  6407 E DeltaChat: Antwort von IMAP posteo.de:143: io: could not resolve address `("posteo.de", 143)` Einige Anbieter platzieren zusätzliche Informationen im Posteingang, die Sie z.B. im Web-Frontend abrufen können. Bitten Sie Ihren Anbieter oder FreundInnen um Rat, wenn es Probleme gibt.
08-17 15:29:42.283  6355  6407 W DeltaChat: src/imap/mod.rs:421: failed to setup imap handle: IMAP Connection Failed params: io: could not resolve address `("posteo.de", 143)`
08-17 15:29:42.283  6355  6407 W DeltaChat: src/scheduler.rs:130: imap connection failed: IMAP Connection Failed params: anonymous@posteo.at imap:anonymous@posteo.de:***:posteo.de:143:cert_automatic smtp:anonymous@posteo.de:***:posteo.de:587:cert_automatic AUTH_NORMAL 0x4IMAP_STARTTLS 0x100SMTP_STARTTLS 0x10000
08-17 15:29:42.283  6355  6407 I DeltaChat: src/imap/idle.rs:136: IMAP-fake-IDLEing...
08-17 15:29:42.334  6355  6407 W DeltaChat: src/imap/idle.rs:110: Idle wait errored: Io(Os { code: 110, kind: TimedOut, message: "Connection timed out" })
08-17 15:29:42.354  6355  6773 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
08-17 15:29:42.372  6355  6407 W DeltaChat: src/scheduler.rs:147: IMAP IDLE protocol failed to init/complete: io: Broken pipe (os error 32)
08-17 15:29:42.374  6355  6407 I DeltaChat: src/job.rs:1077: loading job for Imap-thread
08-17 15:29:42.398  6355  6407 I DeltaChat: src/imap/select_folder.rs:32: Expunge messages in "INBOX".
08-17 15:29:42.398  6355  6407 W DeltaChat: src/imap/mod.rs:342: failed to close folder: NoSession
08-17 15:29:42.414  6355  6407 E DeltaChat: Antwort von IMAP posteo.de:143: io: could not resolve address `("posteo.de", 143)` Einige Anbieter platzieren zusätzliche Informationen im Posteingang, die Sie z.B. im Web-Frontend abrufen können. Bitten Sie Ihren Anbieter oder FreundInnen um Rat, wenn es Probleme gibt.
08-17 15:29:42.415  6355  6407 W DeltaChat: src/imap/mod.rs:421: failed to setup imap handle: IMAP Connection Failed params: io: could not resolve address `("posteo.de", 143)`
08-17 15:29:42.415  6355  6407 W DeltaChat: src/scheduler.rs:130: imap connection failed: IMAP Connection Failed params: anonymous@posteo.at imap:anonymous@posteo.de:***:posteo.de:143:cert_automatic smtp:anonymous@posteo.de:***:posteo.de:587:cert_automatic AUTH_NORMAL 0x4IMAP_STARTTLS 0x100SMTP_STARTTLS 0x10000
08-17 15:29:42.415  6355  6407 I DeltaChat: src/imap/idle.rs:136: IMAP-fake-IDLEing...
```

- Remarks:
-- The device was not connected to any WLAN either, but the WLAN interface itself was active.
-- Delta Chat has resumed after airplane mode has been switched off. Nevertheless, I believe this could be an issue, because several attempts to connect to the IMAP server were done.

**Comment by gerryfrancis** [comment] 2020-08-17 15:57
```
08-17 15:29:42.212  6355  6407 W DeltaChat: src/imap/idle.rs:110: Idle wait errored: Io(Os { code: 110, kind: TimedOut, message: "Connection timed out" })
08-17 15:29:42.232  6355  6407 W DeltaChat: src/scheduler.rs:147: IMAP IDLE protocol failed to init/complete: io: Broken pipe (os error 32)
08-17 15:29:42.276  6355  6407 I DeltaChat: src/imap/select_folder.rs:32: Expunge messages in "DeltaChat".
08-17 15:29:42.277  6355  6407 W DeltaChat: src/imap/mod.rs:342: failed to close folder: NoSession
```

Referring to https://github.com/deltachat/deltachat-core-rust/pull/1704 , I guess that Expunge should not be called after IMAP IDLE has failed, correct?

**Comment by angelo-fuchs** [comment] 2020-08-17 21:39
Interesting.
What would be the expected behavior? Wifi was active (as far as DC can tell) so there probably was a connection.
Would you want DC to be inactive during Airplane mode even if there is an active Wifi?

**Comment by gerryfrancis** [comment] 2020-08-17 21:50
> Wifi was active (as far as DC can tell) so there probably was a connection.

@angelo-fuchs No, just the WiFi interface of the phone was active, but not connected.

**Comment by angelo-fuchs** [comment] 2020-08-18 07:27
@gerryfrancis I see.

It looks like a bug here. `ApplicationDcContext#isNetworkConnected` checks `ConnectivityManager#getActiveNetworkInfo` and `NetworkInfo#isConnected` which should only return true if there is a connection that can be used.

We need to check if `isNetworkConnected` is called everywhere it should be.

**Comment by gerryfrancis** [comment] 2020-08-18 20:00
@angelo-fuchs I think, I have found a hint: Usually the message "No network." appears in Delta Chat when it is opened and a connection to the internet is not available. This does not happen when I reboot the phone and enable airplane mode immediately before I open the app.

**Comment by gerryfrancis** [comment] 2020-08-18 20:33
This is what happens when I enable airplane mode:

```
08-18 21:36:12.238  6226  6276 I WM-WorkerWrapper: Work [ id=267c5f01-3903-4fdd-af96-adea247d5fbb, tags={ org.thoughtcrime.securesms.connect.FetchWorker } ] was cancelled
08-18 21:36:12.238  6226  6276 I WM-WorkerWrapper: java.util.concurrent.CancellationException: Task was cancelled.
08-18 21:36:12.238  6226  6276 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
08-18 21:36:12.238  6226  6276 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
08-18 21:36:12.238  6226  6276 I WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
08-18 21:36:12.238  6226  6276 I WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:298)
08-18 21:36:12.238  6226  6276 I WM-WorkerWrapper: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
08-18 21:36:12.238  6226  6276 I WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-18 21:36:12.238  6226  6276 I WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-18 21:36:12.238  6226  6276 I WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:919)
```

@angelo-fuchs Is that correct?

**Comment by r10s** [comment] 2020-08-18 21:07
> We need to check if isNetworkConnected is called everywhere it should be.

In general, we do _not_ check if network is available or not before doing something on the network.

the reason for that is that these checks are not reliable. in flaky networks, the shift between "network available" and "no network" may be so fast, that there is not much sense to check the state before trying doing something.

so, the approach of the core is just to "keep trying" - of course, with larger backoff timeouts. only if android signals that there is "potentially some network state change" - eg. because of wifi connected, we pass these information to the core, that resets the backoff timeouts then (roughly).

(just some general background information, i did not read through all logs in this issue, might be there is another bug that is fixable from android side)

**Comment by gerryfrancis** [comment] 2020-08-18 21:19
@r10s Thank you for your explanation, I thought something similar after reading the logs, which went in the "try and error" direction. ;) Nevertheless I believe that the issue is caused by the cancellation of FetchWorker. (See my comment above.) When this happens, we have these two lines afterwards:

```
08-17 15:29:42.212  6355  6407 W DeltaChat: src/imap/idle.rs:110: Idle wait errored: Io(Os { code: 110, kind: TimedOut, message: "Connection timed out" })
08-17 15:29:42.232  6355  6407 W DeltaChat: src/scheduler.rs:147: IMAP IDLE protocol failed to init/complete: io: Broken pipe (os error 32)
```

FetchWorker was "killed" before by enabling airplane mode, but it seems the rest is not aware of it, so procedures are continuing (and failing):

```
08-17 15:29:42.276  6355  6407 I DeltaChat: src/imap/select_folder.rs:32: Expunge messages in "DeltaChat".
08-17 15:29:42.277  6355  6407 W DeltaChat: src/imap/mod.rs:342: failed to close folder: NoSession
```

Of course, this is just my personal explanation of what is happening in the background, because I cannot read the code. ;)

**Comment by gerryfrancis** [comment] 2020-08-18 22:11
OK, regarding FetchWorker, it seems that I followed the wrong path, because the task is no longer cancelled when Delta Chat is excluded from battery optimization.

But the remaining question is: Why are Expunge operations performed shortly after "Connection timed out"?

**Comment by hpk42** [comment] 2020-08-19 06:45
On Tue, Aug 18, 2020 at 14:07 -0700, bjoern wrote:
> so, the approach of the core is just to "keep trying" - of course, with larger backoff timeouts. 

Are you sure we do exponential backoff for smtp and imap connection attempts?

**Comment by r10s** [comment] 2020-08-19 14:14
> Are you sure we do exponential backoff for smtp and imap connection attempts?

no :)

however, the job is retried at some point in time, imu, this implies trying to set up the connection not later than that.

**Comment by gerryfrancis** [comment] 2020-08-19 14:28
@r10s OK, that seems to be the case. But what I still cannot understand is why Expunge operations are called immediately after "Connection timed out" each and every time, just milliseconds afterwards. To me it looks like a trigger, but still it does not make sense to launch further network operations immediately after it is clear that no network is available.

**Comment by r10s** [comment] 2021-09-08 08:54
we meanwhile have a much better state getting information about connectivity (parts of this issue discuss that point).

for timeouts/backoff - this is out of scope for android and on core, there are some ongoing discussions, https://github.com/deltachat/deltachat-core-rust/issues/2208 and points why just checking some state is maybe counter-productive were made above.

closing as there is no actionable item.

**Closed by r10s** 2021-09-08 08:54 UTC
Labels: bug
