### ISSUE TITLE
Timestamp of last message in summary screen does not auto-update

### ISSUE THREAD

**Issue by rrthomas** [deltachat/deltachat-android#2236] opened 2022-03-15 18:17 UTC
- Android version: 9
- Device: Sony Xperia XZ1 Compact
- Delta Chat version: 1.28.3
- Expected behavior: Timestamps should update automatically
- Actual behavior: The timestamps of messages in the chat view updates automatically. The timestamp of the most recent message shown in the list of chats does not update automatically.
- Steps to reproduce the problem: Send a message. See that its time stamp is e.g. "Now" in the list of chats. Switch to another app and wait a bit. Switch back to DeltaChat. The timestamp is still what it was when I last looked. If instead of switching directly to another app I press the system Back icon to go to the Home screen, then go back into DeltaChat, the timestamp is correctly updated.
- Screenshots: n/a
- Logs: n/a

Thanks for DeltaChat!

**Comment by adbenitez** [comment] 2022-03-23 21:57
this seems a duplicate of #2029

**Closed by adbenitez** 2022-03-23 21:57 UTC

**Comment by rrthomas** [comment] 2022-03-24 08:18
Thanks, @adbenitez; apologies that I didn't find the other bug when I filed!

**Comment by adbenitez** [comment] 2022-03-24 20:44
@rrthomas thanks to you for testing the app and reporting! :+1:
