### ISSUE TITLE
add concluding slash to Videochat-link if missing

### ISSUE THREAD

**Issue by Caliandroid** [deltachat/deltachat-android#1545] opened 2020-08-12 14:21 UTC
Delta Chat 1.12.2 
Video chat instance feature missing concluding slash

Tested with my Jitsi server:

If the inserted url does not end with a "/" (in the settings page), the invitation link will look like this https://meet.jitsi.comA3434ß8

Please add a concluding slash if not present in the video chat url to fix this.

**Comment by r10s** [comment] 2020-08-12 15:12
yip, that would be nice.

i think, in practise, it is a but more tricky the missing slash may also be by design, eg. when the url ends with key/value paies as `https://example.org/?audio=true&roomname=`

**Comment by r10s** [comment] 2020-08-13 20:48
closing this in favor to https://github.com/deltachat/deltachat-core-rust/issues/1830

**Closed by r10s** 2020-08-13 20:48 UTC
