### ISSUE TITLE
Configure IMAP folders

### ISSUE THREAD

**Issue by rootuser1** [deltachat/deltachat-android#101] opened 2017-06-11 13:23 UTC
I suggest to have a dialog to configure IMAP folders. Delta Chat should use those to read/write chat messages.

I'm using Delta Chat since early F-Droid versions and I don't know if anything changed in between but my app (0.9.0) is storing sent messages in the "Drafts" folder.
Maybe that's why I'm not having them shown within Delta Chat when (re-)installing the app (e.g. on a new device). Moreover, if I (re-)install Delta Chat the app does not "load" any old chat messages - neither from "Inbox" nor "Drafts". It works fine for new chat messages and I can see all of them using K-9 Mail. Anyone having similar issues?

**Comment by licaon-kter** [comment] 2017-06-12 07:59
duplicate of #63 ?

**Comment by rootuser1** [comment] 2017-06-21 16:32
Seems to be similar to #28 or #103.

**Comment by rootuser1** [comment] 2017-06-22 18:33
Well, I don't have a "Chats" folder either, like (see #108). Can I move all (received and sent) chat messages to a "Chats" folder, if I can create it manually? Do I have to reconfigure Delta Chat to use the "Chats" folder?

**Comment by r10s** [comment] 2017-11-18 12:25
see https://github.com/deltachat/deltachat-core/issues/47

**Closed by r10s** 2017-11-18 12:25 UTC
