### ISSUE TITLE
message size and data plans

### ISSUE THREAD

**Issue by fauno** [deltachat/deltachat-android#162] opened 2017-09-03 00:07 UTC
hey, we're just re-testing dc and it's awesome!  but i'm wondering about the size of messages, which are even bigger after encryption is on.  a single hello can become a 4kb message between two accounts in the same server, and i guess it'd grow a lot between different servers, when the received and other headers are added.  i also noticed the autocrypt header is added to every message, is that really needed after the initial key exchange?  i don't know the details of the autocrypt spec yet, so i don't know if it's required.

the issue is that around here our data plans are capped at most at 3 gb / month so a little data saving is appreciated :)

**Comment by rizzopablo** [comment] 2017-09-03 03:57
Hi Fauno, cómo estas?

May be Delta could send messages with CCO to the sender address, this will place a copy of the message in the inbox without the need to upload the message twice, first time to smtp and second time to imap server. The message sent may be moved to Chats folder server side without downloading it completely, only headers. I used to configure my K-9 mail client  this way and it worked well.

**Comment by fauno** [comment] 2017-09-04 12:23
Pablo Manuel Rizzo <notifications@github.com> writes:

> Hi Fauno, cómo estas?

:)

> May be Delta could send messages with CCO to the sender address, this
> will place a copy of the message in the inbox without the need to
> upload the message twice, first time to smtp and second time to imap
> server. The message sent may be moved to Chats folder server side
> without downloading it completely, only headers. I used to configure
> my K-9 mail client this way and it worked well.

that would save half the space too!  but there's still room to remove
some headers from the email itself i think, specially the autocrypt
header that sends the pubkey every time.  from what i gather from the
spec, it isn't required on every message?

the email server can also be configured to discard specific headers, not
sure at the moment if they can be done under specific conditions, like
the presence of delta chat headers.

-- 
}(:=

**Comment by testbird** [comment] 2018-03-07 23:22
> room to remove some headers from the email itself i think, specially the autocrypt header that sends the pubkey every time.

If the autocrypt spec defines when sending the public keys is required, and a way to request re-sending of (deleted/lost etc.) keys, that might already be one part of what is minimally needed to have short Email-notify messages defined https://github.com/deltachat/deltachat-core/issues/113 (other would be a header that identifies them? and contains the encrypted subscription token (or request?) and the target app id?).

**Comment by r10s** [comment] 2018-10-13 22:48
i think this is can be regarded as a duplicate of https://github.com/deltachat/deltachat-core/issues/46

closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat

**Closed by r10s** 2018-10-13 22:48 UTC
