### ISSUE TITLE
profile picture not editable sometimes

### ISSUE THREAD

**Issue by AndreasLattmann** [deltachat/deltachat-android#1171] opened 2019-12-17 21:39 UTC
- Android version: 9
- Device: Huawei HMA-L29
- Delta Chat version: 1.0.0
- Expected behavior: Change the profile picture
- Actual behavior: It is no longer possible to insert a new image.
- Steps to reproduce the problem: Insert a profile image, then delete it and try to insert another one.
- Screenshots:

![2019-12-17-22-28-1](https://user-images.githubusercontent.com/58994349/71035858-b81e0f00-211c-11ea-88e1-a4738c00e2c6.jpg)

**Comment by r10s** [comment] 2019-12-17 21:40
@AndreasLattmann thanks for reporting, we'll check this :)

**Comment by r10s** [comment] 2019-12-18 00:34
hm, i cannot reproduce this.
i tried the following:

1. --> select an avatar, hit ok
2. send a message
3. avatar is received
4. --> select another avatar, hit ok
5. send another message
6. avatar is changed
7. --> delete the avatar, hit ok
8. send a message
9. avatar is removed
10. --> again select an avatar, hit ok
11. send a message
12. avatar is received again

i tried this with both, avatars from the gallery and taking photos on two different devices - so which step fails for you? and what exactly does happen when you try to click the upload button? does a force-stop or device-restart help?

**Comment by AndreasLattmann** [comment] 2019-12-18 07:52
Now I can no longer reproduce the problem.  This morning I tried to insert the profile picture and it works.  Now I try to reproduce the problem.  What I know is that last night I didn't open the screen to crop the image.  🤔

**Comment by r10s** [comment] 2019-12-18 09:53
@AndreasLattmann thanks for coming back to this. i close this issue as it is not reproducible for now and there is no actionable item. we can reopen it as needed :)

**Closed by r10s** 2019-12-18 09:53 UTC
Labels: bug
