### ISSUE TITLE
No alert for new message in Contact Requests

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#228] opened 2017-12-24 00:53 UTC
The following behaviour to be seen now with v0.9.9 (f-droid version):

- New message has been arrived at "Contact Requests" (sender address is not known, sender uses non DC MUA).
- No alert for that raised at all (and no request to start new chat at top of chat list).

==> This means that the new message only can be detected by a manual check of "Contact Requests" in spite of that message requests a new contact!

This is a standard use case with contacts which are using non DC MUA and should produce an alert.

Proposal:
Produce an alert for all new messages in "Contact Requests".

Background:
This case came up by a friend's new mail address (chat with old address exists). He changes mail address and sent first message from non DC MUA. He uses non DC MUA by standard. 

Related issue:
Option to show "Contact Requests in chat list" by extended settings doesn't exist any more (but IMHO it was very useful and a good practice).

**Comment by testbird** [comment] 2017-12-24 01:49
> No alert for that raised at all (and no request to start new chat at top of chat list).

Strangely I was seeing too much prompts. The next one only comes after the previous is dismissed, have you done that?

> Proposal: Produce an alert for all new messages in "Contact Requests".

Personally I'd prefer no alerts for the not admitted messages ("contact requests") (beep only for messages considered wanted).  Note that your friend is probably not changing email address that often to warrant beeping for every spam and long, non-chat email.

Still the former special chat shown in the chat list solution allowed to change the notification preference in addition to being browsable?

**Comment by csb0730** [comment] 2017-12-26 17:57
1st - no I haven't done that. I simply did not get any alert in spite of that new message into contact requests chat. I get aware of this message only because I was asked by that friend why I did not saw his message!

2nd - I think the aim of Contact Requests chat should be to receive requests from new contacts. Therefore there should be an alert of any new message into that (any means that there should be an alert that there are unseen messages, maybe a small number like we had it). Simply that.

But by the way: The new way to show a request at the top of the chat list is only a kind of an alert. The main issue what I want to describe here is only that any kind of alert should be generated. Regardless how it's presented.

**Comment by testbird** [comment] 2017-12-28 15:00
Ok, the issue is clearer now.

1) Not getting any prompt may be a bug?

2) Visualisation of new non-chat messages is important.

Seems it needs to be reintroduced even with the new top-row-prompt. Maybe similar like it was previously with the number overlay on the "contact requests shown in chat list", but with a "?" as icon, and a "dismiss all" button? Having to dismiss every unrelated non-chat message (one after the other) in the new top-row-prompt is annoying. Certainly without a length limit.

**Comment by testbird** [comment] 2017-12-28 15:08
Oh, and the "contact requests shown in chat list" also allowed configuring playing a sound (for all non-chat messages).

**Comment by r10s** [comment] 2018-01-05 17:55
> The following behaviour to be seen now with v0.9.9 (f-droid version):
> 
> - New message has been arrived at "Contact Requests" (sender address is not known, sender uses non DC MUA).
> - No alert for that raised at all (and no request to start new chat at top of chat list).
> 
> ==> This means that the new message only can be detected by a manual check of "Contact Requests" in spite of that message requests a new contact!

This is the current design. To avoid spam, we show the alerts above the chat list only for 
(a) known contacts and  
(b) messages from other Delta Chat clients.  
Messages from unknown/non-Delta do not appear automatically in the list. We consider renaming the "Contact requests" menu entry to "E-Mails" to make things clearer, and, in general, this is still subject to changes. So, _simply_ ideas are very welcome :)

**Comment by testbird** [comment] 2018-01-05 18:43
The idea sounds reasonable, just looks like there is still a problem in who is considered as known, as I've been prompted for example about an order confirmation email.

BTW maybe we better distinguish between prompting, notification (show number unread), alert (with sound)?

**Comment by testbird** [comment] 2018-01-05 19:24
Mind that csb0730 was missing the notification about (unread count for) new contact requests "Non-Chat Messages"?

And I tend to think a practical way (that also solves the notification options in a natural way) would be to re-enable the option to show the Non-Chat Messages in the chats list (but with a "?" as icon ;-).

**Comment by testbird** [comment] 2018-01-05 21:07
For the prompting, what would you think about showing a little more of the message (maybe up to 300 chars?) in a bubble (just like in a chat), so that one can better decide to read all/answer or dismiss.

**Comment by r10s** [comment] 2018-01-05 22:07
> For the prompting, what would you think about showing a little more of the "Non-Chat Message?" (maybe up to 300 chars?) in a bubble (just like in a chat), so that one can better decide to read all/answer or dismiss.

Sounds good, however, I think fist of all, we have to figure out what to show when and how. The UI can be optimized later (if there are resources left then :)

**Comment by testbird** [comment] 2018-01-05 23:16
All right, rename this issue to re-introduce option to show "Non-Chat Messages?" in chat list?

**Comment by testbird** [comment] 2018-01-06 16:23
> I think fist of all, we have to figure out what to show when and how

Please review:
https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy
https://github.com/deltachat/deltachat-core/wiki/Use-Cases

**Comment by csb0730** [comment] 2018-01-09 00:11
Hello Guys,
it's not ok so see really nothing regarding new messages in "Contact Requests". Most of my colleagues uses standard MUA and it's important to get informed about new messages from these (new) contacts.
Please reintroduce a possibility to get an alert in some way from "Contact Requests"!

Proposal:
User option to get an alert from that or not (simple and clear!).

For me it's not a problem to get some (few in my case) unwanted emails. IMHO: Because we're using email as backbone there will not be a perfect solution about that. For me it's much more angry NOT to see a message!

**Comment by testbird** [comment] 2018-01-09 09:07
@csb0730 Re-introducing the "show (CR) contact requests in chat list" as "(...) Email log" is the first option suggested in the use cases wiki document.

> - [ ] 1) show browse-able (...) Email Log (formerly contact requests) in chat list

I would be interested to know how you think the use cases are covered over all.

(As a workaround for now, you could install K-9 email client to get notifications.)

**Comment by testbird** [comment] 2018-01-09 09:34
Why not show the "(...) Email Log" item in the chat list by default, and let the user hide the emails in DC if he uses another MUA? (Option: Hide (...) Email Log in chats menu.)

**Comment by csb0730** [comment] 2018-01-15 20:58
@testbird I don't understand exactly what You want to describe. I do have installed K9 in parallel all the time but I'm using it only less regularly (e.g. once a day). Most of communication meanwhile I'm doing with DC :-)

But, in general: What's the problem in generating an alert for new messages (all MUA) in CR?

Nevertheless IMHO it would be very welcome to use the CR _inbox_ more "email like".

I don't wan to start now a discussion to have "virtual chats" or "folders" and use manual move functions for that from CR. There may be use cases where You have only onetime short communication and automatic mapping of messages is quite not possible!

**Comment by testbird** [comment] 2018-01-15 22:53
What I think I understood is, when you were missing an "alert" you actually mean some form of basic, non-attention stealing visualization/notice like the number of unread messages shown for a chat (thread). I don't think there is a general problem with it. Only unfortunately, this visualization/notice is now missing because the introduction of the new message prompting also removed the option to "show contact requests (email log) in chat list". The problem is that the prompting is only done for **known** contacts, while the removed option showed new messages from **unknown** contacts, so we are now missing something.

My proposal (use cases wiki) relates to this issue by supporting:
* To chat in reply to **unknown** contacts: Reintroduce the old option "show contact requests (under the new name email log) in chat list", and enable it by default. This would then silently show the number of new unread messages from the email log in the chat list, so users get an overview how DC sorts out chats and emails, and can easily browse their emails and respond to emails if desired. After all, answering a message is the only active way in DC to make a unknown contact a known contact. The email log in the chat list would also allow you to configure playing a sound on new emails, if you really want this kind of loud alert, in the same way as for regular chats. If one prefers to use another email program (MUA), instead of the email log, to browse the emails, one can disable the "show email log in chat list" option in the global preferences. To make removing the email log from the chat list even easier, the option could also be available in the preferences of the email log itself, and instead of the delete chat option upon long press of the email log in the chat list.

* To chat in reply to **known** contacts: The "open chat?" prompt could later possibly even become the same/get merged with regular chats: I.e. add an "X" to allow to quickly delete a chats that have not been opened yet. This allows to show a number of "prompts" (list of new chats to delete or enter) together with the message count. (Avoids serialization and possibly hiding/seeing important messages only after dismissing uninteresting ones.)

**Comment by testbird** [comment] 2018-01-16 16:14
Concerning K9 in parallel, I thought it could give you notice (even with sound) about every new email, until this issue is fixed in DC.

**Comment by csb0730** [comment] 2018-01-21 01:26
If I read all this I think we have a more or less inconsistent behaviour. Additionally meanwhile I saw some alerts at my phone with grey bar for chat request at top of the chat list even from unknown addresses (contacts)!

I understood that
- every message from unknown contact is arriving in "contact requests" and
- there are so called "known contacts" with which no chat is started (!) - these contacts are collected by cc's of known contacts (if a message from such a contact arrives: is that not shown in contact requests?)
- both of them can be sent from DC or other MUA.

I think, the easiest way to get a clear behaviour is: not to distinguish between _known_ and _unknown_ contacts, better to distinguish only between "chat with contact is established" or "no chat with contact exists".

**Comment by testbird** [comment] 2018-01-21 07:35
> meanwhile I saw some alerts at my phone with grey bar for chat request at top of the chat list even from unknown addresses (contacts)!

As this sometimes also happened here, I also suspect there might still be an inconsistency/bug #225 (should be reopened) in the current implementation. @devs Is there a date saved for known contacts to help finding how they where gathered?

> * "known contacts" with which no chat is started

I think this happens, if one answers "never" to open a chat. Not sure if the user can get a list of these?

> better to distinguish only between "chat with contact is established" or "no chat with contact exists".

That sounds quite similar to "chat gets opened" and "no chat gets opened", but these are actually the target states, for which the address based criteria is needed to sort the messages: https://delta.chat/en/help#which-messages-do-appear-in-delta-chat

**Comment by Ampli-fier** [comment] 2018-01-21 12:31
> Is there a date saved for known contacts to help finding how they where gathered?

There is no date saved. From the order of the contact entries in the database, one can probably derive when the contact was saved.

Instead the "origin" is saved in the database, [see](https://github.com/deltachat/deltachat-core/blob/9e8a2c64be55e848ee548acdc7b93cd2fd7c209c/src/mrcontact-private.h#L59).

The values are in decimal in the database.

To look for contacts **not** originated from the phone's address book, run:
`sqlite3 messenger.db "select name,addr,origin from contacts where id>9 AND origin != 524288;"`

Instead of 'messenger.db' one can use a backup file instead.

**Comment by testbird** [comment] 2018-01-23 19:21
>>    Is there a date saved for known contacts to help finding how they where gathered?

> There is no date saved. From the order of the contact entries in the database, one can probably derive when the contact was saved

Uh, that looks not easily to understand to me, and very unfortunate for tracing reverting wrong contact status changes (https://github.com/deltachat/deltachat-android/issues/240).

Idea: Couldn't that maybe better be references to message IDs that triggered the status, instead of decimal encodings?

The untraceable levels may have to do with the the errors in showing/not-showing messages mentioned here and for example at https://github.com/deltachat/deltachat-android/issues/239.

**Comment by csb0730** [comment] 2018-08-16 21:26
Request for that again because it is annoying to look manually for new email in Contact Requests.

**Comment by testbird** [comment] 2018-08-16 22:13
Yes unfortunately there are v1.0 blockers, plenty of usage annoyances (this issue included -> see wiki pages), important perception improvements, and then there are some nice issues to make email chats "just work".

I hope it will be possible to dedicate some more time to these issues after the summer vacations and with more devs working on the code now.

**Comment by r10s** [comment] 2018-10-25 10:41
i'm closing this for now here; the new forum at https://support.delta.chat is the better place for feature requests and discussions.

**Closed by r10s** 2018-10-25 10:41 UTC
