### ISSUE TITLE
No notification for new chat requests

### ISSUE THREAD

**Issue by marco-trovato** [deltachat/deltachat-android#2052] opened 2021-09-17 15:59 UTC
This issue affects all devices and all versions.
When a new chat request is received there is no notification.
To check the presence of new unread messages request the main window must be continuously opened manually.

This is not the expected behaviour in a messenger, i.e.: imagine WhatsApp or Gmail with no notification when receiving a new message.

(Note: having persistent background notification options activated does not change the result)

**Further information:**
- Android version: All
- Device: All
- Delta Chat version: <= v1.22.1
- Expected behavior: Notify on new chat request
- Actual behavior: Phone is silent until you manually check for new message
- Steps to reproduce the problem: Receive a new email from a new contact. The request for new message will not generate any notification, but it will be visible as new and unread request when opening the main window.
- Screenshots: None provided
- Logs: None provided

**Comment by Gh0stz0x** [comment] 2021-09-17 16:17
Hi Marco, I think this must be entered as a Feature Request in the Delta Chat support forum.
Here you can see that it is already mentioned: https://support.delta.chat/t/notify-contact-requests-lets-discuss-about-this/190 and also here: https://support.delta.chat/t/show-all-classic-emails-no-requests/1584 
So it would not be a real bug that you are ,rightly complaining about, given that to date the contact request notification has not yet been implemented. 
Unfortunately DEVs are overworked and there are no devs that can follow this request. 😒

**Comment by marco-trovato** [comment] 2021-09-17 17:57
Hello, I have read the discussion about this.

In my opinion the absence of notification when receiving a new message **is a bug**, and not a fancy feature.
i.e.:
Imagine if WhatsApp did not notify all incoming new messages.

**Comment by darhma** [comment] 2021-09-17 19:39
@marco-trovato 
I agree that the absence of notifications is to be considered more a bug than a lack of implementation or a feature. Moreover, the problem of the absence of notifications for contact requests is not only present in case you use delta chat to manage all the mails but also in the "chat only" mode.

**Comment by Gh0stz0x** [comment] 2021-09-17 19:55
@marco-trovato I don't want to downplay the importance of this feature, I too miss notifications for contact requests. 
My speech was from a technical point of view, the bug is something unwanted, here the problem is that the code part to notify it is missing. 🤷
Maybe I'm wrong, I hope the devs answer. 🤔

**Comment by r10s** [comment] 2021-09-18 11:55
there were several discussions about that in the forum - and there is also a pr now: https://github.com/deltachat/deltachat-core-rust/pull/2690 :)

**Comment by link2xt** [comment] 2021-09-19 19:30
Fixed with https://github.com/deltachat/deltachat-core-rust/pull/2690

**Closed by link2xt** 2021-09-19 19:30 UTC
