### ISSUE TITLE
Classic mail shared with Delta Chat starts chat with sender of this mail

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#1527] opened 2020-08-08 12:48 UTC
- Operating System (Linux/Mac/Windows/iOS/Android): Android 7.0
- Delta Chat Version: 1.10.5
- Expected behavior: show all chats to share a message from k9 mail
- Actual behavior: Delta Chat starts a new chat with the receiver address
- Steps to reproduce the problem:

1. receive a mail in K9 to ReceiverAddressInK9@provider.org
2. open this messag
3. press "share"
4. choose "Delta Chat" in the now opened share menu
5. Now Delta Chat shows not as expected all current chats. It starts a new chat with ReceiverAddressInK9@provider.org

Probably is a issue in k9. But maybe you can fix that in Delta Chat by stripe out the address (ReceiverAddressInK9@provider.org) and show always all current chats.

BTW. in all other messengers it works fine as expected.

**Comment by Hocuri** [comment] 2020-08-09 08:06
> BTW. in all other messengers it works fine as expected.

It would be hard for Telegram to send a message to an email address :wink:

> stripe out the address

Sure we could ignore it, actually it was ignored for a long time but there was a pr changing this some months ago. But I think that it does make sense to open the correct chat directly if we receive an intent with an email address.

**Comment by webratte** [comment] 2020-08-09 08:16
I'm not sure if I understand correctly.

But I would like to have the choice where I share a a mail.
Not K9 and not DC should force me to a receiver.

Your telegram example is correct.
But in your example I can share this mail to every chat in telegram.

In my example (DC) I only can share this mail to myself.
It's a little bit stupid. 

Don't you think too?

**Comment by gerryfrancis** [comment] 2020-08-09 20:26
@webratte Slowly I get an idea what you are trying to achieve, and because you already received the message from a specific contact in K9 Mail, it does not make sense to share it with the same contact in Delta Chat again, right? Currently I guess it is not meant to share a message with Delta Chat, but the contact mail address.

**Comment by webratte** [comment] 2020-08-10 05:03
My englisch is really bad.
But I believe you got me.

Still I will try to write it in simple words what happens.

I got a mail in K9 to "AddressUsedOnlyInK9@provider.org".

If I tap "share" inside K9 and choose Delta Chat, in Delta Chat the only option is start a chat with "AddressUsedOnlyInK9@provider.org".

I have no chance to share to e.G. "DCAddressOfMyWife@provider.org".

Hopefully it's clear enough to understand what's my problem.

Thank you for your patience.

**Comment by gerryfrancis** [comment] 2020-08-10 08:26
@webratte I can reproduce the issue in FairEmail, too, and it does not make sense to me, too. ;)

> Thank you for your patience.

@webratte You are welcome, thanks for reporting.

**Comment by adbenitez** [comment] 2021-05-14 04:18
what happens is that sharing from K-9 Mail generates an `Intent` that is setting `Intent.EXTRA_EMAIL` to the address in the `To` field of the message, `EXTRA_EMAIL` is used by other apps to indicate the address to which the message should be sent, changing that would break the functionality of the apps that actually wants Delta Chat to send a message to some address.

That said this is not a bug, it is a feature request which in turn would break other use cases, so after investigating this issue and coming to a closed end, I am closing this issue, if further discussion is needed it is better to open a feature request in the forum where more users will see it.

**Closed by adbenitez** 2021-05-14 04:18 UTC
Labels: discussion

**Comment by dumblob** [comment] 2021-05-14 14:00
> That said this is not a bug, it is a feature request which in turn would break other use cases, so after investigating this issue and coming to a dead end, I am closing this issue, if further discussion is needed it is better to open a feature request in the forum where more users will see it.

I'm sorry for not opening a new issue and discussing this further here - I'm sure it's worth it :wink:.

> what happens is that sharing from K-9 Mail generates an `Intent` that is setting `Intent.EXTRA_EMAIL` to the address in the `To` field of the message, `EXTRA_EMAIL` is used by other apps to indicate the address to which the message should be sent, changing that would break the functionality of the apps that actually wants Delta Chat to send a message to some address.

How do other messengers do it then? Maybe there is other data in the intent (or maybe even other intents) and based on some heuristic one could achive the desired result in most if not all cases.

Any pointers to the K-9 source where you found the intent creation/handling? How does e.g. Signal, Telegram, and other open source clients could be a good inspiration (despite them not being email-based which might complicate things for DC).

**Comment by adbenitez** [comment] 2021-05-14 14:34
> How do other messengers do it then? Maybe there is other data in the intent (or maybe even other intents) and based on some heuristic one could achive the desired result in most if not all cases.

as others already pointed out, other messengers are not email apps, so they ignore the EXTRA_EMAIL field, asking to ignore that is like asking Telegram, etc to ignore phone numbers, and as I already said it is expected by others apps that launch email apps that this field is used, for example if an app wants you to send them a bug report via email, they don't want delta chat to show you the list of chats, they provide their email address in the EXTRA_EMAIL field and want the app to send the email to them

> Any pointers to the K-9 source where you found the intent creation/handling? 

I used an app to intercept and audit Intents: https://f-droid.org/packages/de.k3b.android.intentintercept

**Comment by adbenitez** [comment] 2021-05-14 14:45
so there is no action on our side, I recommend to open an issue in k-9 Mail repo, since it doesn't makes much sense they share the message that way, setting the To field, since you will like to share the message to other person most the time,

and by the way, had a really hard time finding the share option which is inside the Reply icon sub-menu besides "reply all" etc so who knows what that "share" is actually intended for ;)

**Comment by dumblob** [comment] 2021-05-14 15:00
Thanks for the pointer to the intent interceptor!

Just to clarify, I'm totally fine with the current situation as I'm not using this sharing (yet :wink:).

But I might have misunderstood what @webratte wrote. I thought that he tested other messangers to use the email addr shared by K-9 and FairEmail. But if the tested value was not an email addr but e.g. a phone number, then the comparison with other messangers is just totally wrong and there is nothing to discuss in here.

Could you @webratte confirm you actually meant other messangers work flawlessly with **non-email_address** data received through "sharing" from K-9/FairEmail?
