### ISSUE TITLE
Sent messages/mail does not show up in chats but end up as "saved messages"

### ISSUE THREAD

**Issue by bluebirch** [deltachat/deltachat-android#1940] opened 2021-05-26 07:16 UTC
- Android version: 10 (LineageOS 17.1)
- Device: FairPhone 3
- Delta Chat version: 1.20.2
- Expected behavior: When sending messages from Delta Chat Desktop or other mail clients, messages should show up in chats. Send copy to myself is checked in advanced settings. Messages sent from Desktop client shows up in *Saved Messages* on Android client -- and vice versa.
- Actual behavior: No outbound messages created with other clients (mail clients, Delta Chat Desktop) shows up in the chats.
- Steps to reproduce the problem:
- Screenshots: 

![Android Client](https://user-images.githubusercontent.com/4832639/119625332-5e8a3b80-be0a-11eb-9d79-92a5c491bd0b.png)

![Desktop Client](https://user-images.githubusercontent.com/4832639/119625411-7235a200-be0a-11eb-8f3c-3c85f8d63fdc.png)

- Logs:

**Comment by bluebirch** [comment] 2021-05-26 07:17
I have two accounts, a Gmail accound and an ordinary IMAP account. Neither of them work.

**Comment by gerryfrancis** [comment] 2021-05-26 08:13
@bluebirch Thank you for your report. Have you enabled "Send copy to self" in the "Advanced" settings of both Delta Chat clients? It must be enabled, otherwise sent messages are not synchronized.

**Comment by bluebirch** [comment] 2021-05-26 08:15
> @bluebirch Thank you for your report. Have you enabled "Send copy to self" in the "Advanced" settings of both Delta Chat clients? This function must be enabled, otherwise sent messages are not synchronized.

Yes. Double and triple checked now. :-)

**Comment by bluebirch** [comment] 2021-05-26 08:19
Android client is 1.20, desktop client 1.15 (latest `.deb`). Has something changed in the mail sorting logic between those versions?

**Comment by gerryfrancis** [comment] 2021-05-26 08:22
@bluebirch The core used in both clients should be equal. Please check whether self-sent messages (mails) are delivered to your mailbox or not.

**Comment by gerryfrancis** [comment] 2021-05-26 08:32
> desktop client 1.15 (latest .deb)

@bluebirch I see that there is a newer version available, please download from [here](https://download.delta.chat/desktop/v1.20.0/) and let us know if it solves your issue. Thanks!

**Comment by bluebirch** [comment] 2021-05-26 09:53
It does not.

Message sent to recipient X from Desktop client can be found on mail server (Gmail, in DeltaChat folder). It ends up in the saved messages folder on the Android client, that is, not as a message to X but as a message from myself to myself.

Two (2) return receipts are sent from myself to myself. Cannot determine if it is the Android client, the Desktop client, or both, who sends them.

**Comment by gerryfrancis** [comment] 2021-05-26 09:57
@bluebirch Please post an anonymized log file, I would like to dig into it. Thanks in advance!

**Comment by r10s** [comment] 2021-05-26 10:38
and, if you can make it, also the anonymized `.eml` file of the message in question, might be helpful.

**Comment by bluebirch** [comment] 2021-05-26 10:41
Could use some guidance hour to get everything... 😉

**Comment by r10s** [comment] 2021-05-26 10:50
the log can be found at Settings / Advanced / View log.

for the `.eml` file, you have to open your account eg. with Thunderbird, search the message and select "More / Save as ..." - a similar functionality is available in most clients, sometimes labeled "View source" or so.

**Comment by bluebirch** [comment] 2021-05-27 07:10
I sent a message from the Delta Chat Desktop Client. This is what I found in the log:

```
2021-05-27T06:32:44.397Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/e2ee.rs:77: peerstate for \"stefan@bjork.blog\" is nopreference"
2021-05-27T06:32:44.397Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:199: saving job for Smtp-thread: Job { job_id: 0, action: SendMsgToSmtp, foreign_id: 274, desired_timestamp: 1622097164, added_timestamp: 1622097164, tries: 0, param: Params { inner: {Recipients: \"stefan@bjork.blog\\u{1e}stefan.bjork@gmail.com\", File: \"$BLOBDIR/Mr.nytiw4fvo6q.axaqtjm4pl-@gmail.co\"} }, pending_error: None }"
2021-05-27T06:32:44.398Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1257: interrupt: smtp"
2021-05-27T06:32:44.399Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/scheduler.rs:283: smtp fake idle - interrupted"
2021-05-27T06:32:44.399Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1295: loading job for Smtp-thread"
2021-05-27T06:32:44.399Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/scheduler.rs:275: executing smtp job"
2021-05-27T06:32:44.399Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1094: Smtp-job #222, action SendMsgToSmtp started..."
2021-05-27T06:32:44.399Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1163: Smtp begin immediate try 0 of job #222, action SendMsgToSmtp"
2021-05-27T06:32:45.397Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1187: Finished immediate try 0 of job #222, action SendMsgToSmtp"
2021-05-27T06:32:45.397Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1144: Smtp removes job #222, action SendMsgToSmtp as it succeeded"
2021-05-27T06:32:45.397Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1295: loading job for Smtp-thread"
2021-05-27T06:32:45.398Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/scheduler.rs:281: smtp fake idle - started"
2021-05-27T06:32:46.114Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap/idle.rs:87: Idle has NewData ResponseData { raw: 4096, response: MailboxData(Exists(1998)) }"
2021-05-27T06:32:46.620Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1515: [move] detected bcc-self Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com as [Gmail]/Skickat/5926"
2021-05-27T06:32:46.620Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:199: saving job for Imap-thread: Job { job_id: 0, action: MoveMsg, foreign_id: 274, desired_timestamp: 1622097166, added_timestamp: 1622097166, tries: 0, param: Params { inner: {} }, pending_error: None }"
2021-05-27T06:32:46.621Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1248: interrupt: imap"
2021-05-27T06:32:46.622Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1577: Updating server uid"
2021-05-27T06:32:46.622Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap/idle.rs:97: Idle wait was interrupted"
2021-05-27T06:32:46.623Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:199: saving job for Imap-thread: Job { job_id: 0, action: MarkseenMsgOnImap, foreign_id: 274, desired_timestamp: 1622097166, added_timestamp: 1622097166, tries: 0, param: Params { inner: {} }, pending_error: None }"
2021-05-27T06:32:46.623Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1248: interrupt: imap"
2021-05-27T06:32:46.624Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1691: Skipping message Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com from \"[Gmail]/Skickat\" by precheck."
2021-05-27T06:32:46.624Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:734: 1 mails read from \"[Gmail]/Skickat\"."
2021-05-27T06:32:46.881Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1295: loading job for Imap-thread"
2021-05-27T06:32:46.882Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1094: Inbox-job #223, action MoveMsg started..."
2021-05-27T06:32:46.882Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:1163: Inbox begin immediate try 0 of job #223, action MoveMsg"
2021-05-27T06:32:46.887Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:734: 0 mails read from \"[Gmail]/Skickat\"."
```

Looking at the message ID, `grep` reveals the following:

```
2021-05-27T06:32:44.397Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/job.rs:199: saving job for Smtp-thread: Job { job_id: 0, action: SendMsgToSmtp, foreign_id: 274, desired_timestamp: 1622097164, added_timestamp: 1622097164, tries: 0, param: Params { inner: {Recipients: \"stefan@bjork.blog\\u{1e}stefan.bjork@gmail.com\", File: \"$BLOBDIR/Mr.nytiw4fvo6q.axaqtjm4pl-@gmail.co\"} }, pending_error: None }"
2021-05-27T06:32:46.620Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1515: [move] detected bcc-self Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com as [Gmail]/Skickat/5926"
2021-05-27T06:32:46.624Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1691: Skipping message Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com from \"[Gmail]/Skickat\" by precheck."
2021-05-27T06:32:48.173Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1556: [move] detected message Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com moved by us from DeltaChat/0 to DeltaChat/441"
2021-05-27T06:32:48.175Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1691: Skipping message Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com from \"DeltaChat\" by precheck."
2021-05-27T06:32:48.380Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1546: [move] detected message Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com moved by other device from DeltaChat/441 to INBOX/40197"
2021-05-27T06:32:48.382Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1691: Skipping message Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com from \"INBOX\" by precheck."
2021-05-27T06:33:14.846Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1546: [move] detected message Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com moved by other device from INBOX/40197 to [Gmail]/Alla mail/273046"
2021-05-27T06:33:14.847Z	core/event            	INFO		"DC_EVENT_INFO"	0	"src/imap.rs:1691: Skipping message Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com from \"[Gmail]/Alla mail\" by precheck."
```

On the Android Client, the message ends up in the saved messages folder. I can't really see this process in the log files, there are no message ids or anything, but here's the full log:

```
**This log may contain sensitive information. If you want to post it publicly you may examine and edit it beforehand.**

device=Fairphone FP3 (FP3)
android=10 (61cb3f0b72, lineage_FP3-userdebug 10 QQ3A.200805.001 61cb3f0b72)
sdk=29
memory=11M (21.29% free, 512M max)
memoryClass=192
host=lineage-buildkite
applicationId=chat.delta
app=Delta Chat 1.20.2-gplay
installer=com.android.vending
ignoreBatteryOptimizations=true
notifications=true
reliableService=false
lang=sv_SE
rtl=false

arch=64
bcc_self=1
blobdir=/data/user/0/chat.delta/files/messenger-1.db-blobs
bot=0
configured_mvbox_folder=DeltaChat
configured_sentbox_folder=[Gmail]/Skickat
database_dir=/data/user/0/chat.delta/files/messenger-1.db
database_version=76
delete_device_after=0
delete_server_after=0
deltachat_core_version=v1.55.0
display_name=Stefan Björk
e2ee_enabled=0
entered_account_settings=XXXXXXXXXXX
fetch_existing_msgs=1
fingerprint=41C27B94F05A42FAC8D8487F096457864AD78583
folders_configured=3
inbox_watch=1
is_configured=1
journal_mode=wal
key_gen_type=0
last_housekeeping=1622016190
level=awesome
mdns_enabled=1
media_quality=0
messages_in_contact_requests=21
mvbox_move=1
mvbox_watch=1
num_cpus=8
number_of_chat_messages=249
number_of_chats=22
number_of_contacts=847
private_key_count=1
public_key_count=2
scan_all_folders_debounce_secs=60
selfavatar=<unset>
sentbox_move=0
sentbox_watch=1
show_emails=2
sqlite_version=3.35.4
uptime=0h 40m 33s
used_account_settings=XXXXXXXXXXXXXXXXXXXXXX
webrtc_instance=<unset>

--------- beginning of main
05-25 17:58:09.027 11531 17136 I DeltaChat: ++++++++++++++++++ FetchWorker.doWork() started ++++++++++++++++++
05-25 17:58:09.028 11531 17136 I DeltaChat: ++++++++++++++++++ ApplicationDcContext.maybeStartIo() ++++++++++++++++++
05-25 17:58:09.048 11531 16872 I DeltaChat: src/context.rs:156: starting IO
05-25 17:58:09.048 11531 16872 I DeltaChat: src/context.rs:158: IO is already running
05-25 17:59:09.094 11531 17136 I DeltaChat: ++++++++++++++++++ FetchWorker.doWork() will return ++++++++++++++++++
05-25 17:59:09.131 11531 11591 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=9cc2f59f-c3cc-48f2-9d04-7bbd86eeb1bf, tags={ org.thoughtcrime.securesms.connect.FetchWorker } ]
--------- beginning of system
05-27 07:48:37.535 13390 13390 D TextClassifierService: No configured system TextClassifierService
05-27 08:35:22.416 13390 13390 I PassphraseRequiredActionBarActivity: onDestroy()
05-27 08:35:22.512 13390 13390 I DeltaChat: ++++++++++++++++++ first ForegroundDetector.onActivityStarted() ++++++++++++++++++
05-27 08:35:22.512 13390 13390 I DeltaChat: ++++++++++++++++++ ApplicationDcContext.maybeStartIo() ++++++++++++++++++
05-27 08:35:22.582 13390 15722 I DeltaChat: src/context.rs:156: starting IO
05-27 08:35:22.582 13390 15722 I DeltaChat: src/context.rs:158: IO is already running
05-27 08:35:22.589 13390 22148 I DeltaChat: calling maybeNetwork()
05-27 08:35:22.596 13390 22148 I DeltaChat: maybeNetwork() returned
05-27 08:35:22.603 13390 15722 I DeltaChat: src/scheduler.rs:283: smtp fake idle - interrupted
05-27 08:35:22.604 13390 13390 I PassphraseRequiredActionBarActivity: onResume()
05-27 08:35:22.609 13390 15722 I DeltaChat: src/job.rs:1295: loading job for Smtp-thread
05-27 08:35:22.612 13390 15722 I DeltaChat: src/imap/idle.rs:97: Idle wait was interrupted
05-27 08:35:22.612 13390 15722 I chatty  : uid=10157(chat.delta) eventThread identical 1 line
05-27 08:35:22.614 13390 15722 I DeltaChat: src/imap/idle.rs:97: Idle wait was interrupted
05-27 08:35:22.637 13390 15722 I DeltaChat: src/scheduler.rs:281: smtp fake idle - started
05-27 08:35:23.060 13390 15722 I DeltaChat: src/job.rs:1295: loading job for Imap-thread
05-27 08:35:23.522 13390 15722 I DeltaChat: src/imap.rs:734: 0 mails read from "DeltaChat".
05-27 08:35:23.523 13390 15722 I DeltaChat: src/imap.rs:734: 0 mails read from "[Gmail]/Skickat".
05-27 08:35:23.672 13390 15722 I DeltaChat: src/imap.rs:734: 0 mails read from "INBOX".
05-27 08:35:23.673 13390 15722 I DeltaChat: src/imap/scan_folders.rs:26: Starting full folder scan
05-27 08:35:23.878 13390 15722 I DeltaChat: src/imap/idle.rs:71: DeltaChat: Idle entering wait-on-remote state
05-27 08:35:23.917 13390 15722 I DeltaChat: src/imap/idle.rs:71: [Gmail]/Skickat: Idle entering wait-on-remote state
05-27 08:35:24.370 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder BRF Plogen
05-27 08:35:24.828 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Familj
05-27 08:35:25.447 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Familj/Becca
05-27 08:35:26.053 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Familj/Erika
05-27 08:35:26.668 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Familj/F&APY-r&AOQ-ldrarna
05-27 08:35:27.138 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Familj/Jenny
05-27 08:35:27.724 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder IKSU kampsport
05-27 08:35:28.186 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder London 2019
05-27 08:35:28.647 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Ra&Awg-kningar &- kvitton
05-27 08:35:29.052 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Resor
05-27 08:35:29.512 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Sent
05-27 08:35:29.971 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Skola &- fritid
05-27 08:35:30.579 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder S&APY-ka bostad
05-27 08:35:31.221 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder S&APY-ka jobb
05-27 08:35:31.651 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Trash
05-27 08:35:32.268 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick
05-27 08:35:32.723 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick/DiEM25
05-27 08:35:33.181 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick/Genuslistan
05-27 08:35:33.554 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick/Handelsbanken
05-27 08:35:33.899 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick/IKSU
05-27 08:35:34.317 13390 13673 D OpenGLRenderer: endAllActiveAnimators on 0x7538495c00 (RippleDrawable) with handle 0x75572adf40
05-27 08:35:34.356 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick/IKSU Kampsport
05-27 08:35:34.801 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick/Newsletter of Phenomenology
05-27 08:35:35.077 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick/Nintendo
05-27 08:35:35.535 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick/Psykologf&APY-rbundet
05-27 08:35:35.986 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick/UHSK
05-27 08:35:36.263 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder Utskick/Ume&AOU- b&AOU-gskytteklubb
05-27 08:35:36.717 13390 15722 W DeltaChat: src/imap/scan_folders.rs:67: Can't fetch new msgs in scanned folder: No UIDVALIDITY for folder [Gmail]
05-27 08:35:37.532 13390 15722 I DeltaChat: src/imap.rs:1546: [move] detected message Mr.d8MiyrmRqUL.qlHoTxie6av@gmail.com moved by other device from [Gmail]/Skickat/5927 to [Gmail]/Alla mail/273047
05-27 08:35:37.532 13390 15722 I DeltaChat: src/imap.rs:1577: Updating server uid
05-27 08:35:37.543 13390 15722 I DeltaChat: src/job.rs:199: saving job for Imap-thread: Job { job_id: 0, action: MarkseenMsgOnImap, foreign_id: 601, desired_timestamp: 1622097337, added_timestamp: 1622097337, tries: 0, param: Params { inner: {} }, pending_error: None }
05-27 08:35:37.553 13390 15722 I DeltaChat: src/job.rs:1248: interrupt: imap
05-27 08:35:37.553 13390 15722 I DeltaChat: src/imap.rs:1691: Skipping message Mr.d8MiyrmRqUL.qlHoTxie6av@gmail.com from "[Gmail]/Alla mail" by precheck.
05-27 08:35:37.553 13390 15722 I DeltaChat: src/imap.rs:1546: [move] detected message Mr.YJLwedCY26Q.jEuaTkWFNZX@gmail.com moved by other device from [Gmail]/Skickat/5928 to [Gmail]/Alla mail/273048
05-27 08:35:37.553 13390 15722 I DeltaChat: src/imap.rs:1577: Updating server uid
05-27 08:35:37.559 13390 15722 I DeltaChat: src/job.rs:199: saving job for Imap-thread: Job { job_id: 0, action: MarkseenMsgOnImap, foreign_id: 602, desired_timestamp: 1622097337, added_timestamp: 1622097337, tries: 0, param: Params { inner: {} }, pending_error: None }
05-27 08:35:37.567 13390 15722 I DeltaChat: src/job.rs:1248: interrupt: imap
05-27 08:35:37.567 13390 15722 I DeltaChat: src/imap.rs:1691: Skipping message Mr.YJLwedCY26Q.jEuaTkWFNZX@gmail.com from "[Gmail]/Alla mail" by precheck.
05-27 08:35:37.574 13390 15722 I DeltaChat: src/imap.rs:734: 2 mails read from "[Gmail]/Alla mail".
05-27 08:35:38.307 13390 13390 I PassphraseRequiredActionBarActivity: onPause()
05-27 08:35:38.322 13390 13390 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@893bf18
05-27 08:35:38.333 13390 13390 W PassphraseRequiredActionBarActivity: onCreate(null)
05-27 08:35:38.352 13390 13390 I PassphraseRequiredActionBarActivity: onResume()
05-27 08:35:38.436 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder [Gmail]/Chattar
05-27 08:35:38.883 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder [Gmail]/Papperskorgen
05-27 08:35:39.337 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder [Gmail]/Skr&AOQ-ppost
05-27 08:35:39.800 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder [Gmail]/Stj&AOQ-rnm&AOQ-rkta
05-27 08:35:40.711 13390 15722 I DeltaChat: src/imap.rs:734: 0 mails read from "[Gmail]/Utkast".
05-27 08:35:41.324 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder [Gmail]/Viktigt
05-27 08:35:41.911 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder temp
05-27 08:35:42.070 13390 13403 W chat.delta: Reducing the number of considered missed Gc histogram windows from 160 to 100
05-27 08:35:42.351 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder &ANY-vrigt
05-27 08:35:42.826 13390 15722 I DeltaChat: src/imap.rs:663: No new emails in folder &ANY-vrigt/Husbygge
05-27 08:35:42.935 13390 13390 I PassphraseRequiredActionBarActivity: onPause()
05-27 08:35:42.944 13390 13390 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@a4d278a
![](@attachment/Re_ Meddelande från me@maildomain.com.eml)
```

The last line is me exporting the message from FairMail... with the following content (the EML file):

```
Bcc: me@maildomain.com
Return-Path: <me@maildomain.com>
Received: from [127.0.0.1] (c80-216-143-104.bredband.tele2.se. [80.216.143.104])
        by smtp.gmail.com with UTF8SMTPSA id f3sm109466lfu.271.2021.05.26.23.32.44
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Wed, 26 May 2021 23:32:44 -0700 (PDT)
Content-Type: text/plain; charset=utf-8; format=flowed; delsp=no
Chat-Disposition-Notification-To: me@maildomain.com
Subject: =?utf-8?q?Re=3A_Meddelande_fr=C3=A5n_XXXXXX
MIME-Version: 1.0
References: <Mr.0QjSFh-XUmS.tj2vVs5ZJnx@gmail.com>
	<Mr.dM6crEU09G0.ISm3PN-aYOm@other.maildomain.com>
In-Reply-To: <Mr.dM6crEU09G0.ISm3PN-aYOm@other.maildomain.com>
Date: Thu, 27 May 2021 06:32:44 +0000
Chat-Version: 1.0
Autocrypt: addr=me@maildomain.com;
	keydata=XXXXXXXXXXXXX
Message-ID: <Mr.nYtIW4fVo6q.AXaQtjM4PL-@gmail.com>
To: =?utf-8?q?Stefan_Bj=C3=B6rk?= <me@other.maildomain.com>
From: <me@maildomain.com>

This message is sent to me@maildomain.com from Delta Chat Desktop.

-- 
Skickat från Delta Chat: https://delta.chat
```

**Comment by gerryfrancis** [comment] 2021-05-27 12:45
@bluebirch Thanks for submitting the logs, much appreciated. What I can see is that, after Delta Chat for Desktop sent a mail via SMTP successfully, it is found in the sent folder `[Gmail]/Skickat`. Delta Chat usually does not deliver any sent messages to the Sent folder. This could be a duplicate of https://github.com/deltachat/deltachat-core-rust/issues/2220 and maybe it is related to using Gmail.

**Comment by Hocuri** [comment] 2021-05-27 18:20
Thanks for the exported message, due to its help I could reproduce the issue! Just trying to fix it...

**Closed** 2021-05-28 18:02 UTC
