### ISSUE TITLE
crash after tapping at location icon in chat view in Android 4.1.2

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#887] opened 2019-05-01 22:04 UTC
v0.200.0
compiled from github sources
Samsung S3 mini
Android 4.1.2

Not shure if this issue is still existing in current version but I want to inform about.

See log excerpt:
[logcat-dc-crash-after-enable-locat-streaming.txt](https://github.com/deltachat/deltachat-android/files/3136140/logcat-dc-crash-after-enable-locat-streaming.txt)

**Comment by csb0730** [comment] 2019-05-01 22:06
See line
`05-01 23:17:47.926  6883  6883 E AndroidRuntime: FATAL EXCEPTION: main`

**Comment by r10s** [comment] 2019-05-01 23:44
again an android 4 issue, and i am sure, this won't be the last. it's just that android 4 has various bugs on its own, deltachat is typically not tested on these devices as it is not in use by any maintainers. i tend to stop supporting this until we have a reasonable way to check bugs here. so, if someone has some android 4 devices left please send them to https://delta.chat/en/imprint :)

**Comment by r10s** [comment] 2019-05-01 23:48
@csb0730 you have and android4 device? and can compile delta on your own? maybe you can take a bit care of such bugs in the future and provide pr as needed? most android4-bugs is just some xml that is not understood and needs some tweaking - see the past pr of the last weeks.

**Comment by csb0730** [comment] 2019-05-03 06:54
I'll support as much I can, sure 👍 

Will have a look into ...

**Comment by csb0730** [comment] 2019-05-03 06:57
May You give me a start point where it could be?

**Comment by r10s** [comment] 2019-05-03 10:03
i think changes are needed only in the .xml file that is inflated from within MapActivity

**Comment by cyBerta** [comment] 2019-05-06 08:49
I have an android 4 device and can fix that

**Comment by cyBerta** [comment] 2019-05-06 10:25
Could not reproduce with current version 0.303 on Android 4.1.2 emulator. @csb0730 Could you please retest with the new version?

**Comment by r10s** [comment] 2019-05-06 13:51
also checked this again, works without crashes. there are some minor positioning glitches, some missing margings or margins that are too small in 4.1.2, however, this is not really problematic and i'd say it's not worth to target them (would be probably come at cost of maintainability of the "newer" systems).

closing this for now.

**Comment by csb0730** [comment] 2019-05-20 23:36
Will rebase my testing code to current version next days and test again. I'll let you know about.

**Comment by csb0730** [comment] 2019-06-14 22:47
checked again with v0.304.0 -> same behaviour:

- tapping on location icon in chat view's headline => crash
- tapping on menu->"show all locations" => crash

@r10s this issue should be reopened

**Comment by csb0730** [comment] 2019-06-14 23:08
here a log excerpt while crash and next restart of the app.
maybe this helps to detect what's going wrong.
[crash-when-loc-function-use.txt](https://github.com/deltachat/deltachat-android/files/3292449/crash-when-loc-function-use.txt)

**Comment by r10s** [comment] 2019-06-16 08:06
this is again an Android 4.x error :/
it should be fixed before location-streaming get out of the experimental state, however, up to then i think this has not the highest priority.

**Comment by r10s** [comment] 2019-06-17 22:25
closed by https://github.com/deltachat/deltachat-android/pull/954

**Closed by r10s** 2019-06-17 22:25 UTC
Labels: android4, bug
