### ISSUE TITLE
Backup import

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#179] opened 2017-10-14 11:38 UTC
Importing seems to wrongly confirm the export, instead of the import. ;-)

---
Sent with the Free Software's mobile email messenger. https://delta.chat

**Comment by testbird** [comment] 2017-10-14 11:39
Oh, everything else seemed to work. :-)

**Comment by testbird** [comment] 2017-10-14 11:53
The import option shown during setup was not able to import exported keys.

Key import only worked through the settings after new keys were auto-generated.
The initial import dialog should probaby just also accept exported keys.

**Comment by r10s** [comment] 2017-10-14 12:41
> Importing seems to wrongly confirm the export, instead of the import. ;-)

I just had a look at the strings but I did not found the bad string. Can you give me a more detailed hint?

> Nope, the import option shown during setup was not able to import exported keys.

This is by design. The "Import backup" function can import a backup, not single keys (which can be done any time later at "settings/advanced/manage keys")

**Comment by testbird** [comment] 2017-10-14 13:21
Retried and the mixed up string is in the key import success message, it talks about exported files.

The problem with the later key imports is the buildup of unessesarry and never used keys during reinstalls/setup.
Also supporting import of the key-only files during setup could avoid further necessity for key management (and setup repair/cleanup).

**Comment by r10s** [comment] 2017-10-14 14:34
> Retried and the mixed up string is in the key import success message, it talks about exported files.

Ah, okay, thank you very much. I've modified this to just show a "Done" hint on import, see 
https://github.com/deltachat/deltachat-android/commit/5a428458b53bcb0975ff1bbcac7f822b4e61ade3

Regarding key import during setup: This advanced usecase is out of scope of the onboarding process. Esp. if the setup message is supported (see https://github.com/deltachat/deltachat-core/issues/35 ), it is not required for the "normal" user to import keys. So I think some expert options in the advanced menu are okay here, at least for now, to keep the code simple :)

**Comment by testbird** [comment] 2017-10-14 20:58
I had thought it would be a part of the proper error checking. As easy as "if a full backup file is not found ~~return error~~ try running the key import code".

If the key creation code, avoids creating a key, if one already exists, all use cases should be fine and delta chat never create unwanted/unneeded keys. Experts that just want to import the key they use elsewhere with delta chat can do so, and it should also work on machines where a gpg key is already installed/created before delta chat runs the first time.

**Comment by r10s** [comment] 2017-10-14 22:19
But even if there is a single key file, it may belong to a different email account, or it may be an old key that was not deleted, or a key from another app ... so importing keys independently of the rest of the user data may get complicated. I think the use case for the "normal" user is a backup - playing around with keys is an advanced use case.

But maybe we should make the difference between "Manage private keys" and "Backup" more clear in the dialog:
 - "Manage private keys" is mainly for working together with other, maybe even non-autocrypt, PGP-programs. Keys that should be imported may also be created by other apps! And exported keys may be used by other apps. This may get very complicated, and for special key formats, not even working at all. This is an advanced use case.
- "Backup" is for transferring data and settings between Delta Chat apps. A backup cannot be transferred to other apps. This is a normal use case.

**Comment by r10s** [comment] 2017-10-14 22:46
To make the difference clearer, an idea might be to change the dialog as follows:

**Before:**

![before](https://user-images.githubusercontent.com/9800740/31579945-2b76b300-b142-11e7-95ae-1c361a21a0a9.png)

**After:**

![after](https://user-images.githubusercontent.com/9800740/31579948-3693ab3a-b142-11e7-8eec-ec423ee9e2d4.png)

**Comment by testbird** [comment] 2017-10-15 10:51
I'd see no need to make the dialog more complicated and less structured.

The dialog looks good to me as it is, maybe the word "Manage" is not neccessary. Just offer export and import for "Encryption keys (.asc)" and "Full backup (keys, config, messages)"


> even if there is a single key file, it may belong to a different email account, ...

Ok, that's true. Automaticaly importing a key is not that good.

The use case that is not so well covered, I think, is cleaning up a messed up install (possibly after a bug with synchronizing the DB with the server). Something one can tell a random bug reporter to do to recover. For example, I wanted to start clean after messing around on the IMAP server, but keep using the same key. However, every time I import a key (after the initial setup) I increase the number of installed keys (with the current code).

Making the "import encryption keys (.asc)" option available during the inital setup, below the "import backup" option should solve this.

**Comment by testbird** [comment] 2017-10-15 11:04
> every time I import a key (after the initial setup) I increase the number of installed keys
Which is the right thing to do by default, because it is a later, additional import.

My idea is that a more sophisticated import dialog (add/replace) can be avoided by alternatively offering the key import before a key is created (if none exists).

**Comment by testbird** [comment] 2017-10-15 11:10
BTW: In the advanced settings, maybe make the first section header "Account settings" also more distinguishable (blue) like the second section header "Export and import".

**Comment by r10s** [comment] 2018-03-11 18:08
closed, see https://github.com/deltachat/deltachat-core/issues/132 about ideas to import the setup on startup.

**Closed by r10s** 2018-03-11 18:08 UTC
