### ISSUE TITLE
Missing notifications

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1328] opened 2020-05-01 12:49 UTC
- Android version: 9 and 7
- Device: Fairphone 3 and Moto G3
- Delta Chat version:1.6.0
- Actual behavior: There are no chat notifications (permanent notification is shown)
- Steps to reproduce the problem:
  - Log into DC with one account
  - Switch account to a second account
  - If you still get notifications, switch to the first account again
  - No notifications (but you can see that the Core received the message in the logs)

  What I found out so far:
  - definitely happens with testrun.org and gmx
  - No notifications, both when the messages are sent from normal MUA and DC
  - doesn't happen with 1.3.0 (Update: No surprise, 1.3.0 did not have account switching)
- Screenshots:
- Logs: (you can definitely see how the core receives the message here)
```

2020-05-01 10:39:34.494 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:37.510 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 20 lines
2020-05-01 10:39:37.511 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:37.793 25400-25693/? I/DeltaChat: ThreadId(47) src/imap/idle.rs:94: Idle has NewData
2020-05-01 10:39:37.900 25400-25693/? I/DeltaChat: ThreadId(47) src/job_thread.rs:179: MVBOX-IDLE ended...
2020-05-01 10:39:37.905 25400-25693/? I/DeltaChat: ThreadId(47) src/job.rs:1038: dc_perform_mbox_jobs EMPTY (for now).
2020-05-01 10:39:37.907 25400-25693/? I/DeltaChat: ThreadId(47) src/job_thread.rs:105: MVBOX-fetch started...
2020-05-01 10:39:37.916 28430-28430/? W/qcom-system-dae: type=1400 audit(0.0:12686): avc: denied { read write } for name="diag" dev="tmpfs" ino=17517 scontext=u:r:vendor_qcomsysd:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=0
2020-05-01 10:39:37.928 28430-28430/? E/QCOMSysDaemon: Can't find/open bootselect node: (No such file or directory)
2020-05-01 10:39:37.928 28430-28430/? I/QCOMSysDaemon: Starting qcom system daemon
2020-05-01 10:39:37.928 28430-28430/? E/Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
2020-05-01 10:39:37.928 28430-28430/? E/QCOMSysDaemon:  Diag_LSM_Init failed : 0
2020-05-01 10:39:38.265 25400-25693/? I/DeltaChat: ThreadId(47) src/dc_receive_imf.rs:42: Receiving message DeltaChat/3028...
2020-05-01 10:39:38.344 25400-25693/? I/DeltaChat: ThreadId(47) src/e2ee.rs:236: Detected Autocrypt-mime message
2020-05-01 10:39:38.401 25400-25693/? W/DeltaChat: ThreadId(47) src/mimeparser.rs:419: Ignoring nested protected headers
2020-05-01 10:39:38.403 25400-25693/? I/DeltaChat: ThreadId(47) src/dc_receive_imf.rs:1141: not creating ad-hoc group: too few contacts
2020-05-01 10:39:38.426 25400-25693/? I/DeltaChat: ThreadId(47) src/dc_receive_imf.rs:671: Message has 1 parts and is assigned to chat #Chat#429.
2020-05-01 10:39:38.426 25400-25693/? I/DeltaChat: ThreadId(47) src/dc_receive_imf.rs:215: received message 3028 has Message-Id: Mr.k4kxVA36HVj.P2REXFd5YXc@gmx.de
2020-05-01 10:39:38.446 25400-25693/? I/DeltaChat: ThreadId(47) src/imap/mod.rs:662: 1 mails read from "DeltaChat".
2020-05-01 10:39:38.582 25400-25693/? I/DeltaChat: ThreadId(47) src/imap/mod.rs:597: fetch_new_messages: ignoring uid 3028, last seen was 3028
2020-05-01 10:39:38.583 25400-25693/? I/DeltaChat: ThreadId(47) src/imap/mod.rs:662: 0 mails read from "DeltaChat".
2020-05-01 10:39:38.583 25400-25693/? I/DeltaChat: ThreadId(47) src/job_thread.rs:112: MVBOX-fetch done in 675 ms.
2020-05-01 10:39:38.586 25400-25693/? I/DeltaChat: ThreadId(47) src/job_thread.rs:177: MVBOX-IDLE started...
2020-05-01 10:39:38.693 25400-25693/? I/DeltaChat: ThreadId(47) src/imap/idle.rs:91: Idle entering wait-on-remote state
2020-05-01 10:39:41.206 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:42.540 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 16 lines
2020-05-01 10:39:42.540 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:42.931 28433-28433/? E/QCOMSysDaemon: Can't find/open bootselect node: (No such file or directory)
2020-05-01 10:39:42.932 28433-28433/? I/QCOMSysDaemon: Starting qcom system daemon
2020-05-01 10:39:42.916 28433-28433/? W/qcom-system-dae: type=1400 audit(0.0:12687): avc: denied { read write } for name="diag" dev="tmpfs" ino=17517 scontext=u:r:vendor_qcomsysd:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=0
2020-05-01 10:39:42.934 28433-28433/? E/Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
2020-05-01 10:39:42.934 28433-28433/? E/QCOMSysDaemon:  Diag_LSM_Init failed : 0
2020-05-01 10:39:44.271 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:44.539 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 7 lines
2020-05-01 10:39:44.539 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:45.369 595-595/? D/ThermalHAL-TARGET: Entering get_temperatures
2020-05-01 10:39:45.369 595-595/? D/ThermalHAL-TARGET: Entering get_temperatures
2020-05-01 10:39:45.369 595-595/? D/ThermalHAL-UTIL: Entering get_temperature_for_all
2020-05-01 10:39:45.369 595-595/? D/ThermalHAL-UTIL: Entering read_temperature
2020-05-01 10:39:45.371 595-595/? I/chatty: uid=1000(system) thermal@1.0-ser identical 9 lines
2020-05-01 10:39:45.374 595-595/? D/ThermalHAL-UTIL: Entering read_temperature
2020-05-01 10:39:45.377 1757-1757/? D/PowerUI: BatteryTempWarning updateTemperatureWarning
2020-05-01 10:39:45.377 1757-1757/? D/PowerUI: BatteryTempWarning mBatteryTemp=258, mThresholdTemp=550.0, mThresholdLowTemp=0.0
2020-05-01 10:39:46.270 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:47.555 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 16 lines
2020-05-01 10:39:47.556 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:47.936 28434-28434/? W/qcom-system-dae: type=1400 audit(0.0:12688): avc: denied { read write } for name="diag" dev="tmpfs" ino=17517 scontext=u:r:vendor_qcomsysd:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=0
2020-05-01 10:39:47.946 28434-28434/? E/QCOMSysDaemon: Can't find/open bootselect node: (No such file or directory)
2020-05-01 10:39:47.946 28434-28434/? I/QCOMSysDaemon: Starting qcom system daemon
2020-05-01 10:39:47.947 28434-28434/? E/Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
2020-05-01 10:39:47.947 28434-28434/? E/QCOMSysDaemon:  Diag_LSM_Init failed : 0
2020-05-01 10:39:49.318 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:49.570 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 7 lines
2020-05-01 10:39:49.570 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:49.610 1123-2415/? D/WificondControl: Scan result ready event
2020-05-01 10:39:49.612 804-20228/? I/LOWI-8.6.0.33: [LOWI-Scan] lowi_close_record:Scan done in 6372836ms, 7 APs in scan results
2020-05-01 10:39:49.613 804-881/? I/LOWI-8.6.0.33: [LOWIUtils] responseToOutPostcard - TO: GTP-FDAL, FROM:   LOWI-SERVER, RESP:  LOWI_ASYNC_DISCOVERY_SCAN_RESULTS
2020-05-01 10:39:49.617 806-963/? W/XTCC-6.2.0.6: [WifiScanner] WiFi scan result : [7] AP's, async result: 1
2020-05-01 10:39:51.235 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:51.586 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 7 lines
2020-05-01 10:39:51.586 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:52.950 28436-28436/? E/QCOMSysDaemon: Can't find/open bootselect node: (No such file or directory)
2020-05-01 10:39:52.950 28436-28436/? I/QCOMSysDaemon: Starting qcom system daemon
2020-05-01 10:39:52.936 28436-28436/? W/qcom-system-dae: type=1400 audit(0.0:12689): avc: denied { read write } for name="diag" dev="tmpfs" ino=17517 scontext=u:r:vendor_qcomsysd:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=0
2020-05-01 10:39:52.952 28436-28436/? E/Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
2020-05-01 10:39:52.952 28436-28436/? E/QCOMSysDaemon:  Diag_LSM_Init failed : 0
2020-05-01 10:39:54.290 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:54.599 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 7 lines
2020-05-01 10:39:54.600 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:55.256 1757-1757/? D/GsensorListener: [SW_SAR] GsensorListener setTransmitPower key = 1, value = 1
2020-05-01 10:39:55.256 1757-1757/? D/TelephonyManager: [SW_SAR] Telephonymanager setTransmitPower
2020-05-01 10:39:55.257 1894-2212/? E/PhoneInterfaceManager: [PhoneIntfMgr] [SW_SAR] phone get successful
2020-05-01 10:39:55.259 2066-2066/? D/QcrilMsgTunnelIfaceManager: handleMessage what = 1
2020-05-01 10:39:55.259 2066-2066/? I/QcrilOemhookMsgTunnel: [0]invokeOemRilRequestRaw: serial=3599 length=24
2020-05-01 10:39:55.268 2066-2127/? I/QcrilOemhookMsgTunnel: [0]processOemHookResponse serial no: 3599 error: 0length=0
2020-05-01 10:39:55.269 2066-2066/? D/QcrilMsgTunnelIfaceManager: handleMessage what = 2
2020-05-01 10:39:55.297 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:56.298 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 12 lines
2020-05-01 10:39:56.298 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:56.402 1757-1757/? D/GsensorListener: [SW_SAR] GsensorListener setTransmitPower key = 1, value = 0
2020-05-01 10:39:56.402 1757-1757/? D/TelephonyManager: [SW_SAR] Telephonymanager setTransmitPower
```

**Comment by r10s** [comment] 2020-05-01 18:57
thanks for filing the issue, some more detailed / other how-to-get-this-error is at https://github.com/deltachat/deltachat-android/pull/1326#issuecomment-622314514

**Comment by Hocuri** [comment] 2020-05-02 08:49
The core probably sends an event when a notification should be shown? Which one is it?

**Comment by r10s** [comment] 2020-05-02 09:13
it is [DC_EVENT_INCOMING_MSG](https://c.delta.chat/group__DC__EVENT.html#ga3f0831ca83189879a2f224b424d8b58f)

@webratte @Hocuri all, in all, could you reproduce this issue _without_ account switching? because then, i would regard it as a minor one, account-switching is flagged as experimental. can you tell what the shortest path to get this issue is?

**Comment by Hocuri** [comment] 2020-05-02 09:30
- Log into DC with one account
  - Switch account
  - No notifications (but you can see that the Core received the message in the logs)

**Comment by Hocuri** [comment] 2020-05-02 09:31
Also updated my post above.

**Comment by Hocuri** [comment] 2020-05-02 09:35
Yes, it definitely only happens after switching accounts.

**Comment by r10s** [comment] 2020-05-02 09:44
k, then maybe this is related to #1329, but even if not, #1329 fixes an issue with account switching and should be merged in

**Comment by Hocuri** [comment] 2020-05-02 10:08
No, #1329 did not fix this.

**Comment by Hocuri** [comment] 2020-05-02 11:44
Ok, I found it out: #1330

**Comment by webratte** [comment] 2020-05-02 11:47
Yes, I can reproduce the "not picked up messages" with this setup:

-only one account
-the nightly of 01.05.2020
-imported a backup made at 29.04.2020 with one of the last nightlys before "permanent notifcations. I'm not absolutely sure which nightly exact. 

To Clarify
I installed the nightly fresh and then I imported the backup.
If it helps. I can do it again and offer a brand new log file.

**Comment by Hocuri** [comment] 2020-05-02 12:15
For whoever has this issue now: 
- Install the update as soon as it is available
- Freeze Delta Chat once with SuperFreezZ or press "Force Stop" in the settings

@webratte Are you talking about this issue here? If I definitely found and fixed a bug but is it the same that you had? (i.e. were only notifications missing or the whole messages)

If whole messages went missing, you should probably post at https://github.com/deltachat/deltachat-core-rust/issues/1412.

**Comment by webratte** [comment] 2020-05-02 12:22
No, I talk about not received messages at all. They stay in the inbox and will never pop up in DC
I answered here because @r10s asked above.
I never talked about missing notifications.
Sorry for confusing.

**Comment by r10s** [comment] 2020-05-02 12:33
@webratte yes, please open a separate issue with an exact description. we will probably do a 1.6.1 soon, so maybe even wait for that, so that things already fixed are not reported again.

@Hocuri great finding!

**Comment by webratte** [comment] 2020-05-02 12:35
I did it:
https://github.com/deltachat/deltachat-core-rust/issues/1444

**Closed** 2020-05-02 13:09 UTC
Labels: bug
