### ISSUE TITLE
Ability to import/export from custom path

### ISSUE THREAD

**Issue by MadTooth** [deltachat/deltachat-android#2634] opened 2023-08-09 05:59 UTC
_Can you add the ability to export attachments, import/export keys... (and everything else) to a custom path ?_

**Comment by adbenitez** [comment] 2023-09-25 23:08
closing here as this is a duplicate of https://support.delta.chat/t/ability-to-export-attachment-s-to-a-custom-path/2662

**Closed by adbenitez** 2023-09-25 23:08 UTC
Labels: discussion
