### ISSUE TITLE
Connection status alternating between "Connecting..."/" "Updating..."

### ISSUE THREAD

**Issue by ChrisPHL** [deltachat/deltachat-android#2228] opened 2022-03-03 16:20 UTC
Hi guys,

today I got an update via F-Droid, v. 1.28.3.
Since then DC is unable to connect to my mail server. Under 3-dots-menu --> Settings --> Connection status I can see alternating between "Connecting..."/" "Updating..."
I'm using Android Version 10 (/e/OS v. 0.22-q...)
Let me know, if you need more information about the issue.

Kind regards
Chris

**Comment by gerryfrancis** [comment] 2022-03-04 19:27
Hi @ChrisPHL , thank you for filling that issue. Please post an anonymized Delta Chat log file here, we will try to find out the cause afterwards. Thank you in advance!

**Comment by ChrisPHL** [comment] 2022-03-05 13:41
Thanks for your reply. Is there a chance to get the log files from the day before yesterday? I could find the log of the current day only.
Otherwise I fear it won't be possible to get the failure reproduced since it seemed to be gone with the sudden reception oft some messages. After that all worked fine so far which is good for me but bad for solving the issue...

Kind regards
Chris

**Comment by gerryfrancis** [comment] 2022-03-09 16:55
> Is there a chance to get the log files from the day before yesterday?

@ChrisPHL I do not think so, especially now it would not be possible.

Maybe a duplicate: https://github.com/deltachat/deltachat-core-rust/issues/2962

**Comment by adbenitez** [comment] 2022-04-03 06:16
mmh... so the issue is gone, I will close this issue until we get a log or more data, because right now not even the user reporting the issue is able to reproduce it :(

**Closed by adbenitez** 2022-04-03 06:16 UTC
Labels: needs-retry
