### ISSUE TITLE
audio message problem

### ISSUE THREAD

**Issue by elvecio** [deltachat/deltachat-android#220] opened 2017-12-16 16:18 UTC
After the last updates the audio message ( mine and from friends) does not work more. 
But I also saw that the same thing happened with  the last telegram updates.
So I really do not know if is just a deltachat problem.
Does anyone know what may have happened?
Basically, both in the deltachat and in the telegram, I see the small player for the audio messaging in the chat, but when I click this player it does not start, so I can not listen.
does anyone have this problem?

**Comment by elvecio** [comment] 2017-12-20 16:27
plz, take a look also here https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/196

**Comment by csb0730** [comment] 2017-12-30 16:47
I can confirm the same problem. Small icon to hear the message doesn't work and the wave form symbols in audio message is not shown any more.

DC v0.9.9 (f-droid version)
Android 4.1.2

A friend of mine with newer Android version is able to play the audio message.
He's using DC v0.9.9 too!

**Comment by csb0730** [comment] 2018-01-15 21:27
Update:
- Android 4.1.2 with DC v0.12.0 from github - still does not work (no change)
- Android 7.1.2 with DC v0.9.9 from f-droid - it works !

Are there any news regarding this issue?

Remark:
It is very angry to see that bug (especially in demo to possible new user) because this function is presented so clearly at input line!

**Comment by csb0730** [comment] 2018-01-21 00:14
Update:
- Android 4.1.2 with DC v0.13.0 - recording and sending of audio message works. But replaying message again at own device or playing messages received from peer devices is not possible. Message only shows the arrow to start audio but not the audio line as in older DC versions.

**Comment by r10s** [comment] 2018-02-23 17:34
Okay, I have checked this.
Telegram-FOSS has solved this by swichting back to ndk r14b, see https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commit/29f6b76bb2f8e66c257ac81c2d3b86cb74a3a76f and https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.telegram.messenger.txt

I think this is also the easiest way to go for Delta Chat; some time later one can figure out what the real problem is with the ogg library, but for now, this seems out of scope. We should: 
- adapt the readme that we really need r14b, 
- push a change to the F-Droid
- change the gradle

This will also "fix" #248

**Comment by Ampli-fier** [comment] 2018-02-24 06:34
I compiled 0.14.0 with NDK 14b and the waveform is back.
Playing the message works and also worked for me with 0.13.0 (self compiled with NDK 15 if I remember correctly).

**Comment by Ampli-fier** [comment] 2018-02-25 06:59
Closed after README update [3ecb5a4](https://github.com/deltachat/deltachat-android/commit/3ecb5a43308703b134d1f3241aa6e6507732bfcb): "dependecy on NDK 14b".

**Closed by Ampli-fier** 2018-02-25 06:59 UTC
Labels: bug

**Comment by r10s** [comment] 2018-02-26 22:03
merge request for F-Droid:
https://gitlab.com/fdroid/fdroiddata/merge_requests/2942
