### ISSUE TITLE
Changing the language direction of Luri Bakhtiari

### ISSUE THREAD

**Issue by hosseinabaspanah** [deltachat/deltachat-android#3213] opened 2024-08-06 08:21 UTC
Hello, please set the language for Luri Bakhtiari like English from left to right, because I have translated this language in Luritian script...

- Android version:14
- Device:Galaxy A23
- Delta Chat version:1.46.8
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by r10s** [comment] 2024-08-07 11:21
> because I have translated this language in Luritian script

this sounds like if there are several alphabets/scrips possible?

i am wondering if the used code `bqi` is the correct one for "Luritian script" still.

because, as far as i know, "right to left", "left to right" and other settings are not really supposed to be under control of the app but are defined in the used locale.

**Comment by hosseinabaspanah** [comment] 2024-08-12 09:49
@r10s 
Yes, there is an Arabic script for this language normally, but translation is allowed for this language and other Luri languages ​​with a special script for Luri, which is taken from Latin, and its name is Luritin...

If you want to check a program to see the status of this language and the source code of the program, look at the link below...

https://github.com/TeamAmaze/AmazeFileManager

Except for one case in which they mistakenly attributed the Luxembourg region to Luri Bakhtiari's language in this program, there is no problem with the display and arrangement from left to right for Luri Bakhtiari's language...

**Comment by r10s** [comment] 2024-08-12 11:30
thanks for the pointer, then it is what i meant, the language code is wrong. my assumptions:

- Delta Chat uses `bqi`, the system expects Arabic script and right-to-left for that
- Amaze uses `bqi-rLU`, the system expects Latin script and left-to-right for that

i will do a PR that changes the identifier for android, you should be able to download a testing file from there and can give feedback if it fixes the issue

**Comment by r10s** [comment] 2024-08-12 12:51
i created a PR that uses - the wrong, but same as Amaze - `bqi-rLU` code.

you can try that out by **setting Delta Chat's language to "Default"** - and then select "Luri Bakhtiari" in the global system settings.

selecting the language that way in Delta Chat, does not work (and would probably also not work for Amaze if there would be such an option) as it would set the locale to "Luri Bakhtiari" using region "Luxembourg" which seems to be just wrong and the latter is ignored, resulting in only setting "Luri Bakhtiari" which again is right-to-left.

otherwise, i am a bit lost here - "Luri Bakhtiari" exists in transifex in the following variations:

![Screenshot 2024-08-12 at 14 46 41](https://github.com/user-attachments/assets/8c7836de-b20a-4a69-9153-e1bb7e6d3c21)

@hosseinabaspanah is anyone of that known to use latin script?

for the locale, we are using [`setLocale()`](https://developer.android.com/reference/java/util/Locale#Locale(java.lang.String,%20java.lang.String)) that takes the [ISO_639, 2 or 3 characters](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes) and [ISO 3166, 2 characters](https://en.wikipedia.org/wiki/ISO_3166) - but it is unclear to me how that makes to "Luri Bakhtiari, latin script". as far as i understand the documentation, there is no way to force a script.

do you have another example of an app using "Luri Bakhtiari, latin script" - Amaze seems not to be a good example any may work just coincidentally using "Luxemburg" ...

**Comment by hosseinabaspanah** [comment] 2024-08-12 15:27
yes that's right...

It seems that Amaze was able to use the Latin script for this language through this region...

Unfortunately, I have not encountered this problem during all these years of translation...

I know another program in which Luri Bakhtiari's language is displayed well and I have translated it... but unfortunately the text is not open and its name is Lucky Patcher...

Regarding the language of Luri Bakhtiari in Transifex, I have to say that I don't think there is any difference between them, because I had requested the use of RTL functionality for both languages, i.e. Luri Bakhtiari and Luri Bakhtiari of Iran, and it has been applied a long time ago...

**Comment by r10s** [comment] 2024-08-14 19:28
@hosseinabaspanah if possible, can you re-check the [question from above](https://github.com/deltachat/deltachat-android/issues/3213#issuecomment-2283903100):

- use the .apk from https://github.com/deltachat/deltachat-android/pull/3228 
- set the system language to "Luri Bakhtiari"
- make sure, in Delta Chat, the language is set to "Default" (this is the default when the app is stated the first time)
- see if it is now left-to-right on your phone

there is the idea to get rid of the language selection inside Delta Chat, then there will be at least less confusion - if the steps above work, this is one more reason. otherwise, there is no actionable item left for this issue, as we cannot reproduce or do things to improve.

**Comment by r10s** [comment] 2024-08-16 14:42
>  but translation is allowed for this language and other Luri languages ​​with a special script for Luri, which is taken from Latin, and its name is Luritin

@hosseinabaspanah can you provide some sources about that? a wikipedia entry, an iso code, a page, or something? otherwise, the next user may regard using the wrong script for `bqi` as an error.

closing this now, as there is no actionable item.

once we have more detailed information, we can iterate.

**Closed by r10s** 2024-08-16 14:42 UTC
Labels: needs-feedback

**Comment by hosseinabaspanah** [comment] 2024-08-21 10:39
This case can only be solved through the translation with calligraphy based on Arabic...

Anyway, I apologize for opening and discussing this problem...
