### ISSUE TITLE
Explain how to trigger a key exchange

### ISSUE THREAD

**Issue by holgerjakobs** [deltachat/deltachat-android#293] opened 2018-04-12 17:56 UTC
0.16

**Expected behavior**
When a contact deletes and reinstalls Delta chat, my app still has his old, now invalid key, so it doesn't decrypt his messages, which show as unencryptable messages in regular mail client.

Deleting the contact would probably lead to a new key exchange. But unfortunately, deleting a contact which is "in use" is disallowed.

How to trigger a new key exchange?

Please repair!

**Comment by r10s** [comment] 2018-04-12 20:09
> How to trigger a new key exchange?

the person who cannot read a message eg. because of a new device should send a message "hey i cannot read your message, please send again" - the answer should be readable and the keys will be exchanged.

**Comment by r10s** [comment] 2018-04-13 13:34
> Is the person who cannot read a message getting an error that explains this?

currently, there are no really clear advices, this could be improved.

**Comment by testbird** [comment] 2018-04-13 14:41
Is there a current error message in the code to improve?

**Comment by r10s** [comment] 2018-04-13 15:47
not yet, but i've just modified the code to have such an error message. the following text

```
The messsage was encrypted to a different setup.

Send any message to the contact to share your new
setup; eg. ask the contact to send the message again.
```

is currently shown in the message bubble if a message cannot be decrypted. Any suggestions and improvements welcome before we give this to the translators (@comradekingu :)

**Comment by testbird** [comment] 2018-04-13 17:03
Is there another regular cause for this then a re-installation? It could be more sensible to advice the local user towards key transfer instead of asking (all) contacts (and them get accustomed) to re-sending messages to with a new key.

```
The message can not be read, because it was not encrypted for your setup. Usually 
this only happens if you use a new installation without importing a preexisting setup.

You should now import the configuration from your preexisting installation. (Using the 
"setup message" feature or the key-file export and import.)

If you write to contacts without first importing the setup for which the message 
was encrypted, you will share your new setup. This would mean all your contacts 
would have to re-verify your new setup, and your preexisting installations would not 
be able to read messages encrypted for the new installation.
```

**Comment by testbird** [comment] 2018-04-13 17:11
I modified the text to also be shown whenever DC finds non-decryptable messages on the server (after installation), and not only when viewing a new message.

**Comment by testbird** [comment] 2018-04-13 19:50
Shorter, without any explanation:

```
The messsage was encrypted for a different setup.

Import the proper setup (e.g. through a "setup message"),
or send any message to the contact to share your new setup 
(e.g. ask the contact to send the message again).
```

**Comment by r10s** [comment] 2018-04-14 09:27
> Is there another regular cause for this than a re-installation?

might be that the sender used a key from a keyserver - either an old key or an key that was uploaded by another user.

**Comment by testbird** [comment] 2018-04-14 10:04
Ok, new try:

```
A message for you was encrypted for a different setup.

If this was not by mistake of the sender, it is likely you have made a new installation and only need to transfer the preexisting setup (e.g. through a "setup message").
```

**Comment by r10s** [comment] 2018-04-14 14:27
As the text will be written directly into the mail body (the "bubble")  i would prefer `this message` over `A message`. Also, the Autocrypt Setup will only help if the recipient has really changed his setup. I think in many cases, it _is_ a mistake of the sender and this should be fixed by asking him to send the message again. This "social" approach also work if the sender does not use Autocrypt. 

My suggestion:

```
This message was encrypted for another setup.

- to share your current setup, send any message to the contact, eg. ask the contact to send the message again.

- to import another setup, send an Autocrypt Setup Message from another device with the correct setup
```

**Comment by testbird** [comment] 2018-04-14 15:49
> text will be written directly into the mail body

Makes sense then.
I think it's ok, but listing the import as first option might save some hurried users from the annoyances that arise when changing setup.

```
This message was encrypted for another setup.

- The correct setup may be imported, eg. by sending an Autocrypt Setup Message
  from the correct device to this device.

- The current setup may be used instead, by sending a new message to the
  contact, eg. asking the contact to send the message again.
```

**Comment by r10s** [comment] 2018-04-16 09:56
The term `correct` is difficult here - we do not really know (1) if the sender has encrypted to the wrong setup or (2) if the received has messed up his setup. In my experience (1) is far more frequent - eg. it is very easy in Enigmail to encrypt to the wrong key - or just do not add a key for a CC'ed recipient.

```
This message was encrypted for another setup.

- To share your current setup, send any message to the
  contact, eg. ask the contact to send the message again.

- If you have just changed your setup on another device,
  you may want to import it from there by sending an
  Autocrypt Setup Message from the other device.
```

**Comment by testbird** [comment] 2018-04-16 10:37
Yea, some basic explanation is needed. 
So I added some to the other option as well. 

```
This message was encrypted for another setup.

- If you made a new installation and possibly see this text in place of multiple messages: 
You should import the older, preexisting setup, eg. by sending an Autocrypt Setup 
Message to yourself from your first device to the second, to be able to read all your 
messages on all your devices.

- If this is only a singular unreadable message, because a sender mistakenly didn't 
encrypt for your setup: You may use and share your current setup, by sending a new 
message to the contact, eg. asking the contact to send the message again.
```

Don't you think it would make sense to list the case that happens with just DC-only users (no expert involved) first?

**Comment by r10s** [comment] 2018-04-16 11:03
> Don't you think it would make sense to list the case that happens with just DC-only users (no expert involved) first?

Not sure. I think a typical DC user has never used PGP before and uses only one device. These users may more likely be confronted with users that encrypt to an unknown key.
I think, a multi-device DC-setup is more advanced - and also more difficult to explain, so I would use it as the second point.

I like your explanations, however, maybe we can make it a little shorter:

```
This message was encrypted for another setup.

- If you made a new installation on another device:
  You can import that setup it by sending an Autocrypt Setup Message from there.

- The sender may mistakenly didn't encrypt for your setup:
  To share your current setup, send any message to the contact,
  eg. asking the contact to send the message again.
```
I dropped the hint regarding the number of messages - typically, when the users is confronted with the situation, there is only one message - more errors may follow, but the user cannot know.

I think we get closer.

**Comment by testbird** [comment] 2018-04-16 11:26
> typical DC user has never used PGP before and uses only one device.

OTOH it may also be relevant when typical users buy or switch to a new device.

**Comment by r10s** [comment] 2018-04-16 11:37
- yes, the new installation may also be on this device.
- Autocrypt Setup Messages are always sent to oneself, so there is no need for a special hint
- removed "If" from the second point - the user cannot decide, so there is no if-this-then-that advice, the "cannot read" message is the _only_ solution to solve the problem (but a simple one)
- btw. regarding that logic. it is better to keep the order as you suggested - if setup-changed, transfer setup, else ask user to send again. 
- following your suggestion regarding "a new message" (instead of "any message") 

```
This message was encrypted for another setup.

- If you made a new installation:
  You can use your preexisting setup eg. by sending an 
  Autocrypt Setup Message from your first device.

- The sender may mistakenly didn't encrypt for your setup:
  To share your current setup, send a new message to the contact,
  eg. asking the contact to send the message again.
```

Have not discussed so much about a single message :) however, i think it is worth the effort :)

**Comment by r10s** [comment] 2018-04-16 11:39
"The sender may mistakenly didn't encrypt for your setup" - not sure about the grammar btw.

**Comment by testbird** [comment] 2018-04-16 11:58
Yes, it's worth it because good advice should make things in "easy in the end" (and avoid worse problems down the road).

I used "should vs. may", to avoid users sumbling into the problems of using two keys on different devices.

To keep the "advice flow" maybe the second point could start with "Otherwise, the sender may mistakenly not have encrypted for your setup". (I think it's "have".)

```
This message was encrypted for another setup.

- If you made a new installation:
  You should use your preexisting setup, eg. by sending an 
  Autocrypt Setup Message from your first device.

- Otherwise, the sender may have mistakenly not encrypt for your setup:
  Send a new message to the contact (automatically sharing your current setup) 
  and ask the contact to send the message again.

```

**Comment by Ampli-fier** [comment] 2018-04-16 12:24
I fear it is not so obvious, what is meant by "the setup".

**Comment by r10s** [comment] 2018-04-16 12:25
@Ampli-fier This is Autocrypt-slang :) we do not want to speak about keys as this is even more abstract for unaware people.

**Comment by testbird** [comment] 2018-04-16 13:24
> (automatically sharing your current setup)

Ampli-fier is right, the use of setup in this variant is confusing. Setup should probably only refer to the private key part?

**Comment by testbird** [comment] 2018-04-16 13:32
```
This message was encrypted for another setup.

- If you made a new installation:
  You import your preexisting setup, eg. by sending an 
  Autocrypt Setup Message from your first device.

- Otherwise, the sender may have mistakenly not encrypted for your setup:
  To keep using your current setup, just send a new message to the contact
  and ask the contact to send the message again.
```

* 1st use => import
* 2nd share => keep using

**Comment by r10s** [comment] 2018-04-16 13:35
hm, i think the term setup in "This message was encrypted for another setup" and in the first point is fine. It refers to the private key (plus belonging settings).

for the second point, i am unsure. in fact, if you think of setup=privateKey, it may look confusion if you share the setup=privateKey to another user.

@testbird you were faster:) looks good, but lacks the information about that sth. is "automatically shared" - but maybe we can leave this technical detail out. it's complicated to explain.

**Comment by testbird** [comment] 2018-04-16 13:54
Should it be more clear that this is an error message? Reading error: ...?

**Comment by r10s** [comment] 2018-04-16 15:02
> Should it be more clear that this is an error message? Reading error: ...?

No, i think, this i clear enough.

**Comment by testbird** [comment] 2018-04-16 17:24
:+1:  Good, never actually saw such a generated message yet.

**Comment by r10s** [comment] 2018-04-16 18:02
looks like the following: 

![screenshot_1523901554](https://user-images.githubusercontent.com/9800740/38826685-dce2b234-41b0-11e8-87c9-ea4f4d74edd8.png)

The part "Chat: Encrypted Message" will be replaced by the real subject, if unencrypted.

I think this is _far_ better than the old text that would just read "Chat: Encrypted Message - Encrypted Message" in this example :)

**Comment by r10s** [comment] 2018-04-16 18:36
To make it more clear that the message is not written in this way by the sender, we put the string in "Editorial brackets" [these ones] as already used for the ellipses [...]

**Comment by Ampli-fier** [comment] 2018-04-16 20:06
Is there anything that can be known by DC to limit the number of root causes?

If I made a new installation, it must not mean that I still have an old "setup" that makes it possible to use Autocrypt transfer ...

This is my proposal for the "bubble text":

Chat: Encrypted message - [This message can not be decrypted]

* It might already help to simply reply to this message and ask the 
sender to send the message again.
* In case you re-installed Delta Chat or installed it on any additional 
device, read [the online help](https://delta.chat/en/help#encryption) for more information.

**Comment by Ji-eF** [comment] 2018-04-16 20:11
I would like to add the assumption that most of your future user base will not be aware of Delta encrypting feature. Not even aware of encrypting stuff at all, let alone key exchange.
Put simply : in the mind of many people (starting with my brother, my sister, my mother, ...) "Delta Chat is a chatting software, what this message is babbling about?"

**Comment by r10s** [comment] 2018-04-16 20:43
@Ampli-fier at least currently, we cannot limit the number of root causes without additional effort. i fear, a 100% correct error issue isn't possible at all.
Thinking it over again, the case another user caused the error is more likely.

@Ji-eF thank you for pointing this out again - it's true - the "normal", future delta chat user might not know that he is even encrypting. 

@Ampli-fier I like the simple, non-technical speech in your suggestion, seems to be much clearer to me. And yes - we can add a link, however, it will be printed "raw", sth like:

 ```
Encrypted Mail - [This message This message cannot be decrypted

 - It might already help to simply reply to this message and ask the
   sender to send the message again.

- In case you re-installed Delta Chat on this or another device you
   may want to transfer your setup, see https://delta.chat/en/help#encryption ]

**Comment by testbird** [comment] 2018-04-16 22:28
> - It might already help

And, unfortunately, it might also make your contacts use different keys and get things out of order... Thus, probably better to mention importing the setup and, and directly mention solutions. (Helpful advice is not puzzling. A link is still good.)

**Comment by testbird** [comment] 2018-04-16 22:36
The part `by sending an  Autocrypt Setup Message` could possibly be replaced by the actual menu steps like `through Configuration -> Send Setup Message` (or wherever that function is available).

**Comment by testbird** [comment] 2018-04-16 22:52
> If I made a new installation, it must not mean that I still have an old "setup" that makes it possible to use Autocrypt transfer ...

Right.
Slightly adapted:
```
This message was encrypted for another setup.

- If you have used another preexisting setup that is still available:
  You can import and continue using your preexisting setup, eg. by going to 
  "Configuration -> Send Setup Message" at your first device.

- Otherwise, and if the sender may not have encrypted for your setup by mistake:
  Keep using your current setup, by replying and
  asking the sender to send the message again.
```

**Comment by testbird** [comment] 2018-04-16 22:57
> most of your future user base will not be aware of Delta encrypting feature.

Yes, that's why this message is rather crucial. It can be the first contact with this feature, and the single chance to shine and explain.

**Comment by Ampli-fier** [comment] 2018-04-17 07:58
@testbird 
The average user has no idea, what **Setup** could mean. The user went to Google Play Store, installed DC and uses the app.

**Comment by testbird** [comment] 2018-04-17 08:11
> The user went to Google Play Store, installed DC and uses the app.

Sure, and the fist thing the app is used for is, if I am not mistaken, seems to be: The user configures the email setup.

Setup seems a basic word with a common meaning, nothing special. But of course the configuration in DC should make sure to also actually use the word "setup", to make it recognizable when referring to it.

**Comment by testbird** [comment] 2018-04-17 08:55
What about: `This message was encrypted for another Delta Chat setup.`

May that improve it in your sense, Ampli-fier?

**Comment by r10s** [comment] 2018-04-17 10:16
@testbird 
>> It might already help
> And, unfortunately, it might also make your contacts use different keys and get things out of order... 

worst case: if the receiver decides to import his new setup after sending a message to the contact (because he did not read the full message ...), this message will pop up again and he can "repair" the keys by sending a key again.
in the majority of cases, the user will see the message when he has not changed his setup and the message will fix the problem immediately. 

> Thus, probably better to mention importing the setup and, and directly mention solutions. (Helpful advice is not puzzling. A link is still good.)

The other device may be a non-delta-client, so instruction will probably get too long, I think @Ampli-fier suggestion (https://github.com/deltachat/deltachat-android/issues/293#issuecomment-381742870) is still fine.

**Comment by r10s** [comment] 2018-04-17 11:30
this is what the message looks like in delta then; btw. maybe a direct link is not a good idea as this may make it easier for phishers to trick users that have learned to click on links in messages that cannot be encrypted ...  maybe we should just write "see 'Help' for details". 

btw. it's not necessarily a re-installation of Delta Chat causing the problem in the second point - it may also be Thunderbird, K-9 or others. so maybe "In case you re-installed Delta Chat or another E-Mail-Program on this or another device ..."

![screenshot_1523963827](https://user-images.githubusercontent.com/9800740/38866827-707475b4-4242-11e8-8d9a-65edfbaa9183.png)

**Comment by r10s** [comment] 2018-04-17 11:41
update: i also removed the hint to the help - the help should be opened on the newly installed device / E-Mail-Prorgram, so I think the user should search for help there. Added a hint to the Autocrypt Setup Message instead, more experienced users will know what other pgp-alternatives they have, i think.

![screenshot_1523965093](https://user-images.githubusercontent.com/9800740/38867666-f5da547e-4244-11e8-9080-d63e9e233809.png)

**Comment by testbird** [comment] 2018-04-17 12:45
What could still be improved seems to be the consistency of managing the (Delta Chat) autocypt setup.
* Refer to the same words in all places
* Maybe consolidate and show the transferable setup details in the "Name and Status" page (rename it to Email Account Setup)?
* Rename and move the "start autocrypt-key-transfer" menu button to the "Name and Status" page?

**Comment by r10s** [comment] 2018-04-17 13:54
> Should users get accustomed to re-send messages to new keys upon requests?

well, it's the request from a known friend they've contacted before, i think this could be a working "social" protocol. if there's any doubt they can ask or do an out-of-band verification.

> A specific risk of the seemingly easy "just reply" advice would be to lead to a very frustrating ping-pong effect, or not?

no. the sender gets the new key when receiving "please send the message again" and is able to encrypt correctly then.

> Therefore my emphasizing of proper advice to import during install (setup wizard) and on error (the message at hand).

Yes, on install, we can be more specific, but this is another issue :)
When receiving the error, this issue is about, the most common problem is a different one, imho.

> Rename and move the "start autocrypt-key-transfer" menu button to "Send Autocrypt Setup Message" in the "Email Account Setup" page?

Yes, "Send Autocrypt Setup Message" is far better; K-9 will also use this term, see https://github.com/k9mail/k-9/pull/3342

**Comment by testbird** [comment] 2018-04-17 14:55
>> A specific risk of the seemingly easy "just reply" advice would be to lead to a very frustrating ping-pong effect, or not?

> no. the sender gets the new key when receiving "please send the message again" and is able to encrypt correctly then.

That's only one half of what happens, if I understand this correctly:

Suppose, user A has made new install a2 and receives a message from an old friend F (designated for a1).

Instead of importing the a1 setup, A replies to the message from a2 and asks to re-send the message.

F gets the reply and re-sends the message to a2.

Now, A can read the message at its second installation a2.

However, the message is now not readable at the first installation a1, and following the "just reply" advice on a1 will just lead to a frustrating ping-pong loop.

**Comment by r10s** [comment] 2018-04-17 15:28
that's correct _if_ the user has made a second installation which requires an Autocrypt Setup Message that is handled in advice 2.

if there is no new installation (i think this is the more frequent case) and the message is shown, the advice to "just reply" would normally fix the problem.

i think this is fine. maybe we can just give the current text a try, and see what will happen.

**Comment by testbird** [comment] 2018-04-17 16:16
> that's correct if the user has made a second installation which requires an Autocrypt Setup Message that is handled in advice 2.

Ok, then the message should definitely handle that case first, just as discovered before...

> regarding that logic. it is better to keep the order as you suggested - if setup-changed, transfer setup, else ask user to send again

It's an easy condition to exclude for a user anyway. As the ping-pong consequence warrants it, using "should" or even "need" in the message even simplifies it further.

> maybe we can just give the current text a try, and see what will happen.

I made adapted versions for both drafts:

```
This message was not encrypted for your current (Delta Chat) autocrypt setup.

- If you have been using another installation before (and it is still available):
  You need to transfer the setup, eg. (Delta Chat) by going to 
  "Configuration -> Email Account Setup -> Send Autocrypt Setup Message" 
  on the device that you installed first.

- Otherwise (and if the sender may not have encrypted for your setup, by mistake):
  Keep using your current setup, by replying and
  asking the sender to verify and send the message again.
```

```
This message can not be decrypted.

* In case you have been using another installation of Delta Chat or an (autocrypt) 
  E-Mail program before,
  you need to import the setup from there, eg. by sending an Autocrypt Setup Message 
  from there.

* Otherwise, reply to the sender, and ask to verify and send the message again.
  (Only without autocrypt, will the sender have to adapt the encryption settings manually.)
```

**Comment by Ji-eF** [comment] 2018-04-17 16:32
````
This message can not be decrypted.
* Import your keys from the previous installation of Delta-Chat (or E-mail program [unnecessary?])
* Easy solution : Ask the sender to send back this message.
  Drawback : You won't be able to read your previous messages anymore.

**Comment by testbird** [comment] 2018-04-17 16:43
Thanks Ji-eF, I removed the repetition as you suggested, but kept the ", eg." to hint that there are other ways to export and import the key, ok?

Or, adapting your draft:
```
This message can not be decrypted.

* You may need to import your setup from a previous installation, 
  eg. Send Autocrypt Setup Message.
* Only otherwise, ask the sender to verify and send this message again.
```
The drawback (ping-pong) is even worse, but  maybe it doesn't need to be mentioned.

**Comment by testbird** [comment] 2018-04-17 21:14
> maybe we can just give the current text a try, and see what will happen.

I have qualms about that. What can happen, if users follow the advice?:

Suppose again, the user A is at a new installation (a2), reads:

* It might already help to simply reply to this message and ask the sender to send the message again.

and tries this. But afterwards can't read further messages on the old installation (a1), and this time decides to follow the second advice:

* In case you re-installed Delta Chat or another E-Mail-program on this or another device you may want to send an Autocrypt Setup Message from there.

A sends a setup message from a2 and overwrites the old setup. :-(

---
I'd say the adapted Ji-eF inspired version (one post above) should be safer.

**Comment by testbird** [comment] 2018-04-20 14:00
I'll just provide a pull request to change the order of the advice, and saying "if used another ...should import, otherwise, ..."

**Comment by testbird** [comment] 2018-04-22 12:45
If you read this or that above, doesn't it recommend to import from the re-installed (new) deltachat or email? I can't be sure? What about a new device/installation? And, it could be hard to find the "send autocrypt message" in any other email program. That's why the text in the pull request mentions differs in the first point, and tries to associate things to the same words that are used in the menus and options (autocrypt, setup, verify).

Generally, I don't know if basic liking is a first rank criteria for error and help texts.
It seems to be a different idea than not to produce false ambiguities and follow-up problems, when avoidable.


Nevertheless, maybe I would like a litte addy to the main error and "might have to" better than the "should":
```
This message cannot be decrypted (with your current autocrypt setup).
* If you've previously used another autocrypt installation (Delta Chat or other),
  you still might have to import your older setup, eg. use "Send Autocrypt Setup Message" there.
```

**Comment by r10s** [comment] 2018-04-22 20:06
> If you read this or that above, doesn't it recommend to import from the re-installed (new) deltachat or email?

i do not think that "you may want to" is more a recommendation than "you might still have to". it is true optional in my understanding.

> And, it could be hard to find the "send autocrypt message" in any other email program.

this is true, but we cannot help on a little error message on this point - esp. as the "otherwise" part is the more likely one imho.

however, maybe it already gets too technical, also "share" may be misunderstood as being to close to a setup messages, see https://github.com/deltachat/deltachat-android/issues/293#issuecomment-381598084

btw. asking the sender to "verify" - what would es expect the sender to do?

all in all, I think we cannot solve this 100% here, maybe this needs ui testing and more feedback. 

i also think, the current text is not _that_ bad and has no larger issues. so, for now, i would just keep it and go forward to other problems :)

**Comment by testbird** [comment] 2018-04-22 20:41
Yes, sure, nevermind.

It's just an uncomfy experience, that going forward with other problems, leaving small an reachable fixes aside "for now", tends to create more problems later (which are harder to re-approach (and take longer) later when things have evolved and the issue faded away).

---

> i do not think that "you may want to" is more a recommendation than "you might still have to". it is true optional in my understanding.

Yes it's optional, but IMHO it would make sense to stress (even if just so lightly) that one should make sure to import the old setup, if not already done so (too avoid unecessary key changes (and thus further views of that error message, when old contacts write).

>  "verify" - what would es expect the sender to do?

I don't know the new features, thought you just implemented that, and that using a new setup makes users "unverified" at their contacts (and confuses contacts).

> has no larger issues

What about advising to send setup message from the newer install (tablet -> phone, or new phone -> old phone)? https://github.com/deltachat/deltachat-android/issues/293#issuecomment-382148838

If some nerd friend couln't manually set up an autocrypt key, thats not much of an issue, yet unnecessary announcing a new setup (fork)?

> "share" may be misunderstood

Yes, good point, maybe "announce"?

**Comment by comradekingu** [comment] 2018-04-23 23:08
> Unreadable message - it was encrypted with a public key you don't have the private counterpart to.
> 
> * New Autocrypt installations generate new keys, import a key from an old one by sending an Autocrypt Setup message to it.
> 
> * To keep using your current key, verify you are talking to the right person through other private means, and ask the person to resend the message.

**Comment by r10s** [comment] 2018-04-24 09:11
@comradekingu hi :)
- in general, Autocrypt recommends not using the "key" language, "setup" seems to be better for new user, we also follow this approach in other parts.
- setup messages are initiated by the "old setup", not by sending "an Autocrypt Setup message to it".

**Comment by testbird** [comment] 2018-04-24 10:45
> Autocrypt recommends not using the "key" language

That recommendation may, unfortunately, just go a little too far. 

The word key is well known and generally understood -- only the "public key" concept has no analog --, it's easily understood that a key is needed to decrypt, and it should not be given away.

**Comment by comradekingu** [comment] 2018-04-24 21:40
> Unreadable encrypted message
> 
> If it was meant for an old account of yours, send an Autocrypt Setup message from the old to your new device to read it, and older messages on that account.
> 
> To keep using this Autocrypt setup instead, make sure you are talking to the right person through other private means, and ask the person to resend the message.

**Comment by r10s** [comment] 2018-05-25 16:21
i think, we can close this issue for now - if ui testing brings up new insights, we can think it over.

**Closed by r10s** 2018-05-25 16:21 UTC
