### ISSUE TITLE
Sharing cutted Screenshot fails

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#2439] opened 2022-12-25 15:33 UTC
- Android version: 13
- Device: Pixel 6A
- Delta Chat version: 1.34.4
- Steps to reproduce the problem:
1. Make a Screenshot
2. Cut the Screenshot
3. share this cutted Screenshot
4. a empty window is shown in DC

- Screenshots: Will follow if needed
- Logs: Will follow if needed

**Comment by webratte** [comment] 2022-12-27 15:33
This happens only if I cut the screenshot. Direct share the screenshot without edit it works. On my phone with Android 12 this issue doesn't exist.

It's not my phone. It's my wife's phone. Maybe I will test it later with her phone and the current nightly.

**Comment by Hocuri** [comment] 2022-12-28 15:19
Is this a regression, or does this also happen with the previous Android version?

**Comment by webratte** [comment] 2022-12-28 15:26
In Adroid 12 it works fine.
In Android 13 this issue happens.

Am 28. Dezember 2022 16:19:31 MEZ schrieb Hocuri ***@***.***>:

**Comment by Hocuri** [comment] 2022-12-28 15:59
No, I meant, if it works with DeltaChat 1.34.5.

**Comment by webratte** [comment] 2022-12-28 16:19
Sorry 😀
I don't know. I didn't tested it yet with this version.
My wife (she has this newer phone) is using the play store version 1.34.4
Is this Version 1.34.5 already released in play store?
In this case, I will report until she has the update.

**Comment by gerryfrancis** [comment] 2023-01-02 15:03
@webratte The cut screenshot (cartoon) image that you shared in the testing group recently causes an empty bubble on my device running Android 11, too, so this issue is not related to Android 13 only. In fact, it is a duplicate of https://github.com/deltachat/deltachat-android/issues/1915 .

Could you verify with the very same image file on your Android 12 device, please? Many thanks in advance!

**Comment by webratte** [comment] 2023-01-02 17:11
I already tested it on Android 12. It also shows a empty Bubble.

But I think it's not related to the image size. If I create a similar image on Android 12 it works fine. It only happens with images made with Android 13 as described.

**Comment by Hocuri** [comment] 2023-01-16 14:39
No, updating doesn't help here :/

**Comment by gerryfrancis** [comment] 2023-01-16 15:19
I am convinced that the origin is there: https://github.com/deltachat/deltachat-android/issues/1915

@adbenitez What is the current status on that?

**Comment by Hocuri** [comment] 2023-01-16 15:54
No, sending an image with the exact same resolution doesn't reproduce the issue.

In fact, I can only reproduce the issue with the image that was sent into the Testing chat. If i crop or otherwise edit the image in DC's image-edit-activity and then send it, the problem doesn't occur, either. It's even enough to open the image-edit-activity, confirm without any editing whatsoever, and then send it for the bug to go away.

**Comment by webratte** [comment] 2023-01-16 16:11
It seems that happens only with pics edited with Android 13.
My wife use only Android 13/Google Pixel tools to edit pics.

**Closed** 2023-06-10 13:04 UTC
Labels: bug

**Comment by Hocuri** [comment] 2023-06-20 13:24
@webratte was this actually fixed by #2587?

**Comment by hpk42** [comment] 2023-06-20 14:32
better stay alive and enjoy your holidays then :)

**Comment by webratte** [comment] 2023-07-13 04:13
Just want to confirm.
I can't reproduce this.

So it seems, you fixed it 👍🏼

Thank you very much.
