### ISSUE TITLE
Sometimes sending a message is taking forever when it actually was sent!

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#788] opened 2019-03-25 23:47 UTC
Sometimes while sending a message, apparently due to instabilities in the network, the message is sent (I receive the self-bcc copy) but Delta Chat still keeps trying to send the message always failing to do so.

- Platform (android/blackberry/anbox): Android 6.0 (and other people had reported the same problem)
- Device: BLU
- Delta Chat Version: 0.200.0
- Screenshots:
![Screenshot_20190311-204914](https://user-images.githubusercontent.com/24558636/54961191-13c4be80-4f36-11e9-8be9-5ea4dcfc8590.png)

**Comment by testbird** [comment] 2019-03-29 20:27
Could be caused by the too fast increasing delay due to the missing fix https://github.com/deltachat/deltachat-core/pull/446#issuecomment-441385285 for temporary server errors https://github.com/deltachat/deltachat-android/issues/602

But I am wondering why do you say the message was actually sent already? If you get the BCC the message should be out, maybe the smtp error is from the later moving job?

**Comment by adbenitez** [comment] 2019-03-29 21:43
yes, the message was sent, I received the self copy, and the app keeps trying to sending but gets that error(I guess the errror is related to the fact that the email was already sent) restarting the app causes the error to appear, even when the message was already sent, seems like the app for some reason is not able to send it again(luckily)

**Comment by r10s** [comment] 2019-10-28 14:24
i think this is fixed by core-rust.

**Closed by r10s** 2019-10-28 14:24 UTC
