### ISSUE TITLE
DeltaChat doesn't work in background

### ISSUE THREAD

**Issue by CompuRoot** [deltachat/deltachat-android#1553] opened 2020-08-13 13:58 UTC
- Operating System: Android 4.3
- Delta Chat Version: 1.12.2 (from F-Droid)
- Expected behavior: work in background, and throw notifications as it was before
- Actual behavior: DC need to be open manually to get received messages
- Steps to reproduce the problem: Send messages to affected device, result - no notifications

**Comment by RubenDavidPerezJimenez** [comment] 2020-08-13 14:06
#1525

**Comment by RubenDavidPerezJimenez** [comment] 2020-08-13 14:09
Duplicate of #1525 
I don't know how referring to my issue

**Comment by r10s** [comment] 2020-08-13 14:25
> I don't know how referring to my issue

you just did :)
closing this as it is probably a duplicate of #1525 and there are already some more background details. @CompuRoot if possible, add log and further information there.

**Closed by r10s** 2020-08-13 14:25 UTC
