### ISSUE TITLE
Content of attached PDF file is shown empty

### ISSUE THREAD

**Issue by tmaeggle** [deltachat/deltachat-android#1242] opened 2020-02-07 12:00 UTC
- Android version: 9.0
- Device: Samsung Galaxy Note 9 (N960F); Huawai P20 pro
- Delta Chat version: 1.1.2
- Expected behavior: The linked PDF app displays the content of the document.
- Actual behavior: The content of the PDF document is empty 
- Steps to reproduce the problem: 
-- Attach a pdf file on any android device and any conversation and send it
-- try to open the pdf file either on the sending app (android) or on the receiving app (android)
-- the same file can be viewed in the iOS app (v1.0.2)  
- Screenshots: attached
- Logs: attached

[deltachat-log-20200207-124218.txt](https://github.com/deltachat/deltachat-android/files/4170657/deltachat-log-20200207-124218.txt)
![Screenshot_20200207-125205_Delta Chat](https://user-images.githubusercontent.com/60601819/74028674-36739080-49ab-11ea-836a-3ffe425502d1.jpg)
![Screenshot_20200207-125216_Drive](https://user-images.githubusercontent.com/60601819/74028676-37a4bd80-49ab-11ea-864c-2020026bdc30.jpg)

**Comment by r10s** [comment] 2020-02-07 21:44
the screen that shows the pdf is not Delta Chat, so not sure, if that can be fixed by Delta Chat. can you please try if the PDF shows correctly when you open it directly? or when using another PDF viewer (eg. DocumentView from F-Droid is known to work)?

**Comment by angelo-fuchs** [comment] 2020-06-05 16:41
can't reproduce. Closing until further reports suggest that this is an error we can do something about.
@tmaeggle could you test again with the PDF attached here (just some file on my disk that I tried and worked): [stride.pdf](https://github.com/deltachat/deltachat-android/files/4737415/stride.pdf)
If it fails too, could you test with a different PDF viewer like r10s suggested? I personally use ReadEra.
If that fails as well we might have an permission problem and need to dig deeper.

**Closed by angelo-fuchs** 2020-06-05 16:41 UTC
